version: '1.0'
name: ai-agents
description: A coordinated multi-agent system for software developing support Claude
  Code, GitHub Copilot CLI and VS Code Copilot
beads:
  default_enabled: false
subjects: {}
auto_detect:
  enabled: true
  method: path_match
project_id: cdb34e2c-4f26-494e-a820-f3e3ccfedaee
