name: 'Workflow Debounce'
description: 'Introduces a delay to allow GitHub Actions concurrency control to cancel duplicate runs'
author: 'AI Agents Team'

branding:
  icon: 'clock'
  color: 'blue'

inputs:
  delay-seconds:
    description: 'Delay duration in seconds'
    required: false
    default: '10'
  workflow-name:
    description: 'Workflow name for logging'
    required: true
  concurrency-group:
    description: 'Concurrency group identifier'
    required: true

outputs:
  debounce-start:
    description: 'Debouncing start timestamp (ISO 8601)'
    value: ${{ steps.debounce.outputs.start }}
  debounce-end:
    description: 'Debouncing end timestamp (ISO 8601)'
    value: ${{ steps.debounce.outputs.end }}
  debounce-duration:
    description: 'Actual delay duration in seconds'
    value: ${{ steps.debounce.outputs.duration }}

runs:
  using: 'composite'
  steps:
    - name: Debounce workflow run
      id: debounce
      shell: bash
      run: |
        # Capture start time
        START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        START_EPOCH=$(date +%s)
        
        echo "=== Workflow Debouncing ==="
        echo "Workflow: ${{ inputs.workflow-name }}"
        echo "Concurrency Group: ${{ inputs.concurrency-group }}"
        echo "Delay: ${{ inputs.delay-seconds }} seconds"
        echo "Start Time: ${START_TIME}"
        echo ""
        echo "Purpose: Creating cancellation window for duplicate runs"
        echo "Note: This delay allows GitHub Actions' cancel-in-progress to take effect"
        echo ""
        
        # Execute debouncing delay
        echo "Sleeping for ${{ inputs.delay-seconds }} seconds..."
        sleep ${{ inputs.delay-seconds }}
        
        # Capture end time
        END_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        END_EPOCH=$(date +%s)
        DURATION=$((END_EPOCH - START_EPOCH))
        
        echo ""
        echo "=== Debouncing Complete ==="
        echo "End Time: ${END_TIME}"
        echo "Actual Duration: ${DURATION} seconds"
        echo "Proceeding with workflow execution..."
        
        # Set outputs
        echo "start=${START_TIME}" >> $GITHUB_OUTPUT
        echo "end=${END_TIME}" >> $GITHUB_OUTPUT
        echo "duration=${DURATION}" >> $GITHUB_OUTPUT
        
        # Add to job summary
        cat >> $GITHUB_STEP_SUMMARY <<EOF
        ## Workflow Debouncing Applied
        
        | Metric | Value |
        |--------|-------|
        | **Workflow** | ${{ inputs.workflow-name }} |
        | **Concurrency Group** | ${{ inputs.concurrency-group }} |
        | **Delay Configured** | ${{ inputs.delay-seconds }}s |
        | **Actual Duration** | ${DURATION}s |
        | **Start Time** | ${START_TIME} |
        | **End Time** | ${END_TIME} |
        
        **Purpose**: Provide cancellation window for GitHub Actions to terminate duplicate runs
        
        **Impact**: This delay helps reduce race conditions where multiple workflow runs start before cancellation takes effect.
        EOF
