"""Shared CommonMark oracle for the two Markdown fence scanners.

Both `fix_fences.py` and `prose_lint.py` decide which lines sit inside a fenced
code block, and both must measure a fence marker's indent from its containing
list item rather than from column zero. The rules that govern that are easy to
state and easy to get subtly wrong, so the cases below are checked against
`markdown-it-py`, a CommonMark reference implementation and a declared
dependency of this repository, instead of against hand-written expectations.

Scope. This oracle began as list-container handling only and has grown past
that: it now also carries line-terminator cases and closing-fence info-string
cases, which involve no list marker at all. The scanners diverge
from CommonMark elsewhere on purpose: a fence carrying an info string inside an
open block is content to CommonMark but a mistaken closer to `fix_fences.py`,
which is the defect that tool exists to repair.

Known limitations out of scope here, listed rather than counted: the count
said two while a third sat directly beneath it. A raw HTML block (for example
`<example ...>`) swallows a following fence, so the scanners read a fence there
that CommonMark does not. And a blockquote prefix is never stripped, which has
TWO consequences and only one of them was measured for a long time. A fence
inside a `>` block is invisible, and that half is a miss: six shapes diverge
and `--write` changes none of them. The half that went unmeasured is a
blockquote INTERRUPTING a paragraph. CommonMark ends the paragraph there and
lazily continues the quote, so a following `2.` opens a list; we keep the
paragraph open, rule 4 vetoes the marker, and the real closing fence becomes a
fresh opener that `--write` then answers with a stray closer. Two shapes of
twelve, and both are corruptions. `text` / `> q` / `more` / `2.` and a fence
carries no link reference definition at all, so this is the container model
and not rule 16. Closing it means modelling the `>` container, lazy
continuation included, which is why it is still listed here rather than fixed.
A third joined them, found by an adversarial audit rather than by any ratchet.
A setext `===` underline directly under a list item, followed by a lazy
continuation and then an indented fence, leaves the fence unseen. Measured the
way the blockquote gap was, over seven shapes run through `--write`: four
diverge and NONE is changed by the repair, so it is a miss and not a bad
write. `---` under the same item agrees already, which is why rule 11 landed
covering `-` and left this. Closing it means tracking where a setext underline
sits relative to its container, not just that it occurred.

A fourth, and the only one here whose obvious fix was measured and REJECTED.
A backslash in a link destination is treated as escaping whatever follows it.
CommonMark says an escape works only before ASCII punctuation, so a backslash
before a space should leave the space that ends a destination. Two shapes of sixty-four disagree
because of it: an escaped space and an escaped tab. Implementing the spec rule
was measured before being believed, and it is far worse: it takes those
sixty-four from 62 agreeing to 34, and turns 30 of them into `--write`
corruptions, because the reference parser accepts a backslash followed by a
control character where the spec-derived rule rejects it. The escaped-tab
shape has a second cause anyway, `_relative` expanding tabs before the grammar
sees them. So the permissive rule stays, with two known-wrong shapes, because
the correct-sounding one is measurably wrong fifteen times as often.

None of them is generated by the fuzzer below, deliberately: all are
known constants, and folding a constant into a ratchet makes later movement
harder to attribute. Stated precisely, because an earlier wording was not:
`_fuzz_line` DOES emit a `> quote` line. What it never emits is a fence
marker inside a blockquote, which is the actual excluded shape. A blockquote
carrying ordinary prose is generated and is not a known constant.

Two others used to be listed here and were implemented instead, because in each
case the argument for tolerating them was that the gap only made the scanners
miss a fence, and measurement showed the opposite. Both left a block open past
its real end, so `--write` appended a closing fence to well-formed documents.
That is why the blockquote gap above is stated with a measurement rather than
with the same argument. Do not repeat it without measuring; see rules 9 and 10
in `_ListContainers`.

What remains in the fuzz residue below is two documents, and they share almost
nothing. Both are pure under-detections and both carry a tab. Beyond that:
one has five columns of marker padding, an empty item and a thematic break,
and is the only one `--write` still mutates; the other has a maximum of two
columns of padding, no empty item and no thematic break, and carries U+3000
in a fence info string with U+00A0 as a marker remainder. Do not summarize
them as one shape: two earlier attempts did and both were wrong.

Do not widen these cases into those areas without deciding what the intended
behavior is first. The fuzz baselines below are what bound them.
"""

from __future__ import annotations

import re

from commonmark_link_cases import LINK_REFERENCE_CASES
from markdown_it import MarkdownIt

_MD = MarkdownIt("commonmark")


def reference_lines(text: str) -> list[str]:
    """Split *text* the way the reference parser numbers lines.

    NOT `str.splitlines()`. `markdown-it-py` normalizes CRLF and CR and then
    splits on newlines only, so a token's `map` is indexed in THAT numbering.
    `str.splitlines()` also breaks on U+000B, U+000C, U+001C to U+001E,
    U+0085, U+2028 and U+2029, which shifts every later entry and makes the
    blank filter below read a different line than the one the token names.

    Measured: on documents carrying any of those characters the two splitters
    give the oracle different answers, so this is not cosmetic. The oracle is
    the ground truth for both scanners, and a ground truth that disagrees with
    itself depending on how it is asked is worse than a wrong scanner.
    """
    lines = re.split(r"\r\n|\r|\n", text)
    if lines and lines[-1] == "":
        lines.pop()  # text ended with a terminator; no empty final line
    return lines


def oracle_fence_lines(text: str) -> set[int]:
    """Return 0-indexed non-blank lines inside a CommonMark fenced code block.

    Blank lines are excluded because they carry no prose either way, so
    including them would measure the comparison rather than the scanner.
    """
    source = reference_lines(text)
    inside: set[int] = set()
    for token in _MD.parse(text):
        if token.type == "fence" and token.map:
            start, stop = token.map
            inside.update(
                index for index in range(start, min(stop, len(source))) if source[index] != ""
            )
    return inside


# Each case is named for the CommonMark rule it exercises. `_ListContainers`
# carries sixteen numbered rules and every one was a real defect first,
# most reported in review and the rest found by the fuzzer below; each was
# reproduced against the reference parser before being fixed. The remaining
# cases guard the opposite direction, that a fix did not make the scanners
# permissive. Keep this description and the rule numbering in step: an earlier
# version said four, and stayed at four while the count reached eleven.
# The inventory below pins `CASES` against silent shrinkage. `CASES` decides
# both the fixtures AND how many parametrized tests each suite collects, so
# deleting a key deletes a contract rather than failing one, and the suite
# still reports all green. That is the same self-disarm shape `FUZZ_BASELINE`
# carries, and it bites harder here: the fuzzer emits no `[` in any of its
# 6,000 documents, so nothing else covers rule 16 at all.
#
# A count alone would miss a delete-one-add-one edit, so a digest goes with it.
# The digest covers each case's TEXT as well as its name: hashing names alone
# left a hole one level down, where swapping a demanding fixture body for a
# trivially balanced one keeps the count and the digest identical while every
# parametrized suite goes quietly green. Both are asserted by a NON-parametrized
# test in each suite, which is what makes them run when the dict is empty.
# Re-measure, never hand-edit:
#
#     uv run python -c "import sys; sys.path.insert(0,'tests/skills'); \
#       import commonmark_fence_cases as O; print(O.case_inventory())"
CASE_COUNT = 142
CASE_DIGEST = "f2307cc4c7d855d4"

# The cases where a balanced document is SUPPOSED to change under `--write`,
# named rather than detected. Membership used to come from asking the scanner
# whether it had reported a mistaken closer, which let a regression that
# invented one exempt its own document from the corruption assertion. Data
# cannot do that, and the digest above pins this list with the rest.
MISTAKEN_CLOSER_CASES = frozenset(
    {
        "U+00A0 does not blank a closing fence's info string",
        "U+3000 does not blank a closing fence's info string",
        "a tilde closer carrying U+00A0 does not close either",
    }
)


def case_inventory() -> tuple[int, str]:
    """Return the live (count, digest) of `CASES`, for comparison with the pin."""
    import hashlib

    payload = "\n".join(f"{name}\x00{CASES[name]}" for name in sorted(CASES))
    return len(CASES), hashlib.sha256(payload.encode()).hexdigest()[:16]


_CONTAINER_CASES: dict[str, str] = {
    # Rule 1: a marker more than three columns past its container is code.
    "marker over indented is code": "    - literal\n      ```\n      x\n",
    # Rule 2: five or more columns of padding is not all indentation.
    "padding of five columns": "-     literal\n      ```\n      x\n      ```\n",
    "padding of four columns": "-    item\n     ```\n     x\n     ```\n",
    # Rule 3: an item with no content on its line still opens a container.
    "empty item opens a container": "-\n    ```\n    x\n    ```\nafter\n",
    "empty item then nested item": "-\n  - inner\n\n    ```\n    x\n    ```\nafter\n",
    # Rule 4: only a non-empty item, ordered at 1, may interrupt a paragraph.
    "ordered two cannot interrupt": "Some prose.\n2. literal\n    ~~~\n    x\n    ~~~\nafter\n",
    "ordered one can interrupt": "Some prose.\n1. item\n    ~~~\n    x\n    ~~~\nafter\n",
    "empty item cannot interrupt": "Some prose.\n-\n    ~~~\n    x\n    ~~~\nafter\n",
    "ordered two after a blank line": "Some prose.\n\n2. item\n    ~~~\n    x\n    ~~~\nafter\n",
    # Sync before classify: a dedent closes its container before the indent test.
    "dedent before a top level opener": "- item\n~~~\ncode\n    ~~~\nafter\n",
    # Guards against an over-permissive container model.
    "nested item fence": "- item\n  - nested:\n\n    ```bash\n    x\n    ```\n\nDone.\n",
    "top level four space marker": "Text.\n\n    ~~~\n\nAfter.\n",
    "four columns past the container": "- item\n\n      ~~~\n\nAfter.\n",
    "blank line inside an item": "- item\n\n    ~~~\n    x\n    ~~~\n\nDone.\n",
    # Rule 4 detail: leading zeros do not change an ordered list's start value.
    "leading zero starts at one": ("Some prose.\n01. item\n    ~~~\n    x\n    ~~~\nafter\n"),
    "three leading zeros start at one": (
        "Some prose.\n001. item\n     ~~~\n     x\n     ~~~\nafter\n"
    ),
    "leading zero three cannot interrupt": (
        "Some prose.\n003. item\n     ~~~\n     x\n     ~~~\nafter\n"
    ),
    # Rule 5: a thematic break matches the bullet grammar but is not an item.
    "thematic break of stars": "* * *\n    ~~~\n    x\n    ~~~\nafter\n",
    "thematic break of dashes": "- - -\n    ~~~\n    x\n    ~~~\nafter\n",
    # Rule 6: a lazy continuation may dedent without closing its item.
    "lazy paragraph continuation": (
        "  1.  A paragraph\nwith two lines.\n\n      ```\n      x\n      ```\nafter\n"
    ),
    # Rule 7: paragraph state follows blocks, measured against the container.
    "a fence ends the paragraph": (
        "Para text.\n~~~\ncode\n~~~\n2. next\n    ```\n    y\n    ```\nafter\n"
    ),
    "heading indented inside a list": (
        "- item\n  - nested\n    # Heading\n    2. next\n"
        "        ```\n        y\n        ```\nafter\n"
    ),
    "thematic break inside a list": (
        "- item\n  - nested\n    ***\n    2. next\n        ```\n        y\n        ```\nafter\n"
    ),
    "indented code is not a paragraph": "     ```\n - \n     ```\n",
    "a marker with no padding is prose": " +  item\n1)text\n      ~~~\n",
    # Rule 8: an item may begin with at most one blank line.
    "blank line closes an empty item": "-\n\n    ```\n    x\n    ```\n",
    "blank line closes an empty ordered item": "1)\n\n    ```\n    x\n    ```\n",
    "two blanks close an empty item": "-\n\n\n    ```\n    x\n    ```\n",
    "a blank keeps a non-empty item open": "- item\n\n    ```\n    x\n    ```\n",
    # Rule 9: a marker line's remainder is re-parsed inside the item.
    "backtick fence on the marker line": "- ```\n  x\n  ```\n\nEnd.\n",
    "tilde fence on the marker line": "- ~~~\n  x\n  ~~~\n\nEnd.\n",
    "fence with an info string on the marker line": ("1. ~~~info\n   x\n   ~~~\n\nEnd.\n"),
    "two markers then a fence on one line": "- - ```\n    x\n    ```\n\nEnd.\n",
    "a heading on the marker line": ("- # heading\n2. item\n      ```\n      x\n      ```\n"),
    "two markers on one line": "- - a\n      ```\n      x\n      ```\n",
    # Rule 11: a setext underline ends the paragraph above it.
    "setext h1 ends the paragraph": ("Title\n===\n2. item\n    ~~~\n    robust\n    ~~~\n"),
    "single equals is a setext underline": ("Title\n=\n2. item\n    ~~~\n    x\n    ~~~\n"),
    "setext h2 ends the paragraph": "Title\n---\n2. item\n    ~~~\n    x\n    ~~~\n",
    "equals with no paragraph is prose": ("\n===\n2. item\n    ~~~\n    x\n    ~~~\n"),
    # Five columns of padding leave four behind, so a marker-line fence is
    # indented code. Stripping that indent opened a fence in literal content.
    "padding of five before a marker-line fence": ("-     ```\n     x\n     ```\nafter\n"),
    "padding of five before a marker-line tilde": ("-     ~~~\n     x\n     ~~~\nafter\n"),
    "padding of two before a marker-line fence": "-  ```\n   x\n   ```\nafter\n",
    # A backtick opening fence may not carry a backtick in its info string.
    "backtick in a fence info string": ("para\n```lang`x`\nrobust significant\n```\nafter\n"),
    "backtick info on a marker line": "- ```lang`x`\n  robust\n",
    # An ordered marker is ASCII digits only; Python's `\d` is not.
    "arabic-indic digits are not a marker": ("\u0661. item\n\n    ~~~\n    robust\n    ~~~\n"),
    "devanagari digits are not a marker": ("\u0967. item\n\n    ~~~\n    x\n    ~~~\n"),
    "ascii digits are a marker": "1. item\n\n   ~~~\n   x\n   ~~~\n",
    # A marker line does not itself open a paragraph; its remainder decides.
    "nested ordered on the marker line": (
        "- 2. item\n\n        ~~~\n        x\n        ~~~\nafter\n"
    ),
    "nested ordered one on the marker line": (
        "- 1. item\n\n        ~~~\n        x\n        ~~~\nafter\n"
    ),
    # Rules 9 and 12 composed: a marker, a nested marker, and a fence on one
    # line. The nested `2.` opens the first block inside the outer item, so
    # CommonMark accepts start 2 there.
    "marker, nested marker, then fence": "- 2. ~~~\n     x\n     ~~~\n",
    "marker, nested marker one, then fence": "- 1. ~~~\n     x\n     ~~~\n",
    # Rule 14: blank is spaces and tabs, not everything `str.strip()` removes.
    "non-breaking space is not padding": "-\u00a0\n    ```\n    x\n    ```\n",
    "non-breaking space line is not blank": "- ```\n  x\n\u00a0\nafter\n",
    "non-breaking space inside an item": "- ~~~\n  x\n\u00a0\n  ~~~\n",
    "a space after the marker is padding": "- \n    ```\n    x\n    ```\n",
    # A fence with no closing marker that the container ends anyway. The
    # public no-op assertion used to skip this, calling it unclosed.
    "dedent terminates a marker-line fence": "- ```\n  x\nafter\n",
    # Rule 15. The first three differ only in the third line's indent,
    # which is the whole of the rule: dedenting below the content column
    # closes the item, and the paragraph closes with it, so the `2.` is
    # judged where no paragraph is open. At the same level rule 4 still
    # vetoes it, which is why the second case must stay unfenced.
    "dedent past the content column reopens an ordered marker":
        "- text\n  more\n2. ```\ncode\n",
    # Negative control for rule 15, and it passed before rule 15 too. That is
    # the point: it pins that widening the veto did not over-fire. Deleting it
    # because it is green removes the only guard on the inverse failure.
    "same level keeps rule 4's paragraph veto":
        "- text\n  more\n  2. ```\n  code\n",
    "a one-column dedent is still a dedent":
        "  - text\n    more\n   2. ```\n   code\n",
    "an empty item's paragraph closes on dedent too":
        "- \n  more\n2. ```\ncode\n",
    # Rule 14 reaching the marker-line rescan. U+00A0 is item content to
    # CommonMark, so the remainder opens a paragraph and the content
    # column moves; `str.strip()` read it as an empty item and both
    # directions of mask were wrong.
    "U+00A0 remainder is item content, not an empty item":
        "- \u00a0\n  2. ```\n  not code\n",
    # This one also passes on the unfixed scanner, and is kept because it is
    # the case that caught the naive repair. Measured on all three variants:
    # unfixed AGREE, rule 14 applied ALONE DIVERGE, rule 14 plus rule 15 AGREE.
    # Rule 14 without rule 15 leaves the remainder's paragraph open across the
    # dedent, so rule 4 vetoes the `2.` and the fence is lost. It is a guard on
    # the composite, not on either half.
    "U+00A0 remainder after wide padding":
        "-  \u00a0\n  2. ```\n  not code\n",
    # A closing fence may be followed only by spaces and tabs, so a fence
    # carrying U+00A0 does not close its block. `str.strip()` read it as a
    # blank info string, closed the block two lines early, and `--write`
    # then appended a fence to a document the reference parser reads as
    # well formed. That is the corruption class this whole module exists to
    # prevent, and no ratchet could reach it.
    "U+00A0 does not blank a closing fence's info string":
        "```\nx\n```\u00a0\ny\n```\n",
    "U+3000 does not blank a closing fence's info string":
        "```\nx\n```\u3000\ny\n```\n",
    "a tilde closer carrying U+00A0 does not close either":
        "~~~\nx\n~~~\u00a0\ny\n~~~\n",
    # Controls: a real space and a real tab DO blank the info string, so the
    # fix must not swing the other way and reject a valid closer.
    "a trailing space still closes a fence":
        "```\nx\n``` \ny\n```\n",
    "a trailing tab still closes a fence":
        "```\nx\n```\t\ny\n```\n",
    # Line terminators. `str.splitlines` splits on characters CommonMark does
    # not treat as line endings, enumerated at `_LINE_SPLIT_RE` in either
    # scanner rather than counted here: this comment said `six` and the real
    # figure is eight. One prose line became two and the halves read as a
    # fence opener plus a body. The reference parser sees no
    # fence in any of these. `fix_fences` was already immune and `prose_lint`
    # was not, which is the kind of drift the parity test cannot see: it
    # compares the container class, and this lives outside it.
    "U+0085 is not a line terminator": "a\u0085```\nreal prose\n",
    "U+2028 is not a line terminator": "a\u2028```\nreal prose\n",
    "a form feed is not a line terminator": "a\x0c```\nreal prose\n",
    "a group separator is not a line terminator": "a\x1d```\nreal prose\n",
}


# One table, two files. The container cases above and the rule 16 cases beside
# them are merged here so both suites parametrize over a single dict and the
# inventory pin covers the union rather than half of it.
CASES: dict[str, str] = {**_CONTAINER_CASES, **LINK_REFERENCE_CASES}
