"""Shared CommonMark oracle for the two Markdown fence scanners.

Both `fix_fences.py` and `prose_lint.py` decide which lines sit inside a fenced
code block, and both must measure a fence marker's indent from its containing
list item rather than from column zero. The rules that govern that are easy to
state and easy to get subtly wrong, so the cases below are checked against
`markdown-it-py`, a CommonMark reference implementation and a declared
dependency of this repository, instead of against hand-written expectations.

Scope. This oracle began as list-container handling only and has grown past
that: it now also carries line-terminator cases and closing-fence info-string
cases, which involve no list marker at all. The scanners diverge
from CommonMark elsewhere on purpose: a fence carrying an info string inside an
open block is content to CommonMark but a mistaken closer to `fix_fences.py`,
which is the defect that tool exists to repair.

Known limitations out of scope here, listed rather than counted: the count
said two while a third sat directly beneath it. A raw HTML block (for example
`<example ...>`) swallows a following fence, so the scanners read a fence there
that CommonMark does not. And a blockquote prefix is never stripped, so a fence
inside a `>` block is invisible; that gap is a miss rather than a bad write,
checked by running `--write` over seven blockquote shapes rather than argued.
A third joined them, found by an adversarial audit rather than by any ratchet.
A setext `===` underline directly under a list item, followed by a lazy
continuation and then an indented fence, leaves the fence unseen. Measured the
way the blockquote gap was, over seven shapes run through `--write`: four
diverge and NONE is changed by the repair, so it is a miss and not a bad
write. `---` under the same item agrees already, which is why rule 11 landed
covering `-` and left this. Closing it means tracking where a setext underline
sits relative to its container, not just that it occurred.

None of them is generated by the fuzzer below, deliberately: all are
known constants, and folding a constant into a ratchet makes later movement
harder to attribute. Stated precisely, because an earlier wording was not:
`_fuzz_line` DOES emit a `> quote` line. What it never emits is a fence
marker inside a blockquote, which is the actual excluded shape. A blockquote
carrying ordinary prose is generated and is not a known constant.

Two others used to be listed here and were implemented instead, because in each
case the argument for tolerating them was that the gap only made the scanners
miss a fence, and measurement showed the opposite. Both left a block open past
its real end, so `--write` appended a closing fence to well-formed documents.
That is why the blockquote gap above is stated with a measurement rather than
with the same argument. Do not repeat it without measuring; see rules 9 and 10
in `_ListContainers`.

What remains in the fuzz residue below is two documents, and they share almost
nothing. Both are pure under-detections and both carry a tab. Beyond that:
one has five columns of marker padding, an empty item and a thematic break,
and is the only one `--write` still mutates; the other has a maximum of two
columns of padding, no empty item and no thematic break, and carries U+3000
in a fence info string with U+00A0 as a marker remainder. Do not summarize
them as one shape: two earlier attempts did and both were wrong.

Do not widen these cases into those areas without deciding what the intended
behavior is first. The fuzz baselines below are what bound them.
"""

from __future__ import annotations

import re

from markdown_it import MarkdownIt

_MD = MarkdownIt("commonmark")


def reference_lines(text: str) -> list[str]:
    """Split *text* the way the reference parser numbers lines.

    NOT `str.splitlines()`. `markdown-it-py` normalizes CRLF and CR and then
    splits on newlines only, so a token's `map` is indexed in THAT numbering.
    `str.splitlines()` also breaks on U+000B, U+000C, U+001C to U+001E,
    U+0085, U+2028 and U+2029, which shifts every later entry and makes the
    blank filter below read a different line than the one the token names.

    Measured: on documents carrying any of those characters the two splitters
    give the oracle different answers, so this is not cosmetic. The oracle is
    the ground truth for both scanners, and a ground truth that disagrees with
    itself depending on how it is asked is worse than a wrong scanner.
    """
    lines = re.split(r"\r\n|\r|\n", text)
    if lines and lines[-1] == "":
        lines.pop()  # text ended with a terminator; no empty final line
    return lines


def oracle_fence_lines(text: str) -> set[int]:
    """Return 0-indexed non-blank lines inside a CommonMark fenced code block.

    Blank lines are excluded because they carry no prose either way, so
    including them would measure the comparison rather than the scanner.
    """
    source = reference_lines(text)
    inside: set[int] = set()
    for token in _MD.parse(text):
        if token.type == "fence" and token.map:
            start, stop = token.map
            inside.update(
                index for index in range(start, min(stop, len(source))) if source[index] != ""
            )
    return inside


# Each case is named for the CommonMark rule it exercises. `_ListContainers`
# carries sixteen numbered rules and every one was a real defect first,
# most reported in review and the rest found by the fuzzer below; each was
# reproduced against the reference parser before being fixed. The remaining
# cases guard the opposite direction, that a fix did not make the scanners
# permissive. Keep this description and the rule numbering in step: an earlier
# version said four, and stayed at four while the count reached eleven.
# The inventory below pins `CASES` against silent shrinkage. `CASES` decides
# both the fixtures AND how many parametrized tests each suite collects, so
# deleting a key deletes a contract rather than failing one, and the suite
# still reports all green. That is the same self-disarm shape `FUZZ_BASELINE`
# carries, and it bites harder here: the fuzzer emits no `[` in any of its
# 6,000 documents, so nothing else covers rule 16 at all.
#
# A count alone would miss a delete-one-add-one edit, so the digest goes with
# it. Both are asserted by a NON-parametrized test in each suite, which is
# what makes them run when the dict is empty. Re-measure, never hand-edit:
#
#     uv run python -c "import sys,hashlib; sys.path.insert(0,'tests/skills'); \
#       import commonmark_fence_cases as O; n=sorted(O.CASES); \
#       print(len(n), hashlib.sha256(chr(10).join(n).encode()).hexdigest()[:16])"
CASE_COUNT = 108
CASE_DIGEST = "3da84182eaf4773d"


def case_inventory() -> tuple[int, str]:
    """Return the live (count, digest) of `CASES`, for comparison with the pin."""
    import hashlib

    names = sorted(CASES)
    return len(names), hashlib.sha256("\n".join(names).encode()).hexdigest()[:16]


CASES: dict[str, str] = {
    # Rule 1: a marker more than three columns past its container is code.
    "marker over indented is code": "    - literal\n      ```\n      x\n",
    # Rule 2: five or more columns of padding is not all indentation.
    "padding of five columns": "-     literal\n      ```\n      x\n      ```\n",
    "padding of four columns": "-    item\n     ```\n     x\n     ```\n",
    # Rule 3: an item with no content on its line still opens a container.
    "empty item opens a container": "-\n    ```\n    x\n    ```\nafter\n",
    "empty item then nested item": "-\n  - inner\n\n    ```\n    x\n    ```\nafter\n",
    # Rule 4: only a non-empty item, ordered at 1, may interrupt a paragraph.
    "ordered two cannot interrupt": "Some prose.\n2. literal\n    ~~~\n    x\n    ~~~\nafter\n",
    "ordered one can interrupt": "Some prose.\n1. item\n    ~~~\n    x\n    ~~~\nafter\n",
    "empty item cannot interrupt": "Some prose.\n-\n    ~~~\n    x\n    ~~~\nafter\n",
    "ordered two after a blank line": "Some prose.\n\n2. item\n    ~~~\n    x\n    ~~~\nafter\n",
    # Sync before classify: a dedent closes its container before the indent test.
    "dedent before a top level opener": "- item\n~~~\ncode\n    ~~~\nafter\n",
    # Guards against an over-permissive container model.
    "nested item fence": "- item\n  - nested:\n\n    ```bash\n    x\n    ```\n\nDone.\n",
    "top level four space marker": "Text.\n\n    ~~~\n\nAfter.\n",
    "four columns past the container": "- item\n\n      ~~~\n\nAfter.\n",
    "blank line inside an item": "- item\n\n    ~~~\n    x\n    ~~~\n\nDone.\n",
    # Rule 4 detail: leading zeros do not change an ordered list's start value.
    "leading zero starts at one": ("Some prose.\n01. item\n    ~~~\n    x\n    ~~~\nafter\n"),
    "three leading zeros start at one": (
        "Some prose.\n001. item\n     ~~~\n     x\n     ~~~\nafter\n"
    ),
    "leading zero three cannot interrupt": (
        "Some prose.\n003. item\n     ~~~\n     x\n     ~~~\nafter\n"
    ),
    # Rule 5: a thematic break matches the bullet grammar but is not an item.
    "thematic break of stars": "* * *\n    ~~~\n    x\n    ~~~\nafter\n",
    "thematic break of dashes": "- - -\n    ~~~\n    x\n    ~~~\nafter\n",
    # Rule 6: a lazy continuation may dedent without closing its item.
    "lazy paragraph continuation": (
        "  1.  A paragraph\nwith two lines.\n\n      ```\n      x\n      ```\nafter\n"
    ),
    # Rule 7: paragraph state follows blocks, measured against the container.
    "a fence ends the paragraph": (
        "Para text.\n~~~\ncode\n~~~\n2. next\n    ```\n    y\n    ```\nafter\n"
    ),
    "heading indented inside a list": (
        "- item\n  - nested\n    # Heading\n    2. next\n"
        "        ```\n        y\n        ```\nafter\n"
    ),
    "thematic break inside a list": (
        "- item\n  - nested\n    ***\n    2. next\n        ```\n        y\n        ```\nafter\n"
    ),
    "indented code is not a paragraph": "     ```\n - \n     ```\n",
    "a marker with no padding is prose": " +  item\n1)text\n      ~~~\n",
    # Rule 8: an item may begin with at most one blank line.
    "blank line closes an empty item": "-\n\n    ```\n    x\n    ```\n",
    "blank line closes an empty ordered item": "1)\n\n    ```\n    x\n    ```\n",
    "two blanks close an empty item": "-\n\n\n    ```\n    x\n    ```\n",
    "a blank keeps a non-empty item open": "- item\n\n    ```\n    x\n    ```\n",
    # Rule 9: a marker line's remainder is re-parsed inside the item.
    "backtick fence on the marker line": "- ```\n  x\n  ```\n\nEnd.\n",
    "tilde fence on the marker line": "- ~~~\n  x\n  ~~~\n\nEnd.\n",
    "fence with an info string on the marker line": ("1. ~~~info\n   x\n   ~~~\n\nEnd.\n"),
    "two markers then a fence on one line": "- - ```\n    x\n    ```\n\nEnd.\n",
    "a heading on the marker line": ("- # heading\n2. item\n      ```\n      x\n      ```\n"),
    "two markers on one line": "- - a\n      ```\n      x\n      ```\n",
    # Rule 11: a setext underline ends the paragraph above it.
    "setext h1 ends the paragraph": ("Title\n===\n2. item\n    ~~~\n    robust\n    ~~~\n"),
    "single equals is a setext underline": ("Title\n=\n2. item\n    ~~~\n    x\n    ~~~\n"),
    "setext h2 ends the paragraph": "Title\n---\n2. item\n    ~~~\n    x\n    ~~~\n",
    "equals with no paragraph is prose": ("\n===\n2. item\n    ~~~\n    x\n    ~~~\n"),
    # Five columns of padding leave four behind, so a marker-line fence is
    # indented code. Stripping that indent opened a fence in literal content.
    "padding of five before a marker-line fence": ("-     ```\n     x\n     ```\nafter\n"),
    "padding of five before a marker-line tilde": ("-     ~~~\n     x\n     ~~~\nafter\n"),
    "padding of two before a marker-line fence": "-  ```\n   x\n   ```\nafter\n",
    # A backtick opening fence may not carry a backtick in its info string.
    "backtick in a fence info string": ("para\n```lang`x`\nrobust significant\n```\nafter\n"),
    "backtick info on a marker line": "- ```lang`x`\n  robust\n",
    # An ordered marker is ASCII digits only; Python's `\d` is not.
    "arabic-indic digits are not a marker": ("\u0661. item\n\n    ~~~\n    robust\n    ~~~\n"),
    "devanagari digits are not a marker": ("\u0967. item\n\n    ~~~\n    x\n    ~~~\n"),
    "ascii digits are a marker": "1. item\n\n   ~~~\n   x\n   ~~~\n",
    # A marker line does not itself open a paragraph; its remainder decides.
    "nested ordered on the marker line": (
        "- 2. item\n\n        ~~~\n        x\n        ~~~\nafter\n"
    ),
    "nested ordered one on the marker line": (
        "- 1. item\n\n        ~~~\n        x\n        ~~~\nafter\n"
    ),
    # Rules 9 and 12 composed: a marker, a nested marker, and a fence on one
    # line. The nested `2.` opens the first block inside the outer item, so
    # CommonMark accepts start 2 there.
    "marker, nested marker, then fence": "- 2. ~~~\n     x\n     ~~~\n",
    "marker, nested marker one, then fence": "- 1. ~~~\n     x\n     ~~~\n",
    # Rule 14: blank is spaces and tabs, not everything `str.strip()` removes.
    "non-breaking space is not padding": "-\u00a0\n    ```\n    x\n    ```\n",
    "non-breaking space line is not blank": "- ```\n  x\n\u00a0\nafter\n",
    "non-breaking space inside an item": "- ~~~\n  x\n\u00a0\n  ~~~\n",
    "a space after the marker is padding": "- \n    ```\n    x\n    ```\n",
    # A fence with no closing marker that the container ends anyway. The
    # public no-op assertion used to skip this, calling it unclosed.
    "dedent terminates a marker-line fence": "- ```\n  x\nafter\n",
    # Rule 15. The first three differ only in the third line's indent,
    # which is the whole of the rule: dedenting below the content column
    # closes the item, and the paragraph closes with it, so the `2.` is
    # judged where no paragraph is open. At the same level rule 4 still
    # vetoes it, which is why the second case must stay unfenced.
    "dedent past the content column reopens an ordered marker":
        "- text\n  more\n2. ```\ncode\n",
    # Negative control for rule 15, and it passed before rule 15 too. That is
    # the point: it pins that widening the veto did not over-fire. Deleting it
    # because it is green removes the only guard on the inverse failure.
    "same level keeps rule 4's paragraph veto":
        "- text\n  more\n  2. ```\n  code\n",
    "a one-column dedent is still a dedent":
        "  - text\n    more\n   2. ```\n   code\n",
    "an empty item's paragraph closes on dedent too":
        "- \n  more\n2. ```\ncode\n",
    # Rule 14 reaching the marker-line rescan. U+00A0 is item content to
    # CommonMark, so the remainder opens a paragraph and the content
    # column moves; `str.strip()` read it as an empty item and both
    # directions of mask were wrong.
    "U+00A0 remainder is item content, not an empty item":
        "- \u00a0\n  2. ```\n  not code\n",
    # This one also passes on the unfixed scanner, and is kept because it is
    # the case that caught the naive repair. Measured on all three variants:
    # unfixed AGREE, rule 14 applied ALONE DIVERGE, rule 14 plus rule 15 AGREE.
    # Rule 14 without rule 15 leaves the remainder's paragraph open across the
    # dedent, so rule 4 vetoes the `2.` and the fence is lost. It is a guard on
    # the composite, not on either half.
    "U+00A0 remainder after wide padding":
        "-  \u00a0\n  2. ```\n  not code\n",
    # A closing fence may be followed only by spaces and tabs, so a fence
    # carrying U+00A0 does not close its block. `str.strip()` read it as a
    # blank info string, closed the block two lines early, and `--write`
    # then appended a fence to a document the reference parser reads as
    # well formed. That is the corruption class this whole module exists to
    # prevent, and no ratchet could reach it.
    "U+00A0 does not blank a closing fence's info string":
        "```\nx\n```\u00a0\ny\n```\n",
    "U+3000 does not blank a closing fence's info string":
        "```\nx\n```\u3000\ny\n```\n",
    "a tilde closer carrying U+00A0 does not close either":
        "~~~\nx\n~~~\u00a0\ny\n~~~\n",
    # Controls: a real space and a real tab DO blank the info string, so the
    # fix must not swing the other way and reject a valid closer.
    "a trailing space still closes a fence":
        "```\nx\n``` \ny\n```\n",
    "a trailing tab still closes a fence":
        "```\nx\n```\t\ny\n```\n",
    # Line terminators. `str.splitlines` splits on characters CommonMark does
    # not treat as line endings, enumerated at `_LINE_SPLIT_RE` in either
    # scanner rather than counted here: this comment said `six` and the real
    # figure is eight. One prose line became two and the halves read as a
    # fence opener plus a body. The reference parser sees no
    # fence in any of these. `fix_fences` was already immune and `prose_lint`
    # was not, which is the kind of drift the parity test cannot see: it
    # compares the container class, and this lives outside it.
    "U+0085 is not a line terminator": "a\u0085```\nreal prose\n",
    "U+2028 is not a line terminator": "a\u2028```\nreal prose\n",
    "a form feed is not a line terminator": "a\x0c```\nreal prose\n",
    "a group separator is not a line terminator": "a\x1d```\nreal prose\n",
    # Rule 16. A link reference definition is its own leaf block, so it does
    # not leave a paragraph open and a following `2.` may start a list. We
    # read it as prose, vetoed the `2.` under rule 4, and `--write` appended a
    # stray fence to a document the reference parser reads as balanced.
    "a link reference definition is not a paragraph":
        "[foo]: /url\n2. ```\n   code\n   ```\n",
    "a title on the next line continues a definition":
        "[foo]: /url\n\"T\"\n2. ```\n   code\n   ```\n",
    # Controls for rule 16, every one of which passed BEFORE it landed. They
    # pin the four ways it must NOT over-fire: a definition cannot interrupt
    # an open paragraph, a second title is prose once the definition has one,
    # an empty label is not a definition, and four columns of indent is code.
    "a definition cannot interrupt a paragraph":
        "text\n[foo]: /url\n2. ```\n   code\n   ```\n",
    "a second title is prose once the definition has one":
        "[foo]: /url \"A\"\n\"B\"\n2. ```\n   code\n   ```\n",
    "an empty link label is not a definition":
        "[]: /url\n2. ```\n   code\n   ```\n",
    "a definition indented four columns is code":
        "    [foo]: /url\n2. ```\n   code\n   ```\n",
    # Rule 16 continued. The destination and title must be COMPLETE. An
    # earlier version required only one non-space character after the colon,
    # so `[foo]: <broken` cleared paragraph state and `--write` appended a
    # fence to a document holding no fence at all. Measured against the
    # reference parser over 22 destination and title shapes.
    "an unclosed angle destination is not a definition":
        "[foo]: <broken\n2. ~~~\n   code\n",
    "an unclosed title is not a definition":
        "[foo]: /url \"unclosed\n2. ~~~\n   code\n   ~~~\n",
    "junk after a complete title is not a definition":
        "[foo]: /url \"T\" trailing\n2. ~~~\n   code\n   ~~~\n",
    "unbalanced parentheses in a destination are not a definition":
        "[foo]: /u(rl\n2. ~~~\n   code\n   ~~~\n",
    "a closed angle destination is a definition":
        "[foo]: <a b>\n2. ~~~\n   code\n   ~~~\n",
    # And the destination may start on the line after the label. The label
    # line stays paragraph text until a valid destination proves otherwise,
    # which the next two cases pin in both directions.
    "a destination on the following line completes a definition":
        "[foo]:\n/url\n2. ~~~\n   code\n   ~~~\n",
    "a label alone does not clear paragraph state":
        "[foo]:\n2. ~~~\n   code\n   ~~~\n",
    "a label followed by a bad destination stays a paragraph":
        "[foo]:\n<broken\n2. ~~~\n   code\n   ~~~\n",
    # Rule 16 continued. A fence INTERRUPTS a pending definition. The scanner
    # freezes container state for the whole fenced block, so nothing between
    # the opener and the closer is ever observed; a pending destination or
    # title therefore matched the first line AFTER the block, cleared
    # paragraph state the reference parser keeps open, and `--write` appended
    # a closer to a balanced document. Both pending states, both fence
    # characters, because the class is the freeze and not the syntax.
    "a fence interrupts a pending destination":
        "[foo]:\n```\nx\n```\n/url\n2. ~~~\n   code\n",
    "a fence interrupts a pending title":
        "[foo]: /url\n```\nx\n```\n\"T\"\n2. ~~~\n   code\n",
    "a tilde fence interrupts a pending destination":
        "[foo]:\n~~~\nx\n~~~\n/url\n2. ```\n   code\n",
    "a marker-line fence interrupts a pending destination":
        "[foo]:\n- ```\n  x\n  ```\n/url\n2. ~~~\n   code\n",
    # The control for that fix: with no definition pending, a fence followed
    # by an ordered marker behaves exactly as it did before.
    "a fence with no pending definition is unaffected":
        "text\n\n```\nx\n```\n\n2. item\n   ~~~\n   y\n   ~~~\n",
    # Rule 16 continued. A bracketless destination balances parentheses at ANY
    # depth, and a title may carry an escaped copy of its own delimiter. Both
    # were spelled as patterns with a fixed one level, so `[foo]: /u(r(l))` and
    # `[foo]: /url "a\\"b"` were read as prose while the reference parser reads
    # both as definitions. That kept a paragraph open, vetoed the marker below
    # it, and `--write` appended a fence to a balanced document. The depth is
    # why the destination is now a scanner and not a pattern: a pattern has to
    # pick a ceiling, and any ceiling is the next round of this same defect.
    "a destination nests parentheses two deep":
        "[foo]: /u(r(l))\n2. ```\n   code\n   ```\n",
    "a destination nests parentheses five deep":
        "[foo]: /a(((((b)))))\n2. ```\n   code\n   ```\n",
    "a title may escape its own quote":
        "[foo]: /url \"a\\\"b\"\n2. ```\n   code\n   ```\n",
    "a parenthesised title may escape its own bracket":
        "[foo]: /url (a\\)b)\n2. ```\n   code\n   ```\n",
    # The controls: unbalanced stays prose, in both directions, and an escaped
    # parenthesis does not count toward the balance.
    "an unclosed parenthesis is not a destination":
        "[foo]: /a((b)\n2. ```\n   code\n   ```\n",
    "a stray closing parenthesis is not a destination":
        "[foo]: /a(b))c\n2. ```\n   code\n   ```\n",
    "an escaped parenthesis does not open a group":
        "[foo]: /a\\(b\n2. ```\n   code\n   ```\n",
    # Rule 16 continued, and this one no reviewer named. A definition's
    # continuation belongs to the SAME leaf block, so CommonMark strips its
    # indent rather than reading indented code. The indent veto sat in front
    # of that test, so a four-column destination left the label line a
    # paragraph, rule 4 vetoed the marker below it, the real closing fence
    # became a fresh opener, and `--write` appended a closer to a balanced
    # document. Found by sweeping every line shape that can follow a pending
    # state, after a first sweep classified it as a miss: the probe asked
    # whether the tool reported NO defect, and the tool reported a false one.
    "a four-column destination continues a definition":
        "[foo]:\n    /url\n2. ```\n   code\n   ```\n",
    "a tab-indented destination continues a definition":
        "[foo]:\n\t/url\n2. ```\n   code\n   ```\n",
    "a four-column title continues a definition":
        "[foo]: /url\n    \"T\"\n2. ```\n   code\n   ```\n",
    # Controls: the veto still applies when nothing is pending, and when the
    # indented line is not a destination at all.
    "a four-column line with nothing pending is code":
        "text\n\n    code\n\n2. item\n   ```\n   x\n   ```\n",
    "a four-column non-destination does not continue a definition":
        "[foo]:\n    a b\n2. ```\n   code\n   ```\n",
    # Rule 16 continued, five more found by an adversarial sweep of the pending
    # state rather than by review. Every one is a `--write` corruption: the
    # reference parser reads the document as balanced and the tool appends to
    # it. They share one cause, that a pending definition is an OPEN LEAF BLOCK
    # and every block boundary has to say what it does to one.
    #
    # An indented code block is its own leaf block, so it ENDS a pending
    # definition. The indent veto returned before saying so, and the title two
    # lines down was then booked against a definition CommonMark had already
    # closed.
    "indented code ends a pending definition":
        "[foo]: /url\n    zzz\n\"t\"\n2. ```\n",
    # A new list item is a new container, and the pending state belonged to the
    # one outside it. The caller re-parses a marker's remainder inside the item
    # it just opened, and that pass consumed the stale flag.
    "a list marker ends a pending destination":
        "[foo]:\n- /url\nx\n  ```\nx\n",
    "a list marker ends a pending title":
        "[foo]: /url\n- \"t\"\nx\n  ```\nx\n",
    # And the mirror of that: a line CONTINUING a pending definition is a lazy
    # continuation, so it must not close the item holding it. Popping the item
    # on a dedented title moved the fence below it from inside the item to
    # column zero, where nothing could close it.
    "a dedented title does not close the item holding its definition":
        "- [foo]: /url\n\"title\"\n  ~~~\ncode\n",
    # CommonMark normalises a label before comparing it, so one holding only
    # whitespace normalises to empty and the line is not a definition. The
    # blank-label guard tested space and tab, which let every other Unicode
    # whitespace character through.
    "a label of only Unicode whitespace is not a definition":
        "[\u00a0]: /url\n2. item\n    ```\n    code\n",
    # The control: whitespace INSIDE a real label is still a definition.
    "Unicode whitespace inside a label is still a definition":
        "[a\u00a0b]: /url\n2. ```\n   code\n   ```\n",
}

