# Bot Authors Configuration
#
# Centralized configuration for bot author identification across the repository.
# Used by workflows, scripts, and agents to distinguish bot vs. human activity.
#
# Categories:
#   - reviewer: AI code review bots that provide PR feedback
#   - automation: CI/CD and dependency management bots
#   - repository: Bots specific to this repository
#
# See issue #276 for centralization rationale.
# See issue #282 for original centralization into Get-BotAuthors.

# AI code review bots
reviewer:
  - coderabbitai[bot]
  - github-copilot[bot]
  - gemini-code-assist[bot]
  - cursor[bot]

# CI/CD and dependency management bots
automation:
  - github-actions[bot]
  - dependabot[bot]

# Repository-specific bots
repository:
  - rjmurillo-bot
  - copilot-swe-agent[bot]
