# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration - ai-agents repository
#
# Tuned to reduce noise per Issue #326
# - Target: <20 review comments per PR (down from 97 on PR #249)
# - Focuses on high-confidence issues
# - Excludes generated files and agent artifacts

inheritance: true

reviews:
  # Use "chill" profile to reduce nitpicky feedback
  profile: "chill"

  # Exclude generated files and agent artifacts from review
  path_filters:
    - "!.agents/sessions/**"
    - "!.agents/analysis/**"
    - "!.serena/memories/**"
    - "!**/*.generated.*"
    - "!**/bin/**"
    - "!**/obj/**"

  # Reduce supplementary content
  collapse_walkthrough: true
  poem: false
  related_issues: false
  related_prs: false

  # Disable markdownlint (handled by .markdownlint-cli2.yaml)
  tools:
    markdownlint:
      enabled: false

  # Path-specific instructions for high-value reviews
  path_instructions:
    - path: "src/claude/**/*.md"
      instructions: |
        ## Agent Prompt Review Criteria
        ### P0 (Must Fix)
        - Missing required Front Matter
        - Model assignment violating ADR-002
        - Absolute paths in documentation
        ### P1 (Should Fix)
        - Missing Core Identity section
        - Drift from VS Code/Copilot CLI versions
        Prefix all comments with: [P0] or [P1]

        Only comment when you have HIGH CONFIDENCE (>80%) that an issue exists.
        Be concise: one sentence per comment when possible.
        Focus on actionable feedback, not observations.
        If uncertain whether something is an issue, do not comment.


