config:

# Line length - disabled for agent templates with long tool lists and descriptions

  MD013: false

# Table column style - disabled, tables are readable as-is

  MD060: false

# Ordered list prefix - disabled, sequential numbering (1/2/3) is more readable than all-1s

  MD029: false

# Fenced code language - REQUIRED for syntax highlighting

# Note: 3 known false positives in nested template files (retrospective.md, roadmap.md)

# where nested code blocks cause parser confusion

  MD040: true

# Inline HTML - allow specific elements, flag unescaped generic types

  MD033:
    allowed_elements:
      - br
      - kbd
      - sup
      - sub
      - details
      - summary
      - example

# Multiple H1 - allow in agent templates (frontmatter can create implicit H1)

  MD025:
    front_matter_title: ""

# Heading style - consistent ATX style (#)

  MD003:
    style: "atx"

# Code block style - consistent fenced style

  MD046:
    style: "fenced"

# Code fence style - consistent backticks

  MD048:
    style: "backtick"

# List marker style - consistent dashes

  MD004:
    style: "dash"

# Emphasis style - consistent asterisks

  MD049:
    style: "asterisk"

# Strong style - consistent asterisks

  MD050:
    style: "asterisk"

# First line heading - required by default

  MD041: true

globs:

- "**/*.md"
- "!node_modules/**"
- "!.agents/**"
- "!.serena/memories/**"
- "!.flowbaby/**"
- "!.claude/skills/**"

ignores:

- "node_modules/**"
- ".agents/**"
- ".flowbaby/**"

# User instruction files - these are APPENDED to existing user files during installation

# and cannot start with H1 (MD041). They are simple, controlled content that we manually

# verify. No inline suppression is used because it would propagate to user files

- "src/claude/CLAUDE.md"
- "src/vs-code-agents/copilot-instructions.md"
- "src/copilot-cli/copilot-instructions.md"

# Prompt template with intentional nested code blocks and XML-like tags (scratchpad, etc.)

# that confuse the parser. These are prompt content, not markdown errors

- "docs/autonomous-pr-monitor.md"

# Skills treated as third-party plugins per PR #331 - excluded via glob pattern above

# - ".claude/skills/adr-review/agent-prompts.md"  # No longer needed with glob exclusion
