# Markdownlint Configuration
#
# This config follows Prettier compatibility guidelines to enable seamless copying
# of markdown files between projects that use Prettier for formatting.
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Prettier.md

config:

  # ═══════════════════════════════════════════════════════════════════════════
  # PRETTIER-COMPATIBLE SETTINGS
  # These rules are disabled to avoid conflicts with Prettier formatting.
  # Reference: https://github.com/DavidAnson/markdownlint/blob/main/style/prettier.json
  # ═══════════════════════════════════════════════════════════════════════════

  # Heading style - disabled for Prettier compatibility
  MD003: false

  # Line length - disabled for Prettier compatibility
  # (Also needed for agent templates with long tool lists and descriptions)
  MD013: false

  # Ordered list prefix - disabled for Prettier compatibility
  # (Sequential numbering 1/2/3 is more readable than all-1s)
  MD029: false

  # Code fence style - disabled for Prettier compatibility
  MD048: false

  # Emphasis style - disabled for Prettier compatibility
  MD049: false

  # Strong style - disabled for Prettier compatibility
  MD050: false

  # ═══════════════════════════════════════════════════════════════════════════
  # PROJECT-SPECIFIC SETTINGS
  # These rules are project requirements that don't conflict with Prettier.
  # ═══════════════════════════════════════════════════════════════════════════

  # Table column style - disabled, tables are readable as-is
  MD060: false

  # Fenced code language - REQUIRED for syntax highlighting
  # Note: 3 known false positives in nested template files (retrospective.md, roadmap.md)
  # where nested code blocks cause parser confusion
  MD040: true

  # Inline HTML - allow specific elements, flag unescaped generic types
  MD033:
    allowed_elements:
      - br
      - kbd
      - sup
      - sub
      - details
      - summary
      - example

  # Multiple H1 - allow in agent templates (frontmatter can create implicit H1)
  MD025:
    front_matter_title: ""

  # Code block style - consistent fenced style (not a Prettier conflict)
  MD046:
    style: "fenced"

  # List marker style - consistent dashes (not a Prettier conflict)
  MD004:
    style: "dash"

  # First line heading - required by default
  MD041: true

globs:
  - "**/*.md"
  - "!node_modules/**"
  - "!.agents/**"
  - "!.serena/memories/**"
  - "!.flowbaby/**"
  - "!.claude/skills/**"

ignores:
  - "node_modules/**"
  - ".agents/**"
  - ".flowbaby/**"

  # User instruction files - these are APPENDED to existing user files during installation
  # and cannot start with H1 (MD041). They are simple, controlled content that we manually
  # verify. No inline suppression is used because it would propagate to user files
  - "src/claude/CLAUDE.md"
  - "src/vs-code-agents/copilot-instructions.md"
  - "src/copilot-cli/copilot-instructions.md"

  # Prompt templates with intentional nested code blocks and XML-like tags (scratchpad, etc.)
  # that confuse the parser. These are prompt content, not markdown errors
  - "docs/autonomous-pr-monitor.md"
  - "docs/autonomous-issue-development.md"

  # Skills treated as third-party plugins per PR #331 - excluded via glob pattern above
  # - ".claude/skills/adr-review/agent-prompts.md"  # No longer needed with glob exclusion
