"""Regression coverage for pr-comment-responder get_pr_checks envelope reads.

Issue #4465: the Phase 8.5 final-verification snippet read ``.AllPassing``,
``.FailedCount``, and ``.PendingCount`` at the top level of ``get_pr_checks.py``
output. That script emits an ADR-056 envelope, so those fields live under
``.Data``. A top-level read resolves to ``null``, the ``= "true"`` test can
never pass, and the failure branch prints ``null`` counts. The completion
criterion "CI checks pass" could not be satisfied by that snippet on any PR.

The repair normalized every selector to ``.Data.*``. It shipped without a
guard, so PR #4277 dropped it on merge and the defect returned to main. This
module is that guard.

Canonical contract, quoted verbatim from ``scripts/github_core/output.py``
(``write_skill_output``)::

    envelope = {
        "Success": True,
        "Data": data,
        "Error": None,
        "Metadata": {
            "Script": script_name,
            "Version": version,
            "Timestamp": datetime.now(UTC).isoformat(),
        },
    }

``get_pr_checks.py`` passes its result dict, which builds ``FailedCount``,
``PendingCount``, and ``AllPassing``, straight to that helper. The envelope
therefore nests them one level down, under ``Data``.

Stricter/looser/different than canonical: this guard is narrower than the
canonical envelope. It checks only the three ``get_pr_checks.py`` count fields
in the pr-comment-responder carriers. It does not audit every skill script or
every consumer of the envelope.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from scripts.github_core.output import write_skill_output

REPO_ROOT = Path(__file__).resolve().parents[1]

# Every carrier of the pr-comment-responder workflow that runs get_pr_checks.py.
# The shared template generates the VS Code and Copilot CLI copies via
# build/generate_agents.py. The .claude, .github, and src/claude copies are
# hand-maintained siblings guarded by build/scripts/validate_install_parity.py.
# The skill reference pair is generated by build_all.py.
CARRIER_PATHS: tuple[Path, ...] = (
    REPO_ROOT / "templates/agents/pr-comment-responder.shared.md",
    REPO_ROOT / ".claude/agents/pr-comment-responder.md",
    REPO_ROOT / ".github/agents/pr-comment-responder.agent.md",
    REPO_ROOT / ".github/agents/pr-comment-responder.prompt.md",
    REPO_ROOT / "src/claude/pr-comment-responder.md",
    REPO_ROOT / "src/copilot-cli/agents/pr-comment-responder.agent.md",
    REPO_ROOT / "src/vs-code-agents/pr-comment-responder.agent.md",
    REPO_ROOT / ".claude/skills/pr-comment-responder/references/gates.md",
    REPO_ROOT / "src/copilot-cli/skills/pr-comment-responder/references/gates.md",
)

ENVELOPE_COUNT_FIELDS = ("AllPassing", "FailedCount", "PendingCount")

# A selector that reads a count field without the ``Data`` hop. The negative
# lookbehind lets ``.Data.AllPassing`` through and catches bare ``.AllPassing``,
# including the ``jq -r '.AllPassing'`` and ``jq '.PendingCount'`` spellings.
TOP_LEVEL_SELECTOR_RE = re.compile(rf"(?<!Data)\.(?:{'|'.join(ENVELOPE_COUNT_FIELDS)})\b")


def test_envelope_nests_count_fields_under_data() -> None:
    """Pin the ADR-056 shape get_pr_checks.py emits for the count fields."""
    payload = {"AllPassing": False, "FailedCount": 0, "PendingCount": 30}

    emitted = write_skill_output(
        payload,
        output_format="json",
        script_name="get_pr_checks.py",
    )

    assert emitted is not None
    envelope = json.loads(emitted)
    for field in ENVELOPE_COUNT_FIELDS:
        assert field not in envelope, f"{field} must not sit at the envelope top level"
        assert envelope["Data"][field] == payload[field]


def test_detector_separates_top_level_reads_from_data_reads() -> None:
    """The detector must flag the dead spelling and clear the live one."""
    assert TOP_LEVEL_SELECTOR_RE.search("""ALL_PASSING=$(echo "$CHECKS" | jq -r '.AllPassing')""")
    assert TOP_LEVEL_SELECTOR_RE.search("""PENDING=$(echo "$CHECKS" | jq '.PendingCount')""")
    assert TOP_LEVEL_SELECTOR_RE.search("""FAILED=$(echo "$CHECKS" | jq '.FailedCount')""")
    assert not TOP_LEVEL_SELECTOR_RE.search(
        """ALL_PASSING=$(echo "$CHECKS" | jq -r '.Data.AllPassing')"""
    )
    assert not TOP_LEVEL_SELECTOR_RE.search(
        """PENDING=$(echo "$CHECKS" | jq '.Data.PendingCount')"""
    )
    # Prose that names a field without selecting it is not a read.
    assert not TOP_LEVEL_SELECTOR_RE.search("The AllPassing field reports overall CI status.")


@pytest.mark.parametrize(
    "path",
    CARRIER_PATHS,
    ids=lambda p: str(p.relative_to(REPO_ROOT)),
)
def test_carrier_reads_check_counts_through_the_data_hop(path: Path) -> None:
    """Every carrier must select get_pr_checks counts under .Data, not top level."""
    assert path.exists(), f"Expected carrier at {path.relative_to(REPO_ROOT)}"
    text = path.read_text(encoding="utf-8")

    dead = [
        f"line {number}: {line.strip()}"
        for number, line in enumerate(text.splitlines(), 1)
        if TOP_LEVEL_SELECTOR_RE.search(line)
    ]
    assert not dead, (
        f"{path.relative_to(REPO_ROOT)} reads a get_pr_checks count field at the "
        f"envelope top level, which always resolves to null (issue #4465): {dead}"
    )
