from __future__ import annotations

# AUTO-GENERATED HOOK DISPATCHER ENTRYPOINT (ADR-068, #2295).
# Runs every registered matcher shim for this event in ONE process. DO NOT EDIT
# BY HAND; regenerated by build/scripts/generate_dispatcher.py.
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _bootstrap import ensure_plugin_paths  # noqa: E402

_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _main() -> int:
    try:
        ensure_plugin_paths()
        from hook_dispatch import run_dispatch  # noqa: E402

        event_dir = Path(__file__).resolve().parent
        manifest = json.loads((event_dir / "_manifest.json").read_text(encoding="utf-8"))
        shims = manifest["shims"]
        if not isinstance(shims, list):
            raise TypeError("manifest field 'shims' must be a list")
        raw = sys.stdin.buffer.read(_MAX_STDIN_BYTES + 1)
        if len(raw) > _MAX_STDIN_BYTES:
            raise ValueError(f"stdin exceeds {_MAX_STDIN_BYTES} bytes")
        return run_dispatch(event_dir, shims, raw)
    except Exception as exc:  # noqa: BLE001 - generated entrypoint must fail closed
        print(
            f"hook-dispatch-entrypoint: {type(exc).__name__}: {exc}; denying (fail-closed)",
            file=sys.stderr,
        )
        return 2


sys.exit(_main())
