from __future__ import annotations

# AUTO-GENERATED HOOK DISPATCHER ENTRYPOINT (ADR-068, #2295).
# Runs every registered matcher shim for this event in ONE process. DO NOT EDIT
# BY HAND; regenerated by build/scripts/generate_dispatcher.py.
# Exit codes: 0 allows the tool call, any non-zero code denies it. A gate-mode
# dispatcher returns the FIRST denying shim's own exit code, which is not
# necessarily 2; 2 is what the dispatcher itself returns when a registered shim
# is missing or dispatch fails. An observer-mode dispatcher always returns 0.
import json
import sys
from pathlib import Path, PureWindowsPath
from typing import cast

# Version check: degrade gracefully on interpreters below the supported floor.
# This runs inside the already-started Python process (no extra subprocess).
# Python 3.7+ can parse this file; older versions fail at `from __future__`.
if sys.version_info < (3, 10):
    _v = ".".join(str(x) for x in sys.version_info[:3])
    print(
        "project-toolkit@ai-agents WARNING: hooks DISABLED (your session is "
        "unaffected). Python >= 3.10 "
        "required but Python " + _v + " found. "
        "Upgrade: https://www.python.org/downloads/",
        file=sys.stderr,
    )
    sys.exit(0)

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _bootstrap import PluginInfrastructureError, ensure_plugin_paths  # noqa: E402

# Defensive hook-payload ceiling (#3074, ADR-066, CWE-400). Long-session
# apply_patch calls can cross a few MiB, and no measured host maximum exists.
# Below this independent operating limit, unmatched tools allow and registered
# shims enforce their own matcher and replay policies. Above it, gate events deny
# and observe events allow without dispatching a truncated payload.
_MAX_STDIN_BYTES = 64 * 1024 * 1024
_GATE_EVENTS = ("PreToolUse", "preToolUse")
_ADVISE_EVENTS = ("PermissionRequest", "permissionRequest")
# The event this dispatcher was generated for, baked in at generation time.
# The manifest 'event' must equal it exactly before any mode selection, so
# editing the manifest cannot rebind a gate dispatcher to an observer event
# and convert a fail-closed gate into fail-open behavior (#3200, #3074).
_GENERATED_EVENT = 'PreToolUse'
# Bound manifest-controlled diagnostics. repr() escapes control characters
# (no log injection, CWE-117) and the cap prevents an oversized manifest value
# from emitting unbounded stderr (CWE-400). #3200.
_MAX_DIAG_CHARS = 512


def _diag(value):
    text = repr(value)
    if len(text) > _MAX_DIAG_CHARS:
        return text[:_MAX_DIAG_CHARS] + "...(truncated)"
    return text


def _manifest_event(manifest):
    event = manifest.get("event")
    if not isinstance(event, str):
        raise TypeError("manifest field 'event' must be a string")
    if event != _GENERATED_EVENT:
        raise ValueError(
            "manifest field 'event' must equal the generated event "
            + _diag(_GENERATED_EVENT)
            + ", got "
            + _diag(event)
        )
    return event


def _manifest_shims(manifest):
    shims = manifest["shims"]
    if not isinstance(shims, list):
        raise TypeError("manifest field 'shims' must be a list")
    if not shims:
        raise ValueError("manifest field 'shims' must not be empty")
    return shims


def _validate_shim_names(shims):
    normalized_names = set()
    for shim in shims:
        if not isinstance(shim, str):
            raise TypeError("manifest field 'shims' must contain strings")
        windows_path = PureWindowsPath(shim)
        if (
            not shim
            or shim in (".", "..")
            or "/" in shim
            or "\\" in shim
            or "\x00" in shim
            or windows_path.drive
            or Path(shim).suffix.casefold() != ".py"
        ):
            raise ValueError(
                "manifest field 'shims' must contain single basenames ending in .py, got "
                + _diag(shim)
            )
        normalized_name = shim.casefold()
        if normalized_name in normalized_names:
            raise ValueError("manifest field 'shims' must contain unique names")
        normalized_names.add(normalized_name)
    return shims


def _manifest_mode(manifest, event):
    # Default to gate so an older manifest fails closed (ADR-066).
    mode = manifest.get("mode", "gate")
    if mode not in ("gate", "observe", "advise"):
        raise ValueError(
            "manifest field 'mode' must be 'gate', 'observe', or 'advise', "
            f"got {mode!r}"
        )
    if event in _ADVISE_EVENTS:
        expected_mode = "advise"
    elif event in _GATE_EVENTS:
        expected_mode = "gate"
    else:
        expected_mode = "observe"
    if mode != expected_mode:
        raise ValueError(
            f"manifest field 'mode' for {event} must be {expected_mode!r}, got {mode!r}"
        )
    return mode


def _manifest_timeouts(manifest, shims):
    # Metadata supports host budgeting. The host owns the process timeout.
    timeouts = manifest.get("timeouts", {})
    if not isinstance(timeouts, dict):
        raise TypeError("manifest field 'timeouts' must be a dict when present")
    shim_timeouts = {}
    for shim in shims:
        if not isinstance(shim, str):
            raise TypeError("manifest field 'shims' must contain strings")
        if shim not in timeouts:
            continue
        timeout_value = timeouts[shim]
        # Accept only a positive, non-boolean JSON integer. int(True) is 1 and
        # int(3.9)/int("5") silently coerce, so a bool, float, or numeric string
        # must be rejected rather than coerced (#3200).
        if isinstance(timeout_value, bool) or not isinstance(timeout_value, int):
            raise TypeError(
                "manifest timeout for " + _diag(shim)
                + " must be a non-boolean integer, got " + _diag(timeout_value)
            )
        if timeout_value <= 0:
            raise ValueError(
                "manifest timeout for " + _diag(shim) + " must be positive"
            )
        shim_timeouts[shim] = timeout_value
    return shim_timeouts


def _load_manifest(event_dir):
    manifest = json.loads((event_dir / "_manifest.json").read_text(encoding="utf-8"))
    event = _manifest_event(manifest)
    shims = _manifest_shims(manifest)
    mode = _manifest_mode(manifest, event)
    _validate_shim_names(shims)
    return event, shims, _manifest_timeouts(manifest, shims), mode


def _read_payload(
    event: str,
    shims: list[str],
    mode: str,
) -> tuple[bytes, int | None]:
    raw = sys.stdin.buffer.read(_MAX_STDIN_BYTES + 1)
    if len(raw) <= _MAX_STDIN_BYTES:
        return raw, None
    verdict = (
        "denying (fail-closed)"
        if mode in ("gate", "advise")
        else "allowing (observe mode does not gate)"
    )
    print(
        f"hook-dispatch-entrypoint: stdin exceeds {_MAX_STDIN_BYTES} bytes "
        f"for event {_diag(event)} shims={_diag(shims)}; {verdict}",
        file=sys.stderr,
    )
    return raw, 2 if mode in ("gate", "advise") else 0


def _main() -> int:
    event_dir = Path(__file__).resolve().parent
    mode = None
    try:
        ensure_plugin_paths()
    except (PluginInfrastructureError, ImportError, OSError) as exc:
        # Infrastructure failure: the dispatch machinery could not load.
        # Allow the tool call (exit 0) to keep the plugin usable. A plugin
        # that denies every call forces uninstall, removing all protection.
        # Fail-open on infrastructure keeps the plugin installed so the next
        # release still protects the user (#4672).
        print(
            "project-toolkit@ai-agents WARNING: hooks DISABLED "
            "(your session is unaffected). "
            f"{type(exc).__name__}: {_diag(str(exc))}. "
            "Reinstall the plugin or install Python >= 3.10: "
            "https://www.python.org/downloads/",
            file=sys.stderr,
        )
        return 0
    try:
        from hook_dispatch import observe_output_policy, run_dispatch  # noqa: E402

        event, shims, shim_timeouts, mode = _load_manifest(event_dir)
        raw, oversize_exit = _read_payload(event, shims, mode)
        if oversize_exit is not None:
            return oversize_exit
        if mode == "advise":
            from hook_dispatch import run_permission_dispatch  # noqa: E402

            return cast(
                int,
                run_permission_dispatch(event_dir, shims, raw, shim_timeouts),
            )
        return cast(
            int,
            run_dispatch(
                event_dir,
                shims,
                raw,
                shim_timeouts,
                short_circuit=mode == "gate",
                output_policy=(
                    observe_output_policy(event) if mode == "observe" else "passthrough"
                ),
            ),
        )
    except ImportError as exc:
        # hook_dispatch module missing: infrastructure failure, not policy.
        print(
            "project-toolkit@ai-agents WARNING: hooks DISABLED "
            "(your session is unaffected). "
            f"{type(exc).__name__}: {_diag(str(exc))}. "
            "Reinstall the plugin or install Python >= 3.10: "
            "https://www.python.org/downloads/",
            file=sys.stderr,
        )
        return 0
    except Exception as exc:  # noqa: BLE001 - generated entrypoint must stay loud
        # Policy or dispatch error after machinery loaded: a shim ran and
        # raised, or manifest validation failed post-load. Fail closed for
        # gate/advise events (these are policy decisions), allow for observers.
        fail_closed = mode in ("gate", "advise") or event_dir.name.lower() in (
            "pretooluse",
            "permissionrequest",
        )
        consequence = (
            "denying (fail-closed)"
            if fail_closed
            else "observer failed; host continues"
        )
        print(
            f"hook-dispatch-entrypoint: {type(exc).__name__}: "
            f"{_diag(str(exc))}; {consequence}",
            file=sys.stderr,
        )
        return 2


sys.exit(_main())
