from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: '^(mcp__serena__(write|delete)_memory|serena-(write|delete)_memory)$'
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
# Exit codes: 0 when the matcher does not fire (allow) or the wrapped script
# succeeds, or the wrapped script's own code when it fires. Internal matcher
# errors use the wrapped hook's declared fail-open or fail-closed policy.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(mcp__serena__(write|delete)_memory|serena-(write|delete)_memory)$'
_INPUT_ERROR_CODE = 2

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match each top-level `|` branch as a separate glob alternative."""
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def _shim_load_json(raw_value):
    return _json.loads(raw_value, object_pairs_hook=_shim_unique_object)


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _shim_load_json(raw_value)
        except _json.JSONDecodeError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_json_equal(left, right):
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _shim_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _shim_json_equal(a, b) for a, b in zip(left, right))
    return left == right


def _shim_alias_value(payload, snake, camel, parser=None):
    fields = [field for field in (snake, camel) if field in payload]
    if not fields:
        return False, None, snake, False
    values = [payload[field] for field in fields]
    if parser is not None:
        values = [parser(value, field) for value, field in zip(values, fields)]
    if len(values) == 2 and not _shim_json_equal(values[0], values[1]):
        raise ValueError(
            "conflicting top-level {}/{} values".format(snake, camel)
        )
    changed = fields != [snake] or values[0] != payload[snake]
    return True, values[0], "/".join(fields), changed


def _shim_top_level_candidate(payload):
    has_name, name, _, name_changed = _shim_alias_value(
        payload, "tool_name", "toolName", _shim_validate_tool_name
    )
    if not has_name:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    input_payload = payload
    if payload.get("tool_input") is None and "toolArgs" in payload:
        input_payload = {key: value for key, value in payload.items() if key != "tool_input"}
    has_input, tool_input, input_field, input_changed = _shim_alias_value(
        input_payload, "tool_input", "toolArgs", _shim_parse_json_string
    )
    has_call_id, call_id, _, call_id_changed = _shim_alias_value(
        payload, "tool_call_id", "toolCallId"
    )
    if not (name_changed or input_changed or call_id_changed):
        return payload, input_field
    candidate = dict(payload)
    for field in ("toolName", "toolArgs", "toolCallId"):
        candidate.pop(field, None)
    candidate["tool_name"] = name
    if has_input:
        candidate["tool_input"] = tool_input
    if has_call_id:
        candidate["tool_call_id"] = call_id
    return candidate, input_field


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        # A payload may carry top-level action fields OR a `toolCalls` batch,
        # never both: the host precedence contract between the two shapes is
        # unverified, so a top-level Read alongside a Bash in `toolCalls` is
        # ambiguous. Reject any mix (empty or non-empty batch) before a guard
        # ever sees a candidate (#3200).
        conflicting = [
            field
            for field in (
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            )
            if field in payload
        ]
        if conflicting:
            raise ValueError(
                "toolCalls conflicts with top-level action fields: "
                + ", ".join(conflicting)
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    if selected is payload:
        return raw
    return _json.dumps(selected, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)  # always fail-closed for oversized payloads
    try:
        payload = _shim_load_json(_raw or b"{}")
    except RecursionError:
        # Deeply nested JSON exhausts the parser recursion budget and raises
        # RecursionError, which is NOT a ValueError subclass, so it would
        # otherwise escape the malformed-JSON handler below, print a traceback,
        # and exit 1. A standalone shim (run directly, not under the dispatcher)
        # must fail closed the same way the dispatcher does: bounded diagnostic
        # (no traceback, no payload bytes) and exit 2 (issue #3169).
        print(
            "matcher-shim [{}]: stdin JSON nesting too deep; refusing".format(
                _MATCHER
            ),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    except ValueError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block Serena memory mutations aimed at a checkout other than the caller's.

    Issue #5061: a subagent running inside a git worktree called
    ``mcp__serena__write_memory``. The Serena MCP server resolves its memory
    directory from the project it was started with (``.mcp.json`` starts it with
    ``--project ${workspaceFolder:-.}``), not from the caller's cwd, so the file
    landed in the main checkout's ``.serena/memories/`` tree. The memory was
    invisible to the subagent's own branch, and the subagent silently modified a
    working tree it was supposed to be isolated from.

    Customer value: no silent cross-worktree Serena memory write in a consumer's
    own multi-checkout workflow, on either harness.

    Why this guard is not covered by the guard proposed for issue #4917
    (PR #5036, ``.claude/hooks/PreToolUse/invoke_serena_worktree_scope_guard.py``
    on branch ``fix/4917-serena-worktree-scope``, commit 96521be). That guard
    declares, verbatim:

        _WRITE_TOOLS: frozenset[str] = frozenset(
            {
                "serena-replace_content",
                "serena-replace_symbol_body",
                "serena-insert_before_symbol",
                "serena-insert_after_symbol",
                "serena-replace_in_files",
                "serena-safe_delete_symbol",
                "serena-rename_symbol",
            }
        )

    and registers on ``"matcher": "^serena-"`` in
    ``.claude/hooks/dispatch_groups.json``. Two gaps follow. The tool set holds no
    memory tool, so ``write_memory`` and ``delete_memory`` pass it unexamined. And
    ``^serena-`` is the Copilot CLI tool naming; Claude Code names the same server's
    tools ``mcp__serena__*``, which this repository already relies on at
    ``.claude/settings.json`` (``"matcher": "mcp__serena__write_memory"`` on the
    observation-sync PostToolUse entry). This guard therefore matches both namings.

    Different than that guard: it gates memory tools only, and it names the
    in-worktree write path in its block message, because a memory write is
    addressed by name rather than by path and so gives the caller no path-level
    signal that the target sits in another checkout.

    Hook Type: PreToolUse
    Matcher: mcp__serena__(write|delete)_memory|serena-(write|delete)_memory

    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (unrelated tool, scope matches, or caller is not in a git repo)
        2 = Block (memory mutation whose target checkout is not the caller's)

    Fail-closed for mutations whose session root cannot be resolved, whose caller
    worktree cannot be resolved (git failed to launch, timed out, or returned
    unusable output), or whose stdin payload was too large to parse safely: each
    is a state in which a stray write cannot be ruled out. Fail-open only when
    git ran and confirmed the caller is not inside any git worktree at all,
    because no worktree isolation claim exists to violate there.
    """


    import json
    import os
    import subprocess
    import sys
    from pathlib import Path

    _MAX_STDIN_BYTES = 128 * 1024
    _GIT_TIMEOUT_SECONDS = 5

    # Serena tools that mutate the activated project's .serena/memories/ tree.
    # Both harness namings: Claude Code exposes MCP tools as mcp__<server>__<tool>,
    # Copilot CLI as <server>-<tool>.
    _MEMORY_WRITE_TOOLS: frozenset[str] = frozenset(
        {
            "mcp__serena__write_memory",
            "mcp__serena__delete_memory",
            "serena-write_memory",
            "serena-delete_memory",
        }
    )

    _OVERRIDE_ENV = "SERENA_PROJECT_ROOT"
    _SESSION_ENV = "CLAUDE_PROJECT_DIR"


    class _GitUnresolvableError(Exception):
        """Raised when git could not be run at all (not when it ran and said no).

        A caller genuinely outside any git repository gets a clean nonzero
        ``git`` exit; that is a real answer, not an unresolvable state. A
        launch failure, a timeout, or an unreadable result tells us nothing
        about whether the caller is inside a worktree, so it cannot be treated
        the same as a confirmed "not in a repo" answer.
        """


    def _git_toplevel(start: Path) -> Path | None:
        """Return the git worktree root containing *start*, or None.

        Raises :class:`_GitUnresolvableError` when ``git`` could not be launched, hit
        its timeout, or returned output we could not resolve, so a caller that
        needs to distinguish "confirmed outside a repo" from "we do not know"
        can fail closed on the latter instead of silently allowing it.
        """
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--show-toplevel"],
                cwd=str(start),
                capture_output=True,
                encoding="utf-8",
                errors="replace",
                check=False,
                timeout=_GIT_TIMEOUT_SECONDS,
            )
        except (OSError, subprocess.SubprocessError) as error:
            raise _GitUnresolvableError(str(error)) from error
        if result.returncode != 0:
            return None
        toplevel = result.stdout.strip()
        if not toplevel:
            raise _GitUnresolvableError("git rev-parse --show-toplevel returned no output")
        try:
            return Path(toplevel).resolve()
        except OSError as error:
            raise _GitUnresolvableError(str(error)) from error


    def _resolved_dir(raw: str) -> Path | None:
        """Resolve *raw* to an existing directory, or None."""
        candidate = raw.strip()
        if not candidate or "\x00" in candidate:
            return None
        try:
            path = Path(candidate).expanduser().resolve()
        except (OSError, RuntimeError):
            return None
        return path if path.is_dir() else None


    def _serena_memory_root() -> Path | None:
        """Return the checkout whose .serena/memories/ tree Serena actually writes.

        The Serena server binds its project once, at start. ``SERENA_PROJECT_ROOT``
        is the operator's explicit statement of that binding after a re-activation;
        otherwise the session's own project dir is the best available proxy, since
        ``.mcp.json`` starts the server with the session workspace folder.
        """
        override = _resolved_dir(os.environ.get(_OVERRIDE_ENV, ""))
        if override is not None:
            try:
                return _git_toplevel(override) or override
            except _GitUnresolvableError:
                return override

        session_dir = _resolved_dir(os.environ.get(_SESSION_ENV, ""))
        if session_dir is not None:
            try:
                return _git_toplevel(session_dir)
            except _GitUnresolvableError:
                # An unresolvable git state here still yields no answer, and the
                # caller (main) already fails closed on a None memory root.
                return None

        return None


    def _payload_cwd(payload: dict[str, object]) -> Path:
        """Return the caller's cwd from *payload*, falling back to this process."""
        raw = payload.get("cwd")
        if not isinstance(raw, str) or not raw.strip():
            return Path.cwd().resolve()
        candidate = Path(raw.strip())
        if not candidate.is_absolute():
            candidate = Path.cwd() / candidate
        try:
            return candidate.resolve()
        except (OSError, RuntimeError):
            return Path.cwd().resolve()


    class _StdinTooLargeError(Exception):
        """Raised when the hook payload exceeds ``_MAX_STDIN_BYTES``.

        The read itself is already bounded (``read(_MAX_STDIN_BYTES + 1)``), so
        there is no unbounded-read risk in accepting a larger payload; the limit
        exists to bound JSON-parse cost. A payload this size cannot be reliably
        parsed to confirm it is unrelated to a memory write, and a large memory
        body is a realistic, more consequential case, not an edge case to wave
        through. Callers fail closed on this instead of the generic
        can't-parse-so-allow fallback.
        """


    def _read_payload() -> tuple[str, Path]:
        """Return (tool_name, caller_cwd) from the hook stdin payload."""
        fallback = ("", Path.cwd().resolve())
        if sys.stdin.isatty():
            return fallback
        raw = sys.stdin.read(_MAX_STDIN_BYTES + 1)
        if len(raw) > _MAX_STDIN_BYTES:
            raise _StdinTooLargeError(f"payload exceeds {_MAX_STDIN_BYTES} bytes")
        if not raw.strip():
            return fallback
        try:
            payload = json.loads(raw)
        except (json.JSONDecodeError, ValueError):
            return fallback
        if not isinstance(payload, dict):
            return fallback

        name = payload.get("tool_name") or payload.get("toolName") or ""
        if not isinstance(name, str):
            return fallback
        return name, _payload_cwd(payload)


    def _block_message(worktree: Path, memory_root: Path) -> str:
        """Return the stderr guidance shown when a memory mutation is blocked."""
        return (
            "BLOCKED: Serena memory mutation would land outside your worktree "
            "(issue #5061).\n"
            f"  Your worktree:        {worktree}\n"
            f"  Serena memory target: {memory_root}\n"
            "The Serena server binds its project at start, so write_memory and "
            "delete_memory always resolve against the target above, not your cwd.\n"
            "Do one of:\n"
            f"  1. Write the file directly with the Write tool: "
            f"{worktree / '.serena' / 'memories'}/<name>.md\n"
            f"  2. Re-activate Serena for this worktree, then set "
            f"{_OVERRIDE_ENV}={worktree}\n"
        )


    def main() -> int:
        """Entry point. Returns 0 (allow) or 2 (block)."""
        try:
            tool_name, caller_cwd = _read_payload()
        except _StdinTooLargeError as error:
            print(
                f"BLOCKED: cannot verify Serena memory scope (issue #5061): {error}. "
                "A payload this size cannot be confirmed unrelated to a memory "
                "write. Write the memory file directly with the Write tool, or "
                "retry with a smaller call.",
                file=sys.stderr,
            )
            return 2
        if tool_name not in _MEMORY_WRITE_TOOLS:
            return 0

        try:
            worktree = _git_toplevel(caller_cwd)
        except _GitUnresolvableError as error:
            print(
                "BLOCKED: could not determine your git worktree (issue #5061): "
                f"{error}. Set {_OVERRIDE_ENV} to your worktree, or write the "
                "memory file directly with the Write tool.",
                file=sys.stderr,
            )
            return 2
        if worktree is None:
            # git ran and confirmed the caller is not inside a git worktree at
            # all, so there is no isolation claim to violate. Fail open.
            return 0

        memory_root = _serena_memory_root()
        if memory_root is None:
            print(
                "BLOCKED: cannot determine which checkout Serena writes memories "
                f"to (issue #5061). Set {_OVERRIDE_ENV} to that checkout, or write "
                "the memory file directly with the Write tool.",
                file=sys.stderr,
            )
            return 2

        if worktree == memory_root:
            return 0

        print(_block_message(worktree, memory_root), file=sys.stderr)
        return 2


    if __name__ == "__main__":
        raise SystemExit(main())
    return 0

_shim_dispatch()
