from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _json.loads(raw_value)
        except ValueError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_tool_input_from_tool_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolArgs")


def _shim_top_level_input_field(payload):
    if payload.get("tool_input") is not None:
        return "tool_input"
    if "toolArgs" in payload:
        return "toolArgs"
    return "tool_input"


def _shim_candidate_payloads(payload):
    tool_calls = payload.get("toolCalls")
    if isinstance(tool_calls, list):
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        top_level_name = payload.get("tool_name")
        if top_level_name is None:
            top_level_name = payload.get("toolName")
        if not tool_calls and isinstance(top_level_name, str):
            raise ValueError(
                "empty toolCalls conflicts with top-level tool_name/toolName"
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            name = call.get("name")
            if not isinstance(name, str) or not name.strip():
                raise ValueError(
                    "toolCalls[{}].name must be a non-empty string".format(index)
                )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            candidate.pop("toolCalls", None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield payload, _shim_top_level_input_field(payload)


def _shim_match_candidate(payload, kind, params):
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        tool_args = _shim_tool_input_from_tool_args(tool_args)
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    replay = dict(selected)
    changed = selected is not payload
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        replay["tool_input"] = _shim_tool_input_from_tool_args(replay.get("toolArgs"))
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push when canonical agents/rules move without their install siblings.

    Thin adapter over :mod:`push_guard_base`. Reuses the parity logic that lives
    in ``build/scripts/validate_install_parity.py`` so the same rules apply in CI
    (``scripts/validation/pre_pr.py``) and at push time (this guard). Activates on
    any path that could anchor a parity group; the validator decides whether the
    diff is actually drifting or whether the touched files form a clean group.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (no parity drift detected, or the diff did not touch any
            tracked file)
        2 = Block (parity drift detected; the message lists missing siblings)

    Fail-open path:
        The validator depends on the build script being importable. If the
        import or the call fails for an environmental reason (the build tree
        is absent on a consumer-repo checkout, the module raises an unexpected
        error), the guard fail-opens with an EVENT line so telemetry can
        flag the degraded state. Real parity violations always block; only
        infrastructure failures fail-open.
    """


    import sys
    from pathlib import Path

    from _bootstrap import ensure_plugin_paths

    ensure_plugin_paths()

    from hook_utilities import get_project_directory  # noqa: E402
    from push_guard_base import emit_fail_open, run_guard  # noqa: E402

    GUARD_NAME = "install-parity"

    # Globs that wake this guard. Multi-segment paths are checked by
    # push_guard_base via prefix + suffix matching.
    _GLOBS = (
        "templates/agents/*.shared.md",
        ".claude/agents/*.md",
        ".github/agents/*.agent.md",
        "src/claude/*.md",
        "src/copilot-cli/agents/*.agent.md",
        "src/vs-code-agents/*.agent.md",
        ".claude/rules/*.md",
        ".github/instructions/*.instructions.md",
        "src/copilot-cli/instructions/*.instructions.md",
    )


    def _import_validator():
        """Import the validator from the repo's build tree.

        Returns the module on success or ``None`` on failure. Importing is
        isolated so the guard can fail-open cleanly when the script is run in
        a consumer repo that does not vendor ``build/scripts/``.

        Every failure path emits an EVENT line via emit_fail_open so the
        degraded state surfaces to telemetry (per the module docstring). An
        earlier revision returned None silently for missing project dirs and
        missing build trees, making the degraded state invisible.
        """
        project_dir = get_project_directory()
        if not project_dir:
            emit_fail_open(
                GUARD_NAME,
                "no_project_dir",
                "get_project_directory returned empty; cannot locate build tree",
            )
            return None
        candidate = Path(project_dir) / "build" / "scripts"
        if not candidate.is_dir():
            emit_fail_open(
                GUARD_NAME,
                "build_tree_absent",
                f"build/scripts not found under {project_dir}; consumer-repo checkout",
            )
            return None
        if str(candidate) not in sys.path:
            sys.path.insert(0, str(candidate))
        try:
            import validate_install_parity as vip  # noqa: PLC0415
        except ImportError as exc:
            emit_fail_open(
                GUARD_NAME,
                "import_failed",
                f"validate_install_parity: {type(exc).__name__}: {exc}",
            )
            return None
        return vip


    def _validate(_matching: list[str], all_changed: list[str]) -> list[str]:
        vip = _import_validator()
        if vip is None:
            return []

        project_dir = get_project_directory()
        if not project_dir:
            emit_fail_open(GUARD_NAME, "no_project_dir", "get_project_directory returned empty")
            return []

        try:
            violations = vip.find_violations(all_changed, repo_root=Path(project_dir))
        except Exception as exc:  # pragma: no cover - defensive fail-open
            emit_fail_open(
                GUARD_NAME, "validator_raised", f"{type(exc).__name__}: {exc}"
            )
            return []

        if not violations:
            return []

        out: list[str] = ["Install-copy parity drift:"]
        for v in violations:
            out.append("")
            out.append(f"  [{v.kind}] {v.name}")
            out.append("    touched:")
            for p in v.touched:
                out.append(f"      {p}")
            out.append("    missing (required siblings):")
            for p in v.missing:
                out.append(f"      {p}")
        out.append("")
        out.append(
            "Fix: stage the missing files in this push. SHARED_AGENT siblings "
            "are templates/agents/X.shared.md, .claude/agents/X.md, "
            ".github/agents/X.agent.md, src/claude/X.md, "
            "src/copilot-cli/agents/X.agent.md, and src/vs-code-agents/X.agent.md. "
            "RULE siblings are .claude/rules/X.md, .github/instructions/X.instructions.md, "
            "and src/copilot-cli/instructions/X.instructions.md."
        )
        return out


    def main() -> int:
        # include_deletions=True so a deletion-only parity break (deleting a
        # template or one install sibling without staging the rest) still
        # reaches the validator. This guard only reasons about file paths, so
        # ACMRD is safe; the validator treats a deleted template path as a
        # touched group member (see _is_shared_agent_group).
        return run_guard(_validate, list(_GLOBS), GUARD_NAME, include_deletions=True)
    return main()

_shim_dispatch()
