from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(Edit|Write)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Edit|Write)$'

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match each top-level `|` branch as a separate glob alternative."""
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def _shim_load_json(raw_value):
    return _json.loads(raw_value, object_pairs_hook=_shim_unique_object)


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _shim_load_json(raw_value)
        except _json.JSONDecodeError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_json_equal(left, right):
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _shim_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _shim_json_equal(a, b) for a, b in zip(left, right))
    return left == right


def _shim_alias_value(payload, snake, camel, parser=None):
    fields = [field for field in (snake, camel) if field in payload]
    if not fields:
        return False, None, snake, False
    values = [payload[field] for field in fields]
    if parser is not None:
        values = [parser(value, field) for value, field in zip(values, fields)]
    if len(values) == 2 and not _shim_json_equal(values[0], values[1]):
        raise ValueError(
            "conflicting top-level {}/{} values".format(snake, camel)
        )
    changed = fields != [snake] or values[0] != payload[snake]
    return True, values[0], "/".join(fields), changed


def _shim_top_level_candidate(payload):
    has_name, name, _, name_changed = _shim_alias_value(
        payload, "tool_name", "toolName", _shim_validate_tool_name
    )
    if not has_name:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    input_payload = payload
    if payload.get("tool_input") is None and "toolArgs" in payload:
        input_payload = {key: value for key, value in payload.items() if key != "tool_input"}
    has_input, tool_input, input_field, input_changed = _shim_alias_value(
        input_payload, "tool_input", "toolArgs", _shim_parse_json_string
    )
    has_call_id, call_id, _, call_id_changed = _shim_alias_value(
        payload, "tool_call_id", "toolCallId"
    )
    if not (name_changed or input_changed or call_id_changed):
        return payload, input_field
    candidate = dict(payload)
    for field in ("toolName", "toolArgs", "toolCallId"):
        candidate.pop(field, None)
    candidate["tool_name"] = name
    if has_input:
        candidate["tool_input"] = tool_input
    if has_call_id:
        candidate["tool_call_id"] = call_id
    return candidate, input_field


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        if not tool_calls and (
            "tool_name" in payload or "toolName" in payload
        ):
            raise ValueError(
                "empty toolCalls conflicts with top-level tool_name/toolName"
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    if selected is payload:
        return raw
    return _json.dumps(selected, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _shim_load_json(_raw or b"{}")
    except RecursionError:
        # Deeply nested JSON exhausts the parser recursion budget and raises
        # RecursionError, which is NOT a ValueError subclass, so it would
        # otherwise escape the malformed-JSON handler below, print a traceback,
        # and exit 1. A standalone shim (run directly, not under the dispatcher)
        # must fail closed the same way the dispatcher does: bounded diagnostic
        # (no traceback, no payload bytes) and exit 2 (issue #3169).
        print(
            "matcher-shim [{}]: stdin JSON nesting too deep; refusing".format(
                _MATCHER
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    except ValueError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block Edit/Write on ADR files unless architect review evidence exists.

    Claude Code PreToolUse hook that enforces architect involvement before
    modifying ADR files. This is a routing-level gate per ADR-033.

    Blocks Edit/Write operations on:
    - .agents/architecture/ADR-*.md
    - docs/architecture/ADR-*.md
    - **/ADR-*.md (any location)

    Evidence sources (any satisfies the gate):
    1. Debate log artifact in .agents/analysis/ or .agents/critique/
    2. Session log contains architect agent routing evidence
    3. adr-review skill was invoked

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (continue with tool use)
        2 = Block (deny tool use with message)
    """


    import json
    import os
    import posixpath
    import re
    import sys
    from datetime import UTC, datetime
    from pathlib import Path, PurePosixPath

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    _lib_dir: str | None = None
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(
            f"Plugin lib directory not found: {_lib_dir} "
            f"(CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import (  # noqa: E402
        get_project_directory,
        get_today_session_log,
    )

    _ADR_PATTERN = re.compile(r"(?:^|/)ADR-\d+[^/]*\.md$", re.IGNORECASE)

    # Directories that hold the gate's OWN evidence artifacts (debate logs,
    # critiques). Writing a debate log here is the act the gate asks for, so the
    # gate must never block writes under these directories, even when the filename
    # starts with an "ADR-<n>" substring (issue #2579: the natural evidence name
    # ADR-0002-architect-review-debate.md otherwise self-blocks, chicken-and-egg).
    _EVIDENCE_DIRS = (
        (".agents", "analysis"),
        (".agents", "critique"),
    )

    _ARCHITECT_EVIDENCE_PATTERNS = [
        re.compile(r"/adr-review"),
        re.compile(r"adr-review skill"),
        re.compile(r"ADR Review Protocol"),
        re.compile(r"subagent_type\s*=\s*['\"]?architect\b['\"]?"),
        re.compile(r"Task\s*\([^)]*subagent_type\s*=\s*['\"]?architect\b"),
        re.compile(r"\barchitect\s+agent\b", re.IGNORECASE),
        re.compile(r"multi-agent consensus.{0,200}\bADR\b", re.DOTALL),
    ]

    _BLOCKED_MESSAGE_TEMPLATE = """\

    ## BLOCKED: ADR Edit Without Architect Review

    **YOU MUST invoke the architect agent before modifying ADR files.**

    ### File Targeted

    {file_path}

    ### Required Action

    Invoke the architect agent to review ADR changes:

    ```
    Task(subagent_type='architect', prompt='Review ADR changes for {adr_name}')
    ```

    After architect review, the adr-review skill will automatically be invoked
    for multi-agent debate (6 agents: architect, critic, independent-thinker,
    security, analyst, high-level-advisor).

    ### Alternative

    Invoke the adr-review skill directly:

    ```
    /adr-review {file_path}
    ```

    **Skill**: `.claude/skills/adr-review/SKILL.md`
    """


    def write_audit_log(message: str) -> None:
        """Write to the hook audit log for infrastructure error visibility."""
        try:
            hook_dir = Path(__file__).resolve().parents[1]
            audit_log_path = hook_dir / "audit.log"
            timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S")
            entry = f"[{timestamp}] [ADRArchitectGate] {message}\n"
            with open(audit_log_path, "a", encoding="utf-8") as f:
                f.write(entry)
        except OSError:
            print(
                f"[ADRArchitectGate] CRITICAL: Audit log write failed. Original error: {message}",
                file=sys.stderr,
            )


    def _normalize_hook_path(file_path: str) -> str:
        """Normalize a hook path for lexical gate matching.

        Hook inputs are project-relative strings, not necessarily existing files.
        ``posixpath.normpath`` collapses ``..`` without requiring the target to
        exist; replacing backslashes first keeps Windows paths on the same path
        separator contract as POSIX paths.
        """
        normalized = file_path.replace("\\", "/")
        return posixpath.normpath(normalized)


    def _is_evidence_artifact(normalized_path: str) -> bool:
        """True if file_path lives under a gate evidence directory.

        Matches ``.agents/analysis/`` and ``.agents/critique/`` after lexical
        normalization has collapsed traversal segments.
        """
        parts = PurePosixPath(normalized_path).parts
        for needle in _EVIDENCE_DIRS:
            span = len(needle)
            for start in range(len(parts) - span + 1):
                if parts[start : start + span] == needle:
                    return True
        return False


    def is_adr_file(file_path: str) -> bool:
        """Check if file path matches ADR naming pattern.

        Files under the gate's own evidence directories (``.agents/analysis/``,
        ``.agents/critique/``) are excluded: writing the architect-review debate
        log is the act the gate asks for, so blocking it is a chicken-and-egg
        deadlock (issue #2579). The pattern is basename-anchored so only files
        whose name starts with ``ADR-<digits>`` match, not any path containing the
        substring.
        """
        normalized_path = _normalize_hook_path(file_path)
        if _is_evidence_artifact(normalized_path):
            return False
        return _ADR_PATTERN.search(normalized_path) is not None


    def check_architect_evidence(project_dir: str) -> dict[str, object]:
        """Check for architect involvement evidence.

        Returns dict with 'complete' (bool) and 'reason' or 'evidence' key.
        """
        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")

        # Check 1: Debate log artifacts in .agents/analysis/ or .agents/critique/
        for artifact_dir in [".agents/analysis", ".agents/critique"]:
            analysis_dir = Path(project_dir) / artifact_dir
            if analysis_dir.is_dir():
                debate_logs = list(analysis_dir.rglob("*debate*.md"))
                for log in debate_logs:
                    if log.stat().st_mtime > (datetime.now(tz=UTC).timestamp() - 86400):
                        return {
                            "complete": True,
                            "evidence": f"Debate log artifact found: {log.name}",
                        }

        # Check 2: Session log evidence
        sessions_dir = os.path.join(project_dir, ".agents", "sessions")
        session_log = get_today_session_log(sessions_dir, date=today)

        if session_log is not None:
            try:
                content = session_log.read_text(encoding="utf-8")
                for pattern in _ARCHITECT_EVIDENCE_PATTERNS:
                    if pattern.search(content):
                        return {
                            "complete": True,
                            "evidence": f"Session log contains architect evidence: {pattern.pattern}",
                        }
            except OSError as exc:
                write_audit_log(f"Session log read failed: {exc}")

        return {
            "complete": False,
            "reason": "No architect involvement evidence found in session log or analysis artifacts",
        }


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_name = hook_input.get("tool_name", "")
            if tool_name not in ("Edit", "Write"):
                return 0

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0

            # file_path (Claude) or path (Copilot CLI create/edit); see #2610.
            file_path = tool_input.get("file_path") or tool_input.get("path") or ""
            if not file_path:
                return 0

            if not is_adr_file(file_path):
                return 0

            # ADR file edit/write detected, check for architect evidence
            project_dir = get_project_directory()
            evidence = check_architect_evidence(project_dir)

            if evidence["complete"]:
                return 0

            # Block the operation
            adr_name = Path(file_path).name
            print(
                _BLOCKED_MESSAGE_TEMPLATE.format(
                    file_path=file_path,
                    adr_name=adr_name,
                )
            )
            print(
                "Blocked: ADR edit without architect review",
                file=sys.stderr,
            )
            return 2

        except json.JSONDecodeError as exc:
            error_msg = f"JSON parse error: {exc}"
            print(error_msg, file=sys.stderr)
            write_audit_log(error_msg)
            return 0  # Fail-open on infrastructure errors

        except Exception as exc:
            # Fail-open on infrastructure errors
            error_msg = f"ADR architect gate error: {type(exc).__name__} - {exc}"
            print(error_msg, file=sys.stderr)
            write_audit_log(error_msg)
            return 0
    return main()

_shim_dispatch()
