from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match each top-level `|` branch as a separate glob alternative."""
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def _shim_load_json(raw_value):
    return _json.loads(raw_value, object_pairs_hook=_shim_unique_object)


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _shim_load_json(raw_value)
        except _json.JSONDecodeError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_json_equal(left, right):
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _shim_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _shim_json_equal(a, b) for a, b in zip(left, right))
    return left == right


def _shim_alias_value(payload, snake, camel, parser=None):
    fields = [field for field in (snake, camel) if field in payload]
    if not fields:
        return False, None, snake, False
    values = [payload[field] for field in fields]
    if parser is not None:
        values = [parser(value, field) for value, field in zip(values, fields)]
    if len(values) == 2 and not _shim_json_equal(values[0], values[1]):
        raise ValueError(
            "conflicting top-level {}/{} values".format(snake, camel)
        )
    changed = fields != [snake] or values[0] != payload[snake]
    return True, values[0], "/".join(fields), changed


def _shim_top_level_candidate(payload):
    has_name, name, _, name_changed = _shim_alias_value(
        payload, "tool_name", "toolName", _shim_validate_tool_name
    )
    if not has_name:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    input_payload = payload
    if payload.get("tool_input") is None and "toolArgs" in payload:
        input_payload = {key: value for key, value in payload.items() if key != "tool_input"}
    has_input, tool_input, input_field, input_changed = _shim_alias_value(
        input_payload, "tool_input", "toolArgs", _shim_parse_json_string
    )
    has_call_id, call_id, _, call_id_changed = _shim_alias_value(
        payload, "tool_call_id", "toolCallId"
    )
    if not (name_changed or input_changed or call_id_changed):
        return payload, input_field
    candidate = dict(payload)
    for field in ("toolName", "toolArgs", "toolCallId"):
        candidate.pop(field, None)
    candidate["tool_name"] = name
    if has_input:
        candidate["tool_input"] = tool_input
    if has_call_id:
        candidate["tool_call_id"] = call_id
    return candidate, input_field


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        if not tool_calls and (
            "tool_name" in payload or "toolName" in payload
        ):
            raise ValueError(
                "empty toolCalls conflicts with top-level tool_name/toolName"
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    if selected is payload:
        return raw
    return _json.dumps(selected, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _shim_load_json(_raw or b"{}")
    except RecursionError:
        # Deeply nested JSON exhausts the parser recursion budget and raises
        # RecursionError, which is NOT a ValueError subclass, so it would
        # otherwise escape the malformed-JSON handler below, print a traceback,
        # and exit 1. A standalone shim (run directly, not under the dispatcher)
        # must fail closed the same way the dispatcher does: bounded diagnostic
        # (no traceback, no payload bytes) and exit 2 (issue #3169).
        print(
            "matcher-shim [{}]: stdin JSON nesting too deep; refusing".format(
                _MATCHER
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    except ValueError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push without retrospective evidence per ADR-033.

    Claude Code PreToolUse hook that enforces retrospective before push.
    Prevents pushing without capturing session learnings.

    Gate triggers on:
    - git push commands

    Evidence requirements (any one satisfies):
    1. Retrospective section in session log (## Retrospective)
    2. Retrospective file in .agents/retrospective/ for today
    3. Reference to retrospective file in session log

    Bypass conditions:
    - Documentation-only changes (no code files)
    - Trivial sessions (<10 minutes, single file)
    - SKIP_RETROSPECTIVE_GATE environment variable set

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not push, or retrospective evidence exists)
        2 = Block (push without retrospective evidence)
    """


    import json
    import os
    import re
    import subprocess
    import sys
    import time
    from datetime import UTC, datetime
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    _lib_dir: str | None = None
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(
            f"Plugin lib directory not found: {_lib_dir} "
            f"(CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        # Non-blocking hook: exit 0 on bootstrap failure (intentional, not a typo)
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)  # Fail open when lib not found

    try:
        from hook_utilities import get_project_directory, get_today_session_log
    except ImportError:
        # Fallback implementations when hook_utilities is not available
        def get_project_directory() -> str:
            """Resolve the project root directory."""
            env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
            if env_dir:
                return str(Path(env_dir).resolve())
            return str(Path.cwd())

        def get_today_session_log(sessions_dir: str, date: str | None = None) -> Path | None:
            """Find the most recent session log for the given date."""
            if date is None:
                date = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            sessions_path = Path(sessions_dir)
            if not sessions_path.is_dir():
                return None
            try:
                logs = sorted(
                    sessions_path.glob(f"{date}-session-*.json"),
                    key=lambda p: p.stat().st_mtime,
                    reverse=True,
                )
            except OSError:
                return None
            return logs[0] if logs else None


    _GIT_PUSH_PATTERN = re.compile(r"(?:^|\s)git\s+push\b")
    _RETROSPECTIVE_SECTION_PATTERN = re.compile(
        r"(?i)(##\s*retrospective|retrospective\s*section|learnings?\s*captured)"
    )
    _RETROSPECTIVE_FILE_REF_PATTERN = re.compile(
        r"(?i)(\.agents/retrospective/|retrospective[-_]?file|retro[-_]?\d{4})"
    )

    # Documentation-only file patterns
    _DOC_PATTERNS = [
        re.compile(r"\.md$"),
        re.compile(r"\.txt$"),
        re.compile(r"(^|/)README$"),
        re.compile(r"(^|/)LICENSE$"),
        re.compile(r"(^|/)CHANGELOG$"),
        re.compile(r"\.gitignore$"),
        re.compile(r"\.editorconfig$"),
    ]

    _TRIVIAL_SESSION_MINUTES = 10


    def is_git_push_command(command: str | None) -> bool:
        """Check if a command string is a git push command."""
        if not command:
            return False
        return _GIT_PUSH_PATTERN.search(command) is not None


    def check_retrospective_in_session_log(session_log: Path) -> bool:
        """Check if session log contains retrospective evidence."""
        try:
            content = session_log.read_text(encoding="utf-8")
            if _RETROSPECTIVE_SECTION_PATTERN.search(content):
                return True
            if _RETROSPECTIVE_FILE_REF_PATTERN.search(content):
                return True
        except OSError:
            pass
        return False


    def check_retrospective_file_exists(project_dir: str) -> bool:
        """Check if a retrospective file exists for today."""
        retro_dir = Path(project_dir) / ".agents" / "retrospective"
        if not retro_dir.is_dir():
            return False

        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
        try:
            # Look for files matching today's date
            today_retros = list(retro_dir.glob(f"{today}*.md"))
            return len(today_retros) > 0
        except OSError:
            return False


    def check_documentation_only() -> bool:
        """Check if all changed files are documentation-only."""
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                result = subprocess.run(
                    ["git", "diff", "--name-only", "origin/main"],
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                if result.returncode != 0:
                    return False

            changed_files = result.stdout.strip()
            if not changed_files:
                return True  # No changes, allow

            for file_path in changed_files.splitlines():
                is_doc = any(pat.search(file_path) for pat in _DOC_PATTERNS)
                if not is_doc:
                    return False

            return True
        except (subprocess.TimeoutExpired, OSError):
            return False


    def check_trivial_session(session_log: Path | None) -> bool:
        """Check if this is a trivial session (short duration, minimal changes).

        Uses the session log creation time to measure duration. Falls back to
        allowing bypass only when no session log exists (no session started).
        """
        if session_log is None:
            return False

        # Derive elapsed time from session log creation
        try:
            log_ctime = session_log.stat().st_ctime
            elapsed_minutes = (time.time() - log_ctime) / 60
        except OSError:
            return False

        if elapsed_minutes > _TRIVIAL_SESSION_MINUTES:
            return False

        # Check number of changed files
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                return False

            changed_files = result.stdout.strip().splitlines()
            # Trivial = single file change
            return len(changed_files) <= 1
        except (subprocess.TimeoutExpired, OSError):
            return False


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            if not is_git_push_command(command):
                return 0

            project_dir = get_project_directory()
            sessions_dir = os.path.join(project_dir, ".agents", "sessions")

            # Skip if .agents infrastructure is absent (consumer repo)
            if not os.path.isdir(sessions_dir):
                print(
                    "[SKIP] .agents/sessions/ not found (consumer repo). "
                    "Retrospective enforcement skipped.",
                    file=sys.stderr,
                )
                return 0

            # Bypass 1: Environment variable override
            if os.environ.get("SKIP_RETROSPECTIVE_GATE") == "true":
                print(
                    "Retrospective gate bypassed via SKIP_RETROSPECTIVE_GATE environment variable",
                    file=sys.stderr,
                )
                return 0

            # Resolve session log early (needed by trivial session check)
            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            session_log = get_today_session_log(sessions_dir, date=today)

            # Bypass 2: Documentation-only changes
            if check_documentation_only():
                return 0

            # Bypass 3: Trivial session
            if check_trivial_session(session_log):
                return 0

            has_retrospective = False

            # Check 1: Retrospective file exists for today
            if check_retrospective_file_exists(project_dir):
                has_retrospective = True

            # Check 2: Retrospective section in session log
            if session_log and check_retrospective_in_session_log(session_log):
                has_retrospective = True

            if has_retrospective:
                return 0

            # Block: No retrospective evidence found
            output = f"""
    ## BLOCKED: Retrospective Required Before Push

    **Session retrospective required per ADR-033 enforcement gates.**

    ### Why Retrospectives Matter
    - Capture learnings while context is fresh
    - Prevent knowledge loss across sessions
    - Enable continuous improvement
    - Build institutional memory

    ### How to Satisfy This Gate

    **Option 1: Run retrospective agent**
    ```
    Task(subagent_type='retrospective', prompt='Analyze this session for learnings')
    ```

    **Option 2: Add retrospective section to session log**
    Add a `## Retrospective` section to today's session log with:
    - What went well
    - What could improve
    - Key learnings

    **Option 3: Create retrospective file**
    Create `.agents/retrospective/{today}-*.md` with session analysis.

    ### Bypass Conditions
    - Documentation-only changes (auto-detected)
    - Trivial sessions (<10 minutes, single file)
    - Set `SKIP_RETROSPECTIVE_GATE=true` (requires justification)

    **Current Date**: {today}
    **Session Log**: {session_log.name if session_log else "Not found"}
    """
            print(output)
            print("Push blocked: No retrospective evidence found", file=sys.stderr)
            return 2

        except Exception as exc:
            # Fail-open on errors (don't block on infrastructure issues)
            print(
                f"Retrospective gate error: {type(exc).__name__} - {exc}",
                file=sys.stderr,
            )
            return 0
    return main()

_shim_dispatch()
