from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Glob
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Glob'

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _json.loads(raw_value)
        except ValueError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_tool_input_from_tool_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolArgs")


def _shim_top_level_input_field(payload):
    if payload.get("tool_input") is not None:
        return "tool_input"
    if "toolArgs" in payload:
        return "toolArgs"
    return "tool_input"


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_top_level_candidate(payload):
    name_fields = [key for key in ("tool_name", "toolName") if key in payload]
    if not name_fields:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    names = [
        _shim_validate_tool_name(payload[field], field)
        for field in name_fields
    ]
    if len(names) == 2 and names[0] != names[1]:
        raise ValueError("conflicting top-level tool_name/toolName values")
    return payload, _shim_top_level_input_field(payload)


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        if not tool_calls and (
            "tool_name" in payload or "toolName" in payload
        ):
            raise ValueError(
                "empty toolCalls conflicts with top-level tool_name/toolName"
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        tool_args = _shim_tool_input_from_tool_args(tool_args)
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    replay = dict(selected)
    changed = selected is not payload
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        replay["tool_input"] = _shim_tool_input_from_tool_args(replay.get("toolArgs"))
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block the Glob tool on code symbols when an LSP can navigate them.

    Claude Code PreToolUse hook (matcher: Glob) for ADR-062 conditional LSP-first
    enforcement. Ported from the claude-code-lsp-enforcement-kit (nesaminua, MIT,
    v2.3.2), file ``kit/hooks/lsp-first-glob-guard.js``. It closes the gap where an
    agent locates a symbol by filename glob (for example ``*UserService*``) instead
    of using a symbol-navigation tool, bypassing the Grep and Read guards. The kit
    blocks unconditionally; this port conditions the block on LSP availability so a
    miss degrades to allowing the raw tool (fail-open), never a deadlock.

    Canonical kit decision shape (``lsp-first-glob-guard.js:37-58``), quoted
    character-for-character (canonical-source-mirror.md):

        if (data.tool_name !== 'Glob') process.exit(0);
        const pattern = String(data.tool_input?.pattern ?? '').trim();
        if (!pattern) process.exit(0);
        ...
        const tokens = pattern
          .split(/[*/.\\{}\\[\\]()!?,\\s|+-]+/)
          .map(t => t.trim())
          .filter(Boolean);
        const symbolTokens = tokens.filter(t => isCodeSymbol(t));
        if (symbolTokens.length === 0) process.exit(0);

    Stricter/looser/different than canonical
    ----------------------------------------
    - CONDITIONAL block (the load-bearing ADR-062 difference): the kit blocks any
      symbol-shaped glob token regardless of LSP availability. This port blocks only
      when (a) a token is a code symbol AND (b) a ``symbol_navigation`` provider is
      configured for the glob's code-extension target, or, for a bare symbol glob
      with no extension, for any configured programming language in the repo. Any
      other case ALLOWS (exit 0). Mandatory per release-it.md fail-open.
    - SHARED symbol detection: token detection uses
      ``scripts.hook_utilities.lsp_symbols.is_code_symbol`` (the verbatim
      ``lsp-first-guard.js`` port), not the glob guard's own larger ``skipExact``
      set. The lib's short-lowercase and casing rules already reject the dir and
      framework stems the kit listed explicitly; the result is equivalent for glob
      tokens and avoids a second, drifting allowlist.
    - DROPPED structured-block stdout JSON and the hardcoded NON_CODE_PATH denylist;
      capability detection in ``lsp_provider`` (sourced from ``.serena/project.yml``)
      replaces the denylist, and the recovery guidance replaces the dashboard JSON.
    - ADDED ``LSP_GATE_MODE=warn`` advisory mode, ``SKIP_LSP_GATE`` kill switch, and
      consumer-repo skip (ADR-062 Sections 5, 6), mirroring the sibling guards.

    Hook Type: PreToolUse (matcher: Glob)
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not Glob, empty/no-symbol pattern, no provider for the target,
            warn mode, kill switch, consumer repo, any fail-open path)
        2 = Block (symbol-shaped glob token with an available symbol_navigation
            provider, default block mode)
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    _lib_dir: str | None = None
    if _plugin_root:  # pragma: no cover - deployment layout (env set), not test env
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:  # pragma: no cover - filesystem root, marker found first
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):  # pragma: no cover - lib always present
        print(
            f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        # Fail-open: a navigation guard must never wedge a turn on bootstrap failure.
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import get_project_directory  # noqa: E402
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402
    from hook_utilities.lsp_health import (  # noqa: E402
        lsp_runtime_down,
        warn_once_lsp_down,
    )
    from hook_utilities.lsp_provider import (  # noqa: E402
        EXTENSION_TO_SERENA_LANGUAGE,
        PROGRAMMING_SERENA_LANGUAGES,
        PROVIDERS,
        SYMBOL_NAVIGATION,
        detect_providers,
    )
    from hook_utilities.lsp_symbols import is_code_symbol, strip_zero_width  # noqa: E402

    _HOOK_NAME = "lsp-glob-guard"
    _WARN_MODE = "warn"

    # Port of the kit token splitter (``lsp-first-glob-guard.js:52-55``): strip glob
    # metacharacters, separators, and operators to isolate alphabetic tokens.
    _TOKEN_SPLIT = re.compile(r"[*/.\\{}\[\]()!?,\s|+\-]+")
    # Trailing file extension of a glob: a final ``.<alnum>`` run. Matching on the
    # raw pattern avoids the dotfile trap (stripping ``*`` from ``**/*.json`` leaves
    # ``/.json``, which ``Path.suffix`` reads as a hidden file with no extension).
    _EXTENSION_RE = re.compile(r"\.([A-Za-z0-9]+)$")


    def _coerce_str(value: object) -> str:
        """Coerce a tool_input value to a stripped string, never raising.

        Mirrors the kit's ``String(data.tool_input?.pattern ?? '')`` coercion so a
        non-string pattern becomes a benign string rather than crashing.
        """
        if value is None:
            return ""
        return str(value).strip()


    def find_glob_symbols(pattern: str) -> list[str]:
        """Return the symbol-shaped tokens of a Glob pattern.

        Ports ``lsp-first-glob-guard.js:52-58``: split on glob metacharacters and
        separators, drop empties, and keep tokens that ``is_code_symbol`` recognizes.
        Zero-width characters are stripped first so an invisible split cannot bypass
        the ASCII checks.
        """
        cleaned = strip_zero_width(pattern)
        tokens = [tok.strip() for tok in _TOKEN_SPLIT.split(cleaned)]
        return [tok for tok in tokens if tok and is_code_symbol(tok)]


    def glob_extension(pattern: str) -> str:
        """Return the trailing file extension of a glob, or '' if none.

        ``*UserService*.ts`` -> ``.ts``; ``**/*.json`` -> ``.json``;
        ``*UserService*`` -> ``''``; ``src/**`` -> ``''``.
        """
        match = _EXTENSION_RE.search(pattern.strip())
        return f".{match.group(1)}" if match else ""


    def resolve_providers(pattern: str, project_dir: str) -> list[str]:
        """Resolve the symbol_navigation providers relevant to a glob pattern.

        Two cases:
          - The glob names a file extension (``*Foo*.ts``): ask the provider layer
            whether that extension is symbol-navigation capable. A non-code or
            non-symbol-navigable extension (``.md``) yields an empty list (allow).
          - The glob is a bare symbol search (``*UserService*``, no extension): it
            searches code files by symbol name, so probe each configured programming
            language and return the first non-empty provider list. Empty means no
            symbol-navigation LSP is configured for code in this repo (allow).
        """
        extension = glob_extension(pattern)
        if extension:
            return list(detect_providers(f"x{extension}", SYMBOL_NAVIGATION, project_dir))
        for probe_ext, language in EXTENSION_TO_SERENA_LANGUAGE.items():
            if language not in PROGRAMMING_SERENA_LANGUAGES:
                continue
            providers = detect_providers(f"x{probe_ext}", SYMBOL_NAVIGATION, project_dir)
            if providers:
                return list(providers)
        return []


    def build_guidance(pattern: str, symbols: list[str], providers: list[str]) -> str:
        """Build LSP-first recovery guidance for a blocked symbol-shaped glob.

        Names, per provider, the find_symbol / find_referencing_symbols tool to use
        (PascalCase -> definition, else references) plus the activate_project +
        initial_instructions recovery path for the post-compaction case where Serena
        is configured but inactive.
        """
        lines = [
            f"LSP-FIRST: Glob pattern '{pattern}' contains {len(symbols)} code "
            f"symbol(s): {', '.join(symbols)}.",
            "Find files by symbol name with a symbol-navigation tool, not a glob:",
        ]
        for symbol in symbols:
            intent = "definition" if symbol[:1].isupper() else "references"
            lines.append(f"  {symbol}:")
            for provider_key in providers:
                provider = PROVIDERS.get(provider_key)
                if provider is None:
                    continue
                tool = provider["tools"].get(intent) or provider["tools"].get("symbol_search")
                if not tool:
                    continue
                lines.append(f"    {provider['prefix']}{tool} ({provider['label']})")
        lines.append(
            "Globbing by extension or lowercase concept (for example '*.ts', "
            "'*auth*') is allowed."
        )
        lines.append(
            "Recovery if the LSP is unavailable: call "
            "mcp__serena__activate_project then mcp__serena__initial_instructions, "
            "or set SKIP_LSP_GATE=true to bypass."
        )
        return "\n".join(lines)


    def _emit_warn(guidance: str) -> None:
        """Emit guidance as an exit-0 advisory (LSP_GATE_MODE=warn)."""
        print(json.dumps({"systemMessage": guidance}))
        print(f"{_HOOK_NAME}: warn mode, allowing Glob (advisory only)", file=sys.stderr)


    def _emit_block(guidance: str, symbols: list[str]) -> None:
        """Emit guidance as a blocking message (default block mode)."""
        print(guidance)
        print(
            f"{_HOOK_NAME}: blocked Glob on code symbol(s) {', '.join(symbols)}",
            file=sys.stderr,
        )


    def _bypassed() -> bool:
        """Allow without evaluating: consumer repo or the SKIP_LSP_GATE kill switch (ADR-062)."""
        if skip_if_consumer_repo(_HOOK_NAME):
            return True
        if os.environ.get("SKIP_LSP_GATE", "").strip().lower() == "true":
            print(f"{_HOOK_NAME}: SKIP_LSP_GATE set, allowing", file=sys.stderr)
            return True
        return False


    def _evaluate(
        hook_input: dict[str, object],
    ) -> tuple[str, list[str], list[str]] | None:
        """Decide whether a Glob call should block.

        Returns ``(pattern, symbols, providers)`` when the pattern carries a code
        symbol and a symbol_navigation provider is available; otherwise ``None``.
        """
        if hook_input.get("tool_name") != "Glob":
            return None
        tool_input = hook_input.get("tool_input")
        if not isinstance(tool_input, dict):
            return None
        pattern = _coerce_str(tool_input.get("pattern"))
        if not pattern:
            return None
        symbols = find_glob_symbols(pattern)
        if not symbols:
            return None
        providers = resolve_providers(pattern, get_project_directory())
        if not providers:
            return None
        return pattern, symbols, providers


    def main() -> int:
        """Main hook entry point. Returns exit code (0 allow, 2 block)."""
        if _bypassed():
            return 0

        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            decision = _evaluate(json.loads(input_json))
            if decision is None:
                return 0

            pattern, symbols, providers = decision

            if lsp_runtime_down():
                warn_once_lsp_down(_HOOK_NAME, get_project_directory())
                return 0

            guidance = build_guidance(pattern, symbols, providers)
            if os.environ.get("LSP_GATE_MODE", "").lower() == _WARN_MODE:
                _emit_warn(guidance)
                return 0

            _emit_block(guidance, symbols)
            return 2

        except Exception as exc:  # noqa: BLE001 - fail-open is mandatory (ADR-062)
            print(f"{_HOOK_NAME} error: {type(exc).__name__} - {exc}", file=sys.stderr)
            return 0
    return main()

_shim_dispatch()
