from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push on markdownlint violations in changed .md files.

    Thin adapter over :mod:`push_guard_base`. Activates on ``*.md`` files in
    the push changeset and runs ``markdownlint-cli2`` against them. Failures
    of the binary itself (missing PATH entry, timeout, OSError) fail-open;
    only real lint violations block.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (no .md files, binary missing, timeout, OSError, clean)
        2 = Block (markdownlint reported violations)
    """


    import os
    import shutil
    import subprocess
    import sys
    from pathlib import Path

    def _find_hooks_dir(root: Path) -> str | None:
        """Return hooks dir, trying both PreToolUse (Claude) and preToolUse (copilot-cli)."""
        for variant in ("PreToolUse", "preToolUse"):
            candidate = root / "hooks" / variant
            if candidate.is_dir():
                return str(candidate)
        return None


    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _resolved_root = Path(_plugin_root).resolve()
        _hooks_dir = _find_hooks_dir(_resolved_root)
        _lib_dir = str(_resolved_root / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _hooks_dir = None
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _hooks_dir = _find_hooks_dir(_cur)
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _hooks_dir is None or not os.path.isdir(_hooks_dir):
        print(
            f"Plugin hooks directory not found: {_hooks_dir} "
            f"(CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        sys.exit(2)
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(
            f"Plugin lib directory not found: {_lib_dir} "
            f"(CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        sys.exit(2)
    if _hooks_dir not in sys.path:
        sys.path.insert(0, _hooks_dir)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from push_guard_base import run_guard  # noqa: E402
    from hook_utilities import get_project_directory  # noqa: E402

    GUARD_NAME = "markdown-lint"
    BINARY = "markdownlint-cli2"
    SUBPROCESS_TIMEOUT = 60
    VERSION_TIMEOUT = 5


    def _log_version() -> None:
        try:
            proc = subprocess.run(
                [BINARY, "--version"],
                capture_output=True,
                text=True,
                timeout=VERSION_TIMEOUT,
                shell=False,
                check=False,
            )
            version = (proc.stdout or proc.stderr).strip().splitlines()
            first_line = version[0] if version else "(unknown)"
            print(f"[{GUARD_NAME}] using {BINARY} {first_line}", file=sys.stderr)
        except (subprocess.TimeoutExpired, OSError):
            print(
                f"[{GUARD_NAME}] could not determine {BINARY} version",
                file=sys.stderr,
            )


    def _validate(matching: list[str], _all_changed: list[str]) -> list[str]:
        if shutil.which(BINARY) is None:
            print(
                f"[{GUARD_NAME}] {BINARY} not found on PATH; "
                f"allowing push (fail-open)",
                file=sys.stderr,
            )
            return []

        _log_version()

        project_dir = get_project_directory()
        try:
            # --no-globs: lint only the explicit file args. Without this flag
            # markdownlint-cli2 walks the repo's default **/*.md set and may
            # report violations in files outside the changeset, which is
            # exactly the noise the pre-push gate is meant to avoid.
            proc = subprocess.run(
                [BINARY, "--no-globs", *matching],
                capture_output=True,
                text=True,
                timeout=SUBPROCESS_TIMEOUT,
                shell=False,
                check=False,
                cwd=project_dir,
            )
        except subprocess.TimeoutExpired:
            print(
                f"[TIMEOUT] {BINARY} exceeded {SUBPROCESS_TIMEOUT}s; "
                f"allowing push",
                file=sys.stderr,
            )
            return []
        except OSError as exc:
            print(
                f"[OSError] {BINARY} failed to invoke: {exc}; allowing push",
                file=sys.stderr,
            )
            return []

        if proc.returncode == 0:
            return []

        violations = [
            line for line in proc.stdout.splitlines() if line.strip()
        ]
        if not violations and proc.stderr.strip():
            violations = [
                line for line in proc.stderr.splitlines() if line.strip()
            ]
        return violations


    def main() -> int:
        return run_guard(_validate, ["*.md"], GUARD_NAME)


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
