from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: '^(Agent|Task)$'
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
# Exit codes: 0 when the matcher does not fire (allow) or the wrapped script
# succeeds, or the wrapped script's own code when it fires. Internal matcher
# errors use the wrapped hook's declared fail-open or fail-closed policy.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Agent|Task)$'
_INPUT_ERROR_CODE = 0

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match each top-level `|` branch as a separate glob alternative."""
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def _shim_load_json(raw_value):
    return _json.loads(raw_value, object_pairs_hook=_shim_unique_object)


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _shim_load_json(raw_value)
        except _json.JSONDecodeError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_json_equal(left, right):
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _shim_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _shim_json_equal(a, b) for a, b in zip(left, right))
    return left == right


def _shim_alias_value(payload, snake, camel, parser=None):
    fields = [field for field in (snake, camel) if field in payload]
    if not fields:
        return False, None, snake, False
    values = [payload[field] for field in fields]
    if parser is not None:
        values = [parser(value, field) for value, field in zip(values, fields)]
    if len(values) == 2 and not _shim_json_equal(values[0], values[1]):
        raise ValueError(
            "conflicting top-level {}/{} values".format(snake, camel)
        )
    changed = fields != [snake] or values[0] != payload[snake]
    return True, values[0], "/".join(fields), changed


def _shim_top_level_candidate(payload):
    has_name, name, _, name_changed = _shim_alias_value(
        payload, "tool_name", "toolName", _shim_validate_tool_name
    )
    if not has_name:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    input_payload = payload
    if payload.get("tool_input") is None and "toolArgs" in payload:
        input_payload = {key: value for key, value in payload.items() if key != "tool_input"}
    has_input, tool_input, input_field, input_changed = _shim_alias_value(
        input_payload, "tool_input", "toolArgs", _shim_parse_json_string
    )
    has_call_id, call_id, _, call_id_changed = _shim_alias_value(
        payload, "tool_call_id", "toolCallId"
    )
    if not (name_changed or input_changed or call_id_changed):
        return payload, input_field
    candidate = dict(payload)
    for field in ("toolName", "toolArgs", "toolCallId"):
        candidate.pop(field, None)
    candidate["tool_name"] = name
    if has_input:
        candidate["tool_input"] = tool_input
    if has_call_id:
        candidate["tool_call_id"] = call_id
    return candidate, input_field


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        # A payload may carry top-level action fields OR a `toolCalls` batch,
        # never both: the host precedence contract between the two shapes is
        # unverified, so a top-level Read alongside a Bash in `toolCalls` is
        # ambiguous. Reject any mix (empty or non-empty batch) before a guard
        # ever sees a candidate (#3200).
        conflicting = [
            field
            for field in (
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            )
            if field in payload
        ]
        if conflicting:
            raise ValueError(
                "toolCalls conflicts with top-level action fields: "
                + ", ".join(conflicting)
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    if selected is payload:
        return raw
    return _json.dumps(selected, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)  # always fail-closed for oversized payloads
    try:
        payload = _shim_load_json(_raw or b"{}")
    except RecursionError:
        # Deeply nested JSON exhausts the parser recursion budget and raises
        # RecursionError, which is NOT a ValueError subclass, so it would
        # otherwise escape the malformed-JSON handler below, print a traceback,
        # and exit 1. A standalone shim (run directly, not under the dispatcher)
        # must fail closed the same way the dispatcher does: bounded diagnostic
        # (no traceback, no payload bytes) and exit 2 (issue #3169).
        print(
            "matcher-shim [{}]: stdin JSON nesting too deep; refusing".format(
                _MATCHER
            ),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    except ValueError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(_INPUT_ERROR_CODE)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Require an explicit model on sub-agent spawns (issue #4874).

    A sub-agent whose type has no definition file with a nonempty ``model:``
    pin silently
    inherits the session model. On a Fable or Opus session that prices every
    general-purpose spawn at session-model cost with nobody deciding it. This
    gate denies the spawn unless the call names a model, the agent type has a
    model-pinned definition file in the active harness, or the operator set
    ``CLAUDE_CODE_SUBAGENT_MODEL`` to allow inherit-by-default.

    Customer value: no silent session-model inheritance for sub-agents on
    either harness.

    Cross-harness payload contract:
        Claude Code registers the spawn tool as ``Agent`` (``Task`` before the
        rename) and sends ``tool_input.subagent_type`` plus optional
        ``tool_input.model``. Copilot CLI's runtime tool is ``task`` (Claude
        name ``Agent``); its args carry ``agent_type`` and optional ``model``,
        observed in a real session log (Copilot CLI 1.0.79, 2026-08-06,
        ``events.jsonl`` ``toolRequests``). Native camelCase registrations send
        ``toolName``/``toolArgs`` where ``toolArgs`` may be a JSON string.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (model named, escape hatch set, definition file found,
            unrelated tool, or malformed input)
        2 = Block (no model, no definition file, or payload exceeds 2 MiB)

    Malformed input within the payload limit fails open by design. Payload
    overflow fails closed before parsing. Copilot CLI treats a PreToolUse hook
    crash as deny-all for the session (#4672), so an infrastructure failure must
    never outrank the guard's own policy. This gate bounds model spend; it is not
    a security boundary, so allow-on-broken-input is the cheaper error.
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    _MAX_STDIN_BYTES = 2 * 1024 * 1024
    _SUBAGENT_TOOLS = frozenset({"Agent", "Task", "task"})
    _ESCAPE_HATCH_ENV = "CLAUDE_CODE_SUBAGENT_MODEL"
    _EMPTY_MODEL_VALUES = frozenset({"", "null", "none", "~", '""', "''"})
    _NON_STRING_MODEL_VALUES = frozenset({"false", "no", "off", "on", "true", "yes"})
    _UNQUOTED_MODEL_RE = re.compile(r"[A-Za-z][A-Za-z0-9._ /()+-]*")


    def _user_root(home: Path, *, copilot: bool) -> Path:
        variable = "COPILOT_HOME" if copilot else "CLAUDE_CONFIG_DIR"
        default = ".copilot" if copilot else ".claude"
        configured = os.environ.get(variable, "").strip()
        return Path(configured).expanduser() if configured else home / default


    def _plugin_name(root: Path) -> str | None:
        manifest = root / ".claude-plugin" / "plugin.json"
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            return None
        name = data.get("name") if isinstance(data, dict) else None
        return name.strip() if isinstance(name, str) and name.strip() else None


    def _active_plugin_roots(plugin: str) -> tuple[Path, ...]:
        roots: list[Path] = []
        for variable in ("COPILOT_PLUGIN_ROOT", "CLAUDE_PLUGIN_ROOT"):
            configured = os.environ.get(variable, "").strip()
            if not configured:
                continue
            root = Path(configured).expanduser()
            if root not in roots and _plugin_name(root) == plugin:
                roots.append(root)
        return tuple(roots)


    def _definition_search_space(
        name: str,
        plugin: str | None,
        home: Path,
        project: Path,
        *,
        copilot: bool,
    ) -> tuple[tuple[Path, tuple[str, ...]], ...]:
        """Glob patterns for model-pinned definitions loaded by one harness."""
        if plugin:
            active_patterns = (
                (f"agents/{name}.agent.md", f"agents/{name}.md")
                if copilot
                else (f"agents/{name}.md",)
            )
            active_roots = tuple(
                (root, active_patterns) for root in _active_plugin_roots(plugin)
            )
            if copilot:
                return active_roots + (
                    (
                        _user_root(home, copilot=True),
                        (
                            f"installed-plugins/*/{plugin}/agents/{name}.agent.md",
                            f"installed-plugins/*/{plugin}/agents/{name}.md",
                        ),
                    ),
                )
            return active_roots + (
                (
                    _user_root(home, copilot=False),
                    (
                        f"plugins/**/{plugin}/agents/{name}.md",
                        f"plugins/**/{plugin}/*/agents/{name}.md",
                    ),
                ),
            )
        if copilot:
            return (
                (project / ".github", (f"agents/{name}.agent.md", f"agents/{name}.md")),
                (
                    _user_root(home, copilot=True),
                    (
                        f"agents/{name}.agent.md",
                        f"agents/{name}.md",
                    ),
                ),
            )
        return (
            (project / ".claude", (f"agents/{name}.md",)),
            (_user_root(home, copilot=False), (f"agents/{name}.md",)),
        )


    def _model_scalar(value: str) -> str | None:
        """Return a model only when the YAML token is semantically a string."""
        candidate = value.split("#", 1)[0].strip()
        if not candidate:
            return None
        if candidate.startswith('"'):
            try:
                parsed = json.loads(candidate)
            except (json.JSONDecodeError, ValueError):
                return None
            return parsed if isinstance(parsed, str) and parsed.strip() else None
        if candidate.startswith("'"):
            if len(candidate) < 2 or not candidate.endswith("'"):
                return None
            parsed = candidate[1:-1].replace("''", "'")
            return parsed if parsed.strip() else None
        normalized = candidate.lower()
        if (
            normalized in _EMPTY_MODEL_VALUES
            or normalized in _NON_STRING_MODEL_VALUES
            or not _UNQUOTED_MODEL_RE.fullmatch(candidate)
        ):
            return None
        return candidate


    def _pinned_model(path: Path) -> str | None:
        """Return a nonempty top-level model from YAML frontmatter."""
        try:
            with path.open(encoding="utf-8") as stream:
                if stream.readline().strip() != "---":
                    return None
                model: str | None = None
                for line in stream:
                    if line.strip() == "---":
                        return model
                    if line[:1].isspace():
                        continue
                    key, separator, value = line.partition(":")
                    if separator and key == "model":
                        if model is not None:
                            return None
                        model = _model_scalar(value)
                        if model is None:
                            return None
        except (OSError, UnicodeError):
            return None
        return None


    def _has_pinned_definition(
        name: str,
        plugin: str | None,
        home: Path,
        project: Path,
        *,
        copilot: bool,
    ) -> bool:
        for root, patterns in _definition_search_space(
            name,
            plugin,
            home,
            project,
            copilot=copilot,
        ):
            if not root.is_dir():
                continue
            for pattern in patterns:
                definitions = tuple(
                    path for path in sorted(root.glob(pattern)) if path.is_file()
                )
                if definitions:
                    return all(_pinned_model(path) is not None for path in definitions)
        return False


    def _spawn_arguments(payload: dict[str, object]) -> dict[str, object] | None:
        """Normalize tool arguments across payload spellings.

        Claude and PascalCase Copilot registrations send ``tool_input`` as an
        object. Native camelCase Copilot registrations send ``toolArgs``,
        sometimes as a JSON string.
        """
        args = payload.get("tool_input")
        if args is None:
            args = payload.get("toolArgs")
        if isinstance(args, str):
            args = json.loads(args)
        return args if isinstance(args, dict) else None


    def _has_explicit_model(value: object) -> bool:
        if not isinstance(value, str):
            return False
        return value.strip().lower() not in _EMPTY_MODEL_VALUES


    def _safe_search_part(value: str) -> bool:
        if value in {"", ".", ".."} or not value.isprintable():
            return False
        return not any(character in value for character in "*?[]/\\:")


    def _read_payload() -> object:
        stream = getattr(sys.stdin, "buffer", sys.stdin)
        raw = stream.read(_MAX_STDIN_BYTES + 1)
        if len(raw) > _MAX_STDIN_BYTES:
            raise OverflowError(f"stdin exceeds {_MAX_STDIN_BYTES} bytes")
        return json.loads(raw)


    def _is_copilot_payload(payload: dict[str, object]) -> bool:
        """Detect Copilot payloads from guaranteed schema signals.

        Native Copilot uses lowercase ``toolName``/``toolArgs`` while Claude Code
        uses ``tool_name``/``tool_input``.  The Copilot plugin dispatcher uses
        PascalCase ``PreToolUse`` and sets ``COPILOT_PLUGIN_ROOT``, so its
        payloads match the Claude schema but run in a Copilot context.
        """
        if "toolName" in payload and "tool_name" not in payload:
            return True
        return bool(os.environ.get("COPILOT_PLUGIN_ROOT", "").strip())


    def _project_root(payload: dict[str, object]) -> Path:
        # Copilot hooks run with cwd set to the repository root by contract.
        # Detect Copilot first so CLAUDE_PROJECT_DIR (a Claude-only variable)
        # cannot redirect Copilot definition lookup.
        if _is_copilot_payload(payload):
            return Path.cwd()
        configured = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
        if configured:
            return Path(configured).expanduser()
        cwd = payload.get("cwd")
        return Path(cwd) if isinstance(cwd, str) and cwd.strip() else Path(".")


    def main() -> int:
        try:
            payload = _read_payload()
        except OverflowError as exc:
            print(f"require-subagent-model: {exc}; refusing", file=sys.stderr)
            return 2
        if not isinstance(payload, dict):
            return 0
        tool = payload.get("tool_name") or payload.get("toolName") or ""
        if tool not in _SUBAGENT_TOOLS:
            return 0
        args = _spawn_arguments(payload)
        if args is None:
            return 0
        if _has_explicit_model(args.get("model")) or os.environ.get(_ESCAPE_HATCH_ENV):
            return 0
        agent = args.get("subagent_type") or args.get("agent_type") or ""
        if not isinstance(agent, str) or not agent:
            return 0
        plugin_prefix, separator, name = agent.rpartition(":")
        plugin: str | None = plugin_prefix if separator else None
        searchable_parts = (name, plugin) if plugin else (name,)
        searchable = all(_safe_search_part(part) for part in searchable_parts)
        project = _project_root(payload)
        copilot = (
            tool == "task"
            or "toolName" in payload
            or "toolArgs" in payload
            or bool(os.environ.get("COPILOT_PLUGIN_ROOT"))
        )
        if searchable and _has_pinned_definition(
            name,
            plugin,
            Path.home(),
            project,
            copilot=copilot,
        ):
            return 0
        print(
            f"Sub-agent '{agent}' has no model-pinned definition file and this call "
            "names no model, so it would silently inherit the session model. Pass "
            "model: in the call, add an agent definition with a nonempty model:, or set "
            f"{_ESCAPE_HATCH_ENV} to allow inherit-by-default.",
            file=sys.stderr,
        )
        return 2
    try:
        return main()
    except Exception as _exc:
        __import__('sys').stderr.write('[WARNING] hook error (fail-open): ' + str(_exc) + '\n')
        return 0

_shim_dispatch()
