#!/usr/bin/env python3
"""Create GitHub issues from artifact insight findings.

Replaces the PowerShell 'Create issues for findings' block in
artifact-insight-scanner.yml (ADR-006).

ENV:
  FINDINGS_JSON       - JSON array of finding objects (title, body, labels, source)
  GITHUB_REPOSITORY   - owner/repo for issue creation
  SERVER_URL          - GitHub server URL
  RUN_ID              - workflow run ID for provenance footer
  GH_TOKEN            - GitHub token (consumed by gh CLI automatically)

EXIT CODES (ADR-035):
  0 - completed (some issues may have been skipped as duplicates)
  1 - FINDINGS_JSON is missing or malformed
"""

from __future__ import annotations

import json
import os
import subprocess
import sys


def write_github_output(key: str, value: str) -> None:
    """Append key=value to GITHUB_OUTPUT; fall back to stdout."""
    path = os.environ.get("GITHUB_OUTPUT", "")
    if path:
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(f"{key}={value}\n")
    else:
        print(f"{key}={value}")


def _is_duplicate(title: str) -> bool:
    """Return True if an open issue with a similar title already exists."""
    try:
        raw = subprocess.run(
            [
                "gh",
                "issue",
                "list",
                "--search",
                f'is:issue is:open in:title "{title}"',
                "--json",
                "number,title",
                "--limit",
                "5",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if raw.returncode != 0:
            return False
        existing: list[dict[str, object]] = json.loads(raw.stdout or "[]")
        title_lower = title.lower()
        for issue in existing:
            issue_title = str(issue.get("title", "")).lower()
            if (
                title_lower == issue_title
                or title_lower in issue_title
                or issue_title in title_lower
            ):
                print(f"::notice::Skipping duplicate: '{title}' (matches #{issue.get('number')})")
                return True
    except (json.JSONDecodeError, OSError):
        pass
    return False


def _build_footer(server_url: str, repository: str, run_id: str, source: str) -> str:
    run_url = f"{server_url}/{repository}/actions/runs/{run_id}"
    return (
        "\n\n----\n\n"
        f"<sub>Auto-generated by [Artifact Insight Scanner]({run_url})</sub>\n"
        f"<sub>Source: `{source}`</sub>"
    )


def run(argv: list[str] | None = None) -> int:  # noqa: ARG001
    """Create issues for each non-duplicate finding."""
    findings_json = os.environ.get("FINDINGS_JSON", "")
    if not findings_json:
        print("::error::FINDINGS_JSON env var is required")
        return 1

    try:
        findings: list[dict[str, object]] = json.loads(findings_json)
    except json.JSONDecodeError as exc:
        print(f"::error::Failed to parse FINDINGS_JSON: {exc}")
        return 1

    server_url = os.environ.get("SERVER_URL", "")
    repository = os.environ.get("GITHUB_REPOSITORY", "")
    run_id = os.environ.get("RUN_ID", "")

    created_count = 0
    skipped_count = 0

    for finding in findings:
        title = str(finding.get("title", ""))
        body = str(finding.get("body", ""))
        labels_raw = finding.get("labels", [])
        labels: list[str] = (
            labels_raw if isinstance(labels_raw, list) else str(labels_raw).split(",")
        )
        source = str(finding.get("source", ""))

        if _is_duplicate(title):
            skipped_count += 1
            continue

        footer = _build_footer(server_url, repository, run_id, source)
        full_body = body + footer

        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--body",
                full_body,
                "--label",
                ",".join(labels),
            ],
            check=False,
        )

        if result.returncode == 0:
            created_count += 1
        else:
            print(f"::warning::Failed to create issue: {title}")

    print()
    print("=== SUMMARY ===")
    print(f"Issues created: {created_count}")
    print(f"Duplicates skipped: {skipped_count}")
    return 0


def main() -> int:
    """Entry point."""
    return run()


if __name__ == "__main__":
    sys.exit(main())
