#!/usr/bin/env python3
"""Build and post the escalated AI issue triage PRD comment."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

DEFAULT_OUTPUT = Path("/tmp/prd-comment.md")


def _prd_depth(complexity_score: int) -> str:
    if complexity_score >= 10:
        return "Comprehensive"
    if complexity_score >= 7:
        return "Detailed"
    return "Standard"


def build_prd_comment(
    *,
    prd_content: str,
    complexity_score: str,
    escalation_criteria: str,
    repository: str,
    server_url: str,
    run_id: str,
) -> str:
    score = int(complexity_score)
    prd_depth = _prd_depth(score)
    footer = (
        f"<sub>Generated by [AI PRD Generation](https://github.com/{repository}) "
        f"| [View Workflow]({server_url}/{repository}/actions/runs/{run_id})</sub>"
    )
    return f"""<!-- AI-PRD-GENERATION -->

## Product Requirements Document

> [!IMPORTANT]
> This PRD was automatically generated based on issue triage escalation.
> **Complexity Score**: {complexity_score}/12 ({prd_depth})
> **Escalation Criteria**: {escalation_criteria}

<details>
<summary>About this PRD</summary>

This PRD was generated by the **Explainer Agent** after the issue was flagged
for detailed analysis. The document is designed to be self-contained - it can
be passed to a separate AI agent instance for implementation without additional
context.

**PRD Depth Levels**:
- **Standard** (4-6): Brief analysis, clear requirements
- **Detailed** (7-9): Research section, blocking questions
- **Comprehensive** (10-12): Phased implementation, risk analysis

</details>

---

{prd_content}
---

{footer}"""


def post_comment(*, issue_number: str, body_file: Path) -> int:
    result = subprocess.run(
        [
            "python3",
            ".github/scripts/run_with_retry.py",
            "--",
            "python3",
            ".github/scripts/post_issue_comment.py",
            "--issue",
            issue_number,
            "--body-file",
            str(body_file),
            "--marker",
            "AI-PRD-GENERATION",
        ],
        check=False,
    )
    return result.returncode


def main(argv: list[str] | None = None) -> int:
    if argv:
        return 2
    output = DEFAULT_OUTPUT
    comment = build_prd_comment(
        prd_content=os.environ.get("PRD_CONTENT", ""),
        complexity_score=os.environ.get("COMPLEXITY_SCORE", ""),
        escalation_criteria=os.environ.get("ESCALATION_CRITERIA", ""),
        repository=os.environ.get("GITHUB_REPOSITORY", ""),
        server_url=os.environ.get("SERVER_URL", ""),
        run_id=os.environ.get("RUN_ID", ""),
    )
    output.write_text(comment + "\n", encoding="utf-8")
    return post_comment(issue_number=os.environ.get("ISSUE_NUMBER", ""), body_file=output)


if __name__ == "__main__":
    raise SystemExit(main())
