"""Which recovery events a workflow actually subscribes to.

Issue #4835. A bulk cancellation of PR workflow runs is only safe when every
required context it kills can be regenerated. "Close and reopen the PR" is the
cheapest recovery, and on 2026-08-09 it did not work: several active workflows
declared an explicit ``pull_request.types`` list that omitted ``reopened``, so
reopening produced no run for them and the required contexts stayed missing.
Issue #4827 fixed those particular workflows. This module makes the class of
mistake detectable instead of relying on nobody re-introducing it.

The parsing contract, from GitHub's workflow syntax documentation
(https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows):

- ``on: pull_request`` with no ``types`` defaults to
  ``[opened, synchronize, reopened]``. That default is what
  :data:`DEFAULT_PULL_REQUEST_TYPES` records.
- ``pull_request_target`` carries the same default type list and the same
  trigger semantics for our purpose (it produces check runs on the PR), so its
  types are unioned into the same set.
- ``on:`` accepts three shapes: a bare string (``on: push``), a list
  (``on: [push, pull_request]``), and a mapping (``on: {pull_request: {...}}``).
  All three are handled.

One YAML trap is load-bearing here. ``on`` is a YAML 1.1 boolean literal, so
``yaml.safe_load`` parses the key ``on:`` as Python ``True``, not the string
``"on"``. A parser that reads only ``document["on"]`` sees no triggers at all
and would report every workflow as subscribing to nothing, which fails open in
the direction that matters: a workflow with no recorded subscription must never
be treated as recoverable.

A workflow ``name:`` is the identifier a run record carries, and GitHub does not
require it to be unique across files. Two files may declare the same name, so a
name resolves to a *set* of workflow files, not to one. Every event answered for
such a name is therefore the intersection across that set: only an event every
sharer subscribes to can regenerate the run, because the name alone does not say
which file produced it. See :func:`load_workflow_subscriptions`.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

__all__ = [
    "DEFAULT_PULL_REQUEST_TYPES",
    "RECOVERY_EVENTS",
    "WorkflowSubscriptions",
    "load_workflow_subscriptions",
    "parse_workflow_subscriptions",
    "subscribes_to",
]

# GitHub's documented default activity types for pull_request and
# pull_request_target when the workflow declares no explicit `types` list.
DEFAULT_PULL_REQUEST_TYPES: frozenset[str] = frozenset(
    {"opened", "synchronize", "reopened"}
)

# The recovery events a cancelled required context may be regenerated by.
# `rerun` re-executes the cancelled run itself and therefore needs no trigger
# subscription; the other three do.
RECOVERY_EVENTS: frozenset[str] = frozenset(
    {"synchronize", "reopened", "workflow_dispatch", "rerun"}
)

_PULL_REQUEST_TRIGGERS = ("pull_request", "pull_request_target")


@dataclass(frozen=True, slots=True)
class WorkflowSubscriptions:
    """The events a workflow subscribes to.

    One instance describes one workflow file, except for the record
    :func:`load_workflow_subscriptions` files under a ``name:`` that several
    files declare. That record describes the whole set and holds only what every
    file in it subscribes to.

    Attributes:
        name: The workflow's ``name:`` value, or its filename when unnamed.
        pull_request_types: Activity types unioned across ``pull_request`` and
            ``pull_request_target``. Empty when the workflow declares neither.
        has_workflow_dispatch: True when the workflow declares
            ``workflow_dispatch``, which is what makes a manual re-run possible.
    """

    name: str
    pull_request_types: frozenset[str]
    has_workflow_dispatch: bool


def _trigger_mapping(document: Mapping[Any, Any]) -> dict[str, Any]:
    """Return the ``on:`` block as a mapping of trigger name to its config.

    Reads both the ``True`` key (YAML 1.1 boolean coercion of ``on:``) and the
    literal ``"on"`` key, so a document loaded by a parser that preserved the
    string still resolves. Returns an empty mapping when the workflow declares
    no triggers at all.

    Iterating rather than indexing is deliberate: the document's key type is
    heterogeneous exactly because of that coercion, so ``document[True]`` is not
    expressible against a ``Mapping[str, Any]`` without lying about the type.
    """
    raw: Any = None
    for key, value in document.items():
        if key is True or key == "on":
            raw = value
            break

    if raw is None:
        return {}
    if isinstance(raw, str):
        return {raw: None}
    if isinstance(raw, list):
        return {item: None for item in raw if isinstance(item, str)}
    if isinstance(raw, Mapping):
        return {str(key): value for key, value in raw.items()}
    return {}


def _declared_types(config: object) -> frozenset[str]:
    """Activity types for one pull_request-family trigger config."""
    if not isinstance(config, Mapping):
        # `pull_request:` with a null or scalar body means "default types".
        return DEFAULT_PULL_REQUEST_TYPES
    if "types" not in config:
        return DEFAULT_PULL_REQUEST_TYPES
    types = config["types"]
    if isinstance(types, str):
        return frozenset({types})
    if isinstance(types, Iterable):
        return frozenset(str(item) for item in types)
    # An explicit but unusable `types:` value is not a default; treat it as no
    # subscription so the guard fails closed rather than assuming `reopened`.
    return frozenset()


def parse_workflow_subscriptions(
    document: Mapping[Any, Any], *, fallback_name: str = ""
) -> WorkflowSubscriptions:
    """Extract the event subscriptions from one parsed workflow document.

    Args:
        document: The workflow YAML parsed into a mapping.
        fallback_name: Name to use when the document declares no ``name:``.

    Returns:
        The subscriptions for this workflow. A document with no ``on:`` block
        yields empty types and no dispatch, which blocks every recovery event
        that needs a subscription.
    """
    triggers = _trigger_mapping(document)

    pull_request_types: set[str] = set()
    for trigger in _PULL_REQUEST_TRIGGERS:
        if trigger in triggers:
            pull_request_types |= _declared_types(triggers[trigger])

    declared_name = document.get("name")
    name = declared_name if isinstance(declared_name, str) and declared_name else fallback_name

    return WorkflowSubscriptions(
        name=name,
        pull_request_types=frozenset(pull_request_types),
        has_workflow_dispatch="workflow_dispatch" in triggers,
    )


def subscribes_to(subscriptions: WorkflowSubscriptions, event: str) -> bool:
    """True when this workflow can be regenerated by ``event``.

    ``rerun`` is always true: re-running a workflow run re-executes it through
    the Actions API regardless of which triggers the workflow declares.
    ``workflow_dispatch`` needs the trigger declared. Everything else is looked
    up in the pull_request activity types, so an unknown event name is false.
    """
    if event == "rerun":
        return True
    if event == "workflow_dispatch":
        return subscriptions.has_workflow_dispatch
    return event in subscriptions.pull_request_types


def _narrow_to_shared(
    first: WorkflowSubscriptions, second: WorkflowSubscriptions
) -> WorkflowSubscriptions:
    """Keep only the subscriptions two same-named workflow files share.

    Intersection is the fail-closed reading of an ambiguous name. A run record
    names its workflow, not its file, so when two files answer to that name the
    caller cannot tell which one produced the run. An event only one of them
    declares regenerates only one of them, so promising it would be the same
    fail-open mistake issue #4835 exists to prevent, one level up: the guard
    would report a verified recovery path for a run whose real workflow has
    none.
    """
    return WorkflowSubscriptions(
        name=first.name,
        pull_request_types=first.pull_request_types & second.pull_request_types,
        has_workflow_dispatch=(
            first.has_workflow_dispatch and second.has_workflow_dispatch
        ),
    )


def load_workflow_subscriptions(
    workflows_dir: Path,
) -> dict[str, WorkflowSubscriptions]:
    """Parse every workflow file in a directory, keyed by workflow name.

    Both the workflow's ``name:`` and its filename are registered as keys, so a
    caller holding either identifier resolves. A file that fails to parse is
    skipped rather than raising: one malformed workflow must not prevent the
    guard from reporting on the rest, and an absent entry already fails closed.

    A filename key always describes exactly that file. A ``name:`` key that two
    or more files declare describes all of them, narrowed by
    :func:`_narrow_to_shared` to the events every one of them subscribes to.
    Declared names are collected separately and merged in with ``setdefault`` so
    a ``name:`` that collides with a different file's filename cannot displace
    or narrow that file's own entry.
    """
    subscriptions: dict[str, WorkflowSubscriptions] = {}
    by_declared_name: dict[str, WorkflowSubscriptions] = {}
    if not workflows_dir.is_dir():
        return subscriptions

    for path in sorted(workflows_dir.iterdir()):
        if path.suffix not in (".yml", ".yaml") or not path.is_file():
            continue
        try:
            document = yaml.safe_load(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, yaml.YAMLError):
            continue
        if not isinstance(document, Mapping):
            continue
        parsed = parse_workflow_subscriptions(document, fallback_name=path.name)
        subscriptions[path.name] = parsed
        if parsed.name:
            already = by_declared_name.get(parsed.name)
            by_declared_name[parsed.name] = (
                parsed if already is None else _narrow_to_shared(already, parsed)
            )

    for name, merged in by_declared_name.items():
        subscriptions.setdefault(name, merged)
    return subscriptions
