#!/usr/bin/env python3
"""
Stop hook: Auto-generates retrospective on session end.

Creates a structured retrospective template in .agents/retrospective/ and
updates docs/retros/INDEX.md with a new entry.

Hook Type: Stop (non-blocking, always exits 0)
Exit Codes: Always 0 (fail-open — never blocks session stop)

Bypass: SKIP_AUTO_RETRO=true environment variable

Related:
- Issue #1703 (lifecycle hook infrastructure)
- ADR-008 (protocol automation lifecycle hooks)
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path


def get_project_directory() -> Path | None:
    """Resolve project root from env or git."""
    env_dir = os.environ.get("CLAUDE_PROJECT_DIR")
    if env_dir:
        return Path(env_dir)
    current = Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    return None


def has_retro_today(retro_dir: Path, today: str) -> bool:
    """Check if a retrospective already exists for today."""
    if not retro_dir.is_dir():
        return False
    return any(retro_dir.glob(f"{today}*.md"))


def is_trivial_session(project_dir: Path) -> bool:
    """Check if session is trivial (no meaningful work done)."""
    sessions_dir = project_dir / ".agents" / "sessions"
    if not sessions_dir.is_dir():
        return True

    today = datetime.now().strftime("%Y-%m-%d")
    session_files = sorted(
        sessions_dir.glob(f"{today}-session-*.json"),
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )

    if not session_files:
        return True

    try:
        content = session_files[0].read_text(encoding="utf-8")
        data = json.loads(content)
        # Trivial if no work items or outcomes recorded
        work = data.get("work", [])
        outcomes = data.get("outcomes", [])
        return len(work) == 0 and len(outcomes) == 0
    except (json.JSONDecodeError, OSError, KeyError):
        return True


def generate_retrospective(project_dir: Path, today: str) -> Path | None:
    """Generate a structured retrospective file."""
    retro_dir = project_dir / ".agents" / "retrospective"
    retro_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{today}-auto-retro.md"
    retro_path = retro_dir / filename

    # Try to pull context from today's session log
    session_context = ""
    sessions_dir = project_dir / ".agents" / "sessions"
    if sessions_dir.is_dir():
        session_files = sorted(
            sessions_dir.glob(f"{today}-session-*.json"),
            key=lambda f: f.stat().st_mtime,
            reverse=True,
        )
        if session_files:
            try:
                data = json.loads(session_files[0].read_text(encoding="utf-8"))
                work_items = data.get("work", [])
                outcomes = data.get("outcomes", [])
                if work_items:
                    session_context += "### Work Items\n"
                    for item in work_items[:10]:
                        if isinstance(item, str):
                            session_context += f"- {item}\n"
                        elif isinstance(item, dict):
                            session_context += f"- {item.get('description', item.get('task', str(item)))}\n"
                if outcomes:
                    session_context += "\n### Outcomes\n"
                    for outcome in outcomes[:10]:
                        if isinstance(outcome, str):
                            session_context += f"- {outcome}\n"
                        elif isinstance(outcome, dict):
                            session_context += f"- {outcome.get('result', str(outcome))}\n"
            except (json.JSONDecodeError, OSError):
                pass

    content = f"""# Retrospective — {today}

> Auto-generated by invoke_auto_retrospective.py (Stop hook)

## Session Context

{session_context if session_context else "_No session log data available._"}

## What Went Well

- _[To be filled by reviewing agent or human]_

## What Could Improve

- _[To be filled by reviewing agent or human]_

## Key Learnings

- _[To be filled by reviewing agent or human]_

## Failure Patterns

- _[To be filled — check against known patterns in .agents/failure-modes/]_
"""

    retro_path.write_text(content, encoding="utf-8")
    return retro_path


def update_retro_index(project_dir: Path, today: str, filename: str) -> None:
    """Append entry to docs/retros/INDEX.md, creating if needed."""
    index_dir = project_dir / "docs" / "retros"
    index_dir.mkdir(parents=True, exist_ok=True)
    index_path = index_dir / "INDEX.md"

    header = "# Retrospective Index\n\n| Date | File | Summary |\n|------|------|---------|"

    if not index_path.exists():
        index_path.write_text(header + "\n", encoding="utf-8")

    # Append new row
    row = f"| {today} | {filename} | Auto-generated session retro |"
    with open(index_path, "a", encoding="utf-8") as f:
        f.write(row + "\n")


def main() -> int:
    """Generate retrospective on session stop."""
    # Bypass
    if os.environ.get("SKIP_AUTO_RETRO", "").lower() == "true":
        return 0

    # Skip if stdin is TTY
    if sys.stdin.isatty():
        return 0

    # Read stdin (consume it)
    try:
        sys.stdin.read()
    except Exception:
        pass

    project_dir = get_project_directory()
    if not project_dir:
        return 0

    today = datetime.now().strftime("%Y-%m-%d")
    retro_dir = project_dir / ".agents" / "retrospective"

    # Idempotent: skip if retro already exists today
    if has_retro_today(retro_dir, today):
        return 0

    # Skip trivial sessions
    if is_trivial_session(project_dir):
        return 0

    try:
        retro_path = generate_retrospective(project_dir, today)
        if retro_path:
            update_retro_index(project_dir, today, retro_path.name)
    except OSError:
        pass  # Fail-open

    return 0


if __name__ == "__main__":
    sys.exit(main())
