"""Which recovery events a workflow actually subscribes to.

Issue #4835. A bulk cancellation of PR workflow runs is only safe when every
required context it kills can be regenerated. "Close and reopen the PR" is the
cheapest recovery, and on 2026-08-09 it did not work: several active workflows
declared an explicit ``pull_request.types`` list that omitted ``reopened``, so
reopening produced no run for them and the required contexts stayed missing.
Issue #4827 fixed those particular workflows. This module makes the class of
mistake detectable instead of relying on nobody re-introducing it.

The parsing contract, from GitHub's workflow syntax documentation
(https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows):

- ``on: pull_request`` with no ``types`` defaults to
  ``[opened, synchronize, reopened]``. That default is what
  :data:`DEFAULT_PULL_REQUEST_TYPES` records.
- ``pull_request_target`` carries the same default type list and the same
  trigger semantics for our purpose (it produces check runs on the PR), so its
  types are unioned into the same set.
- ``on:`` accepts three shapes: a bare string (``on: push``), a list
  (``on: [push, pull_request]``), and a mapping (``on: {pull_request: {...}}``).
  All three are handled.

One YAML trap is load-bearing here. ``on`` is a YAML 1.1 boolean literal, so
``yaml.safe_load`` parses the key ``on:`` as Python ``True``, not the string
``"on"``. A parser that reads only ``document["on"]`` sees no triggers at all
and would report every workflow as subscribing to nothing, which fails open in
the direction that matters: a workflow with no recorded subscription must never
be treated as recoverable.

A workflow ``name:`` is the identifier a run record carries, and GitHub does not
require it to be unique across files. Two files may declare the same name, so a
name resolves to a *set* of workflow files, not to one. Every event answered for
such a name is therefore the intersection across that set: only an event every
sharer subscribes to can regenerate the run, because the name alone does not say
which file produced it. See :func:`load_workflow_subscriptions`.

The workflow file is also the only place a *queued* run's published contexts can
be read. The Actions jobs endpoint lists job records GitHub has already
materialized, and a job gated behind ``needs:`` has none until its dependency
finishes, so the endpoint answers "no contexts" for a run that will publish
several. Measured on this repository's ``.github/workflows`` corpus: of the nine
contexts in ``scripts/ci/ruleset_required_contexts.py``, seven resolve to jobs
that declare ``needs:`` (``Analyze (actions)`` and ``Analyze (python)`` from the
matrix job in ``codeql-analysis.yml``, ``Run Python Tests`` from ``pytest.yml``,
plus ``Validate Generated Files``, ``Validate Path Normalization``,
``Validate Plugin Version Bump``, and ``Validate Spec Coverage``); only
``Validate PR`` and ``Validate PR title`` are ungated. So :attr:`
WorkflowSubscriptions.job_names` records the statically declared job identities
and :func:`declared_required_contexts` answers what a run under this workflow
could publish regardless of what the API has materialized.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

__all__ = [
    "DEFAULT_PULL_REQUEST_TYPES",
    "PULL_REQUEST_RECOVERY_EVENTS",
    "RECOVERY_EVENTS",
    "WorkflowSubscriptions",
    "declared_required_contexts",
    "load_workflow_subscriptions",
    "parse_workflow_subscriptions",
    "pin_to_head_ref",
    "subscribes_to",
]

# GitHub's documented default activity types for pull_request and
# pull_request_target when the workflow declares no explicit `types` list.
DEFAULT_PULL_REQUEST_TYPES: frozenset[str] = frozenset(
    {"opened", "synchronize", "reopened"}
)

# The recovery events a cancelled required context may be regenerated by.
# `rerun` re-executes the cancelled run itself through the Actions API and
# therefore needs no trigger subscription; the other three do.
#
# `rerun` is not unconditionally available. GitHub refuses to re-run a workflow
# run older than 30 days, and a run whose workflow file was deleted or renamed
# on the head commit cannot be re-run either. Two things carry that weight
# instead of a subscription check: `plan_recovery` blocks any run whose workflow
# definition does not resolve in the loaded corpus (a deleted or renamed file
# resolves to nothing), and every manifest entry records the `run_id`, which is
# the handle the operator needs to issue the re-run. The manifest also records
# `verification: "rerun"` so a reader can tell a subscription that was checked
# from one that was skipped.
RECOVERY_EVENTS: frozenset[str] = frozenset(
    {"synchronize", "reopened", "workflow_dispatch", "rerun"}
)

# The subset of RECOVERY_EVENTS that GitHub delivers through the
# pull_request-family triggers, and therefore the only ones whose regeneration
# is subject to those triggers' `paths`/`paths-ignore` filters.
#
# `workflow_dispatch` fires its own trigger, which has no path filters at all,
# and `rerun` re-executes an existing run through the Actions API without
# evaluating any trigger. Applying a `pull_request: paths:` filter to either
# rejects a recovery mode that filter cannot affect: measured on this
# repository's corpus, 6 workflow files declare `paths` on `pull_request`, so
# scoping this correctly is the difference between two usable recovery modes
# and none for those workflows.
PULL_REQUEST_RECOVERY_EVENTS: frozenset[str] = frozenset({"synchronize", "reopened"})

_PULL_REQUEST_TRIGGERS = ("pull_request", "pull_request_target")

# Keys inside a pull_request-family trigger config that can suppress the run
# entirely for a given change. `branches` and `branches-ignore` are deliberately
# absent: they filter on the pull request's *base* ref, which does not move when
# a PR is closed and reopened or resynchronized, so a run that exists at all
# already satisfies them. Including them would block essentially every batch:
# 33 of this repository's workflow files declare `branches:` on `pull_request`
# and one more on `pull_request_target`, against 6 that declare `paths`.
_PATH_FILTER_KEYS = ("paths", "paths-ignore")

# GitHub Actions expression marker. A job `name:` containing one is expanded at
# run time (matrix fan-out), so only the literal text before it is knowable
# statically.
_EXPRESSION_MARKER = "${{"


@dataclass(frozen=True, slots=True)
class WorkflowSubscriptions:
    """The events a workflow subscribes to.

    One instance describes one workflow file, except for the record
    :func:`load_workflow_subscriptions` files under a ``name:`` that several
    files declare. That record describes the whole set and holds only what every
    file in it subscribes to.

    Attributes:
        name: The workflow's ``name:`` value, or its filename when unnamed.
        pull_request_types: Activity types unioned across ``pull_request`` and
            ``pull_request_target``. Empty when the workflow declares neither.
        has_workflow_dispatch: True when the workflow declares
            ``workflow_dispatch``, which is what makes a manual re-run possible.
        job_names: Every job's check-run name, taken from its ``name:`` when it
            declares one and from its job id otherwise. Branch protection
            matches a required context against exactly this string, so these are
            the contexts a run of this workflow can publish.
        job_name_prefixes: The literal text before ``${{`` for each job whose
            name is an expression (a matrix fan-out such as
            ``Analyze (${{ matrix.language }})``). A required context that
            starts with one of these could be published by that job. A name that
            is *entirely* an expression contributes the empty string, which
            matches every context: nothing about it is knowable statically, so
            it fails closed rather than silently publishing nothing.
        has_path_filters: True when any pull_request-family trigger declares
            ``paths`` or ``paths-ignore``. Such a workflow produces a run only
            for changes touching those paths, so naming a recovery event does
            not promise the run comes back.
    """

    name: str
    pull_request_types: frozenset[str]
    has_workflow_dispatch: bool
    job_names: frozenset[str] = frozenset()
    job_name_prefixes: frozenset[str] = frozenset()
    has_path_filters: bool = False


def _trigger_mapping(document: Mapping[Any, Any]) -> dict[str, Any]:
    """Return the ``on:`` block as a mapping of trigger name to its config.

    Reads both the ``True`` key (YAML 1.1 boolean coercion of ``on:``) and the
    literal ``"on"`` key, so a document loaded by a parser that preserved the
    string still resolves. Returns an empty mapping when the workflow declares
    no triggers at all.

    Iterating rather than indexing is deliberate: the document's key type is
    heterogeneous exactly because of that coercion, so ``document[True]`` is not
    expressible against a ``Mapping[str, Any]`` without lying about the type.
    """
    raw: Any = None
    for key, value in document.items():
        if key is True or key == "on":
            raw = value
            break

    if raw is None:
        return {}
    if isinstance(raw, str):
        return {raw: None}
    if isinstance(raw, list):
        return {item: None for item in raw if isinstance(item, str)}
    if isinstance(raw, Mapping):
        return {str(key): value for key, value in raw.items()}
    return {}


def _declared_types(config: object) -> frozenset[str]:
    """Activity types for one pull_request-family trigger config."""
    if not isinstance(config, Mapping):
        # `pull_request:` with a null or scalar body means "default types".
        return DEFAULT_PULL_REQUEST_TYPES
    if "types" not in config:
        return DEFAULT_PULL_REQUEST_TYPES
    types = config["types"]
    if isinstance(types, str):
        return frozenset({types})
    if isinstance(types, Iterable):
        return frozenset(str(item) for item in types)
    # An explicit but unusable `types:` value is not a default; treat it as no
    # subscription so the guard fails closed rather than assuming `reopened`.
    return frozenset()


def _declares_path_filter(config: object) -> bool:
    """True when one pull_request-family trigger config narrows by path."""
    if not isinstance(config, Mapping):
        return False
    return any(key in config for key in _PATH_FILTER_KEYS)


def _job_identities(document: Mapping[Any, Any]) -> tuple[frozenset[str], frozenset[str]]:
    """Split a workflow's declared job names into literals and matrix prefixes.

    A check run is named by the job's ``name:`` when it declares one and by the
    job id otherwise, which is the string branch protection matches a required
    context against. A name carrying a ``${{`` expression is only knowable up to
    its literal prefix, so it is returned separately for prefix matching.
    """
    jobs = document.get("jobs")
    if not isinstance(jobs, Mapping):
        return frozenset(), frozenset()

    literals: set[str] = set()
    prefixes: set[str] = set()
    for job_id, body in jobs.items():
        declared = body.get("name") if isinstance(body, Mapping) else None
        label = declared if isinstance(declared, str) and declared else str(job_id)
        marker = label.find(_EXPRESSION_MARKER)
        if marker == -1:
            literals.add(label)
        else:
            prefixes.add(label[:marker])
    return frozenset(literals), frozenset(prefixes)


def parse_workflow_subscriptions(
    document: Mapping[Any, Any], *, fallback_name: str = ""
) -> WorkflowSubscriptions:
    """Extract the event subscriptions from one parsed workflow document.

    Args:
        document: The workflow YAML parsed into a mapping.
        fallback_name: Name to use when the document declares no ``name:``.

    Returns:
        The subscriptions for this workflow. A document with no ``on:`` block
        yields empty types and no dispatch, which blocks every recovery event
        that needs a subscription.
    """
    triggers = _trigger_mapping(document)

    pull_request_types: set[str] = set()
    has_path_filters = False
    for trigger in _PULL_REQUEST_TRIGGERS:
        if trigger not in triggers:
            continue
        config = triggers[trigger]
        pull_request_types |= _declared_types(config)
        has_path_filters = has_path_filters or _declares_path_filter(config)

    declared_name = document.get("name")
    name = declared_name if isinstance(declared_name, str) and declared_name else fallback_name
    job_names, job_name_prefixes = _job_identities(document)

    return WorkflowSubscriptions(
        name=name,
        pull_request_types=frozenset(pull_request_types),
        has_workflow_dispatch="workflow_dispatch" in triggers,
        job_names=job_names,
        job_name_prefixes=job_name_prefixes,
        has_path_filters=has_path_filters,
    )


def declared_required_contexts(
    subscriptions: WorkflowSubscriptions, required: frozenset[str]
) -> frozenset[str]:
    """Required contexts this workflow's job declarations could publish.

    The Actions jobs endpoint is not the authority on what a run publishes: it
    lists only records GitHub has already materialized, and a ``needs:``-gated
    job has none while the run is queued. This reads the workflow file instead,
    so a queued run is scored against every context its workflow declares.

    Matching is exact against :attr:`WorkflowSubscriptions.job_names` and by
    prefix against :attr:`WorkflowSubscriptions.job_name_prefixes`. Prefix
    matching is confined to the expression-bearing names on purpose: applying it
    to literal names would let a job called ``Validate PR`` claim
    ``Validate PR title``, inflating every manifest with contexts the workflow
    cannot publish.
    """
    matched = {context for context in required if context in subscriptions.job_names}
    matched.update(
        context
        for context in required
        for prefix in subscriptions.job_name_prefixes
        if context.startswith(prefix)
    )
    return frozenset(matched)


def subscribes_to(subscriptions: WorkflowSubscriptions, event: str) -> bool:
    """True when this workflow can be regenerated by ``event``.

    ``rerun`` is always true here: re-running a workflow run re-executes it
    through the Actions API regardless of which triggers the workflow declares.
    It is not therefore a free pass, and this function is not the whole check.
    See the :data:`RECOVERY_EVENTS` comment for what carries the weight instead:
    the caller blocks a run whose workflow definition does not resolve, and the
    manifest records ``verification`` so a skipped subscription check is
    auditable rather than indistinguishable from a passed one.

    ``workflow_dispatch`` needs the trigger declared. Everything else is looked
    up in the pull_request activity types, so an unknown event name is false.
    """
    if event == "rerun":
        return True
    if event == "workflow_dispatch":
        return subscriptions.has_workflow_dispatch
    return event in subscriptions.pull_request_types


def pin_to_head_ref(
    head: WorkflowSubscriptions, base: WorkflowSubscriptions | None
) -> WorkflowSubscriptions:
    """Combine a pull request's own workflow definition with the base branch's.

    ``head`` is the definition parsed from the ref GitHub will evaluate for the
    pull request (its merge ref), and ``base`` is the same workflow as the base
    branch declares it, or None when the base corpus has no file at that path.

    The three fields answer three different questions, so they combine three
    different ways:

    - ``pull_request_types`` comes from ``head`` alone. GitHub evaluates the
      merge commit's workflow file for pull_request-family events, so a pull
      request that adds ``reopened`` really does get ``reopened`` on reopen and
      one that drops it really does not. Reading the base branch here is what
      let a pull request whose own workflow omits ``reopened`` verify against a
      healthy checkout and be cancelled with no recovery path.
    - ``has_workflow_dispatch`` needs both. GitHub lists a workflow for manual
      dispatch only when it exists with that trigger on the repository's
      default branch, so a pull request that adds ``workflow_dispatch`` cannot
      be dispatched until it merges. Absent ``base``, this is False.
    - ``job_names``, ``job_name_prefixes``, and ``has_path_filters`` take the
      union, the same polarity :func:`_narrow_to_shared` uses: a context either
      definition publishes is a context the cancellation might remove, and a
      path filter on either side means the run might not regenerate.
    """
    if base is None:
        return WorkflowSubscriptions(
            name=head.name,
            pull_request_types=head.pull_request_types,
            has_workflow_dispatch=False,
            job_names=head.job_names,
            job_name_prefixes=head.job_name_prefixes,
            has_path_filters=head.has_path_filters,
        )
    return WorkflowSubscriptions(
        name=head.name,
        pull_request_types=head.pull_request_types,
        has_workflow_dispatch=(
            head.has_workflow_dispatch and base.has_workflow_dispatch
        ),
        job_names=head.job_names | base.job_names,
        job_name_prefixes=head.job_name_prefixes | base.job_name_prefixes,
        has_path_filters=head.has_path_filters or base.has_path_filters,
    )


def _narrow_to_shared(
    first: WorkflowSubscriptions, second: WorkflowSubscriptions
) -> WorkflowSubscriptions:
    """Keep only the subscriptions two same-named workflow files share.

    Intersection is the fail-closed reading of an ambiguous name. A run record
    names its workflow, not its file, so when two files answer to that name the
    caller cannot tell which one produced the run. An event only one of them
    declares regenerates only one of them, so promising it would be the same
    fail-open mistake issue #4835 exists to prevent, one level up: the guard
    would report a verified recovery path for a run whose real workflow has
    none.

    The three fields below narrow in the opposite direction, and that is the
    same rule applied to a question whose polarity is reversed. Subscriptions
    answer "can this come back", where the smaller claim is the safer one.
    Job names and path filters answer "what is at stake", where the larger claim
    is the safer one: a context either file publishes is a context the
    cancellation might remove, and a path filter on either file means the run
    might not regenerate. So both take the union, and the dispatch flag, being a
    subscription, keeps the intersection.
    """
    return WorkflowSubscriptions(
        name=first.name,
        pull_request_types=first.pull_request_types & second.pull_request_types,
        has_workflow_dispatch=(
            first.has_workflow_dispatch and second.has_workflow_dispatch
        ),
        job_names=first.job_names | second.job_names,
        job_name_prefixes=first.job_name_prefixes | second.job_name_prefixes,
        has_path_filters=first.has_path_filters or second.has_path_filters,
    )


def load_workflow_subscriptions(
    workflows_dir: Path,
) -> dict[str, WorkflowSubscriptions]:
    """Parse every workflow file in a directory, keyed by workflow name.

    Both the workflow's ``name:`` and its filename are registered as keys, so a
    caller holding either identifier resolves. A file that fails to parse is
    skipped rather than raising: one malformed workflow must not prevent the
    guard from reporting on the rest, and an absent entry already fails closed.

    Every key that two or more workflow files can answer to is narrowed by
    :func:`_narrow_to_shared` to what all of its claimants share. Two files
    claim one key in two ways, and both must narrow:

    - Two files declaring the same ``name:``.
    - One file's declared ``name:`` equal to another file's filename. A run
      record supplies the declared name, so a lookup of ``"release.yml"``
      cannot tell the file named ``release.yml`` from the file that declares
      ``name: release.yml``. Keeping only the filename record (the previous
      ``setdefault`` behavior) drops the other claimant and can verify a
      recovery event the run's real workflow does not subscribe to.

    Narrowing a record with itself is a no-op (intersection with self is self,
    union with self is self), so a file whose ``name:`` equals its own filename
    is unaffected.
    """
    subscriptions: dict[str, WorkflowSubscriptions] = {}
    by_declared_name: dict[str, WorkflowSubscriptions] = {}
    if not workflows_dir.is_dir():
        return subscriptions

    for path in sorted(workflows_dir.iterdir()):
        if path.suffix not in (".yml", ".yaml") or not path.is_file():
            continue
        try:
            document = yaml.safe_load(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, yaml.YAMLError):
            continue
        if not isinstance(document, Mapping):
            continue
        parsed = parse_workflow_subscriptions(document, fallback_name=path.name)
        subscriptions[path.name] = parsed
        if parsed.name:
            already = by_declared_name.get(parsed.name)
            by_declared_name[parsed.name] = (
                parsed if already is None else _narrow_to_shared(already, parsed)
            )

    for name, merged in by_declared_name.items():
        existing = subscriptions.get(name)
        subscriptions[name] = (
            merged if existing is None else _narrow_to_shared(existing, merged)
        )
    return subscriptions
