<#
.SYNOPSIS
    Validates skill files follow the atomic format and naming convention.

.DESCRIPTION
    Enforces ADR-017 skill format requirements:
    - One skill per file (no bundled skills)
    - Files with `## Skill-` headers are flagged as bundled format
    - Files must NOT use 'skill-' prefix (use {domain}-{description} format)

    This validation runs on staged .serena/memories/ files during pre-commit.

.PARAMETER Path
    Path to the memories directory. Defaults to .serena/memories/.

.PARAMETER CI
    Run in CI mode (stricter output, exit codes).

.PARAMETER StagedOnly
    Only check staged files (for pre-commit hook).

.PARAMETER ChangedFiles
    Array of file paths to check (for CI workflow). When specified, only these files are validated.

.EXAMPLE
    pwsh scripts/Validate-SkillFormat.ps1

.EXAMPLE
    pwsh scripts/Validate-SkillFormat.ps1 -StagedOnly

.EXAMPLE
    pwsh scripts/Validate-SkillFormat.ps1 -CI -ChangedFiles @('.serena/memories/pr-001.md', '.serena/memories/qa-002.md')

.NOTES
  EXIT CODES:
  0  - Success: All skill files follow atomic format and naming convention
  1  - Error: Bundled format or naming violations detected (always when -CI flag is set)

  See: ADR-035 Exit Code Standardization
  Related: ADR-017, Issue #307
#>
[CmdletBinding()]
param(
    [string]$Path = ".serena/memories",
    [switch]$CI,
    [switch]$StagedOnly,
    [string[]]$ChangedFiles = @()
)

$ErrorActionPreference = 'Stop'
$script:ExitCode = 0
$script:BundledFiles = @()
$script:PrefixViolations = @()

# Get files to check
if ($ChangedFiles.Count -gt 0) {
    # Use explicitly passed files (from CI workflow)
    # Exclude index files (skills-*-index.md and memory-index.md) as they don't contain skill content
    $memoryFiles = $ChangedFiles |
        Where-Object { $_ -match '^\.serena/memories/.*\.md$' -and $_ -notmatch 'skills-.*-index\.md$' }

    if (-not $memoryFiles) {
        Write-Host "No skill files in changed files list. Skipping format validation." -ForegroundColor Gray
        exit 0
    }

    # Filter to existing files only (deleted files don't need validation)
    # Use -ErrorAction SilentlyContinue to skip deleted/renamed files
    $filesToCheck = $memoryFiles | ForEach-Object { Get-Item $_ -ErrorAction SilentlyContinue }
} elseif ($StagedOnly) {
    # Get staged memory files from git
    $stagedFiles = git diff --cached --name-only --diff-filter=ACMR 2>$null |
        Where-Object { $_ -match '^\.serena/memories/.*\.md$' -and $_ -notmatch 'skills-.*-index\.md$' }

    if (-not $stagedFiles) {
        Write-Host "No skill files staged. Skipping format validation." -ForegroundColor Gray
        exit 0
    }

    $filesToCheck = $stagedFiles | ForEach-Object { Get-Item $_ -ErrorAction SilentlyContinue }
} else {
    # Check all skill files (exclude index files)
    $filesToCheck = Get-ChildItem -Path $Path -Filter "*.md" -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -notmatch '^skills-.*-index\.md$' -and $_.Name -ne 'memory-index.md' }
}

if (-not $filesToCheck) {
    Write-Host "No skill files found to validate." -ForegroundColor Gray
    exit 0
}

Write-Host "Validating skill format (ADR-017: one skill per file)..." -ForegroundColor Cyan

foreach ($file in $filesToCheck) {
    $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }

    # Count skill headers (## Skill-*-NNN:)
    $skillHeaders = [regex]::Matches($content, '(?m)^## Skill-[A-Za-z]+-[0-9]+:')

    if ($skillHeaders.Count -gt 1) {
        # Bundled format detected
        Write-Host "  BUNDLED: $($file.Name) contains $($skillHeaders.Count) skills" -ForegroundColor Yellow
        $script:BundledFiles += @{
            File = $file.Name
            Count = $skillHeaders.Count
        }
        $script:ExitCode = 1
    }

    # Check for invalid 'skill-' prefix (ADR-017 requires {domain}-{description} format)
    # Exception: *-observations.md files are generated by skill learning hook
    if ($file.Name -match '^skill-' -and $file.Name -notmatch '-observations\.md$') {
        Write-Warning "  PREFIX: $($file.Name) uses invalid 'skill-' prefix"
        $script:PrefixViolations += $file.Name
        $script:ExitCode = 1
    }
}

# Summary
Write-Host ""

$hasIssues = $false

if ($script:BundledFiles.Count -gt 0) {
    $hasIssues = $true
    Write-Host "=== Bundled Format Detected ===" -ForegroundColor Yellow
    Write-Host "The following files contain multiple skills:" -ForegroundColor Yellow
    $script:BundledFiles | ForEach-Object {
        Write-Host "  - $($_.File): $($_.Count) skills" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "ADR-017 requires ONE skill per file. No exceptions." -ForegroundColor Red
    Write-Host "Split bundled skills into separate atomic files." -ForegroundColor Red
    Write-Host ""
}

if ($script:PrefixViolations.Count -gt 0) {
    $hasIssues = $true
    Write-Warning "=== Invalid Naming Convention ==="
    Write-Warning "The following files use the deprecated 'skill-' prefix:"
    $script:PrefixViolations | ForEach-Object {
        Write-Warning "  - $_"
    }
    Write-Host ""
    Write-Host "ADR-017 requires {domain}-{description} naming (no 'skill-' prefix)." -ForegroundColor Red
    Write-Host "Rename files to use domain prefix (e.g., pr-001-reviewer-enumeration.md)." -ForegroundColor Red
    Write-Host ""
}

if ($hasIssues) {
    if ($CI) {
        Write-Host "Result: FAILED" -ForegroundColor Red
        exit 1
    } else {
        Write-Warning "Result: WARNING (non-blocking for local development)"
        exit 0
    }
} else {
    Write-Host "Result: PASSED - All skill files follow atomic format and naming convention" -ForegroundColor Green
    exit 0
}
