from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(Write|Edit)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Write|Edit)$'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _json.loads(raw_value)
        except ValueError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_tool_input_from_tool_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolArgs")


def _shim_candidate_payloads(payload):
    tool_calls = payload.get("toolCalls")
    if isinstance(tool_calls, list):
        candidates = []
        for call in tool_calls:
            if not isinstance(call, dict):
                continue
            name = call.get("name")
            if not isinstance(name, str):
                continue
            candidate = dict(payload)
            candidate.pop("toolCalls", None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            candidates.append(candidate)
        return candidates
    return [payload]


def _shim_match_candidate(payload, kind, params):
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        tool_args = _shim_tool_input_from_tool_args(tool_args)
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_select_payload(payload):
    kind, params = _shim_classify(_MATCHER)
    candidates = _shim_candidate_payloads(payload)
    if not candidates:
        return None
    for candidate in candidates:
        if _shim_match_candidate(candidate, kind, params):
            return candidate
    return None


def _shim_should_fire(payload):
    return _shim_select_payload(payload) is not None


def _shim_replay_bytes(payload, raw):
    selected = _shim_select_payload(payload)
    if selected is None:
        return raw
    replay = dict(selected)
    changed = selected is not payload
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        replay["tool_input"] = _shim_tool_input_from_tool_args(replay.get("toolArgs"))
        changed = True
    if not changed:
        return raw
    if payload.get("tool_name") is not None:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Persist plan/TODO state after Write/Edit operations.

    Claude Code PostToolUse hook that saves lightweight checkpoints when
    session logs or plan/TODO files are written. This provides compaction-resume
    context without duplicating full file content.

    Addresses continuation reset after context compaction where plan position
    and TODO status are lost.

    Triggers on:
    - Session log writes (.agents/sessions/*.json)
    - Plan/TODO file writes (TODO.md, PLAN.md, .agents/plan*.md)

    Hook Type: PostToolUse
    Exit Codes:
        0 = Skipped or checkpoint written
        2 = Block on malformed hook input or checkpoint failure

    References:
        - Issue #1703 (lifecycle hook infrastructure)
        - Issue #1691 (anti-drift protocol)
        - ADR-008 (protocol automation)
    """


    import json
    import os
    import re
    import sys
    from datetime import UTC, datetime
    from pathlib import Path
    from typing import cast

    # --- Standard hook boilerplate ---
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = os.path.join(_plugin_root, "lib")
    else:
        _lib_dir = str(Path(__file__).resolve().parents[2] / "lib")
    if os.path.isdir(_lib_dir) and _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    try:
        from hook_utilities import get_project_directory
        from hook_utilities.guards import skip_if_consumer_repo
    except ImportError:

        def get_project_directory() -> str:
            env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
            if env_dir:
                return str(Path(env_dir).resolve())
            return str(Path.cwd())

        def skip_if_consumer_repo(hook_name: str) -> bool:
            agents_path = Path(get_project_directory()) / ".agents"
            if not agents_path.is_dir():
                print(f"[SKIP] {hook_name}: .agents/ not found (consumer repo)", file=sys.stderr)
                return True
            return False


    HOOK_NAME = "plan-state-sync"

    # Patterns for files we want to checkpoint
    # All patterns use (?:^|/) anchors to ensure we match only project-relative
    # paths starting with .agents/, not arbitrary paths containing that substring
    # (e.g., "mock.agents/sessions/log.json" should not match).
    SESSION_LOG_PATTERN = re.compile(r"(?:^|/)\.agents/sessions/.*\.json$")
    PLAN_FILE_PATTERNS = [
        re.compile(r"(?:^|/)TODO\.md$", re.IGNORECASE),
        re.compile(r"(?:^|/)PLAN\.md$", re.IGNORECASE),
        # Match `.agents/plan*.md` at the .agents/ root only. Earlier pattern
        # `\.agents/plan.*\.md$` also matched `.agents/planning/.../*.md` and
        # other nested files, triggering checkpoints for unrelated planning
        # docs. `[^/]*` keeps the match scoped to a single path segment.
        re.compile(r"(?:^|/)\.agents/plan[^/]*\.md$", re.IGNORECASE),
        re.compile(r"(?:^|/)PROJECT-PLAN\.md$", re.IGNORECASE),
    ]

    SUMMARY_MAX_CHARS = 500


    def _read_stdin_raw() -> str | None:
        """Drain stdin (harness drain contract) without parsing."""
        if sys.stdin.isatty():
            return None
        data = sys.stdin.read().strip()
        return data or None


    def _parse_hook_input(data: str) -> dict[str, object]:
        """Parse drained stdin into the hook input object (raises on bad shape)."""
        parsed: object = json.loads(data)
        if not isinstance(parsed, dict):
            raise ValueError("hook input JSON must be an object")
        # json.loads object keys are always str, so this cast is sound.
        return cast("dict[str, object]", parsed)


    def _extract_file_path(hook_input: dict[str, object]) -> str | None:
        """Extract the file path from hook input.

        Defends against malformed hook input where ``hook_input`` or
        ``tool_input`` is not a mapping, and against non-string ``file_path``
        values that would later break string ops in ``_is_checkpointable_file``.
        Returning ``None`` lets the caller skip checkpointing without
        disabling the hook silently.
        """
        if not isinstance(hook_input, dict):
            return None
        tool_input = hook_input.get("tool_input", {})
        if not isinstance(tool_input, dict):
            return None
        # Write tool uses 'file_path', Edit tool may use 'file_path' or 'path'.
        # Require a non-empty string; ignore other types so downstream code
        # never operates on, e.g., a dict or None.
        for key in ("file_path", "path"):
            value = tool_input.get(key)
            if isinstance(value, str):
                stripped = value.strip()
                if stripped:
                    return stripped
        return None


    def _is_checkpointable_file(file_path: str) -> bool:
        """Check if the written file should trigger a checkpoint."""
        # Normalize path separators
        normalized = file_path.replace("\\", "/")

        if SESSION_LOG_PATTERN.search(normalized):
            return True

        for pattern in PLAN_FILE_PATTERNS:
            if pattern.search(normalized):
                return True

        return False


    def _read_file_summary(file_path: str) -> str:
        """Read first SUMMARY_MAX_CHARS of a file as a summary.

        Streams only the bytes needed instead of loading the whole file, so
        large session logs do not balloon hook memory.
        """
        try:
            path = Path(file_path)
            if not path.exists():
                return "(file not found)"
            with path.open(encoding="utf-8", errors="replace") as handle:
                content = handle.read(SUMMARY_MAX_CHARS + 1)
            if len(content) > SUMMARY_MAX_CHARS:
                return content[:SUMMARY_MAX_CHARS] + "..."
            return content
        except OSError:
            return "(read error)"


    # Issue #2523: msvcrt.locking() locks a byte RANGE from the current file
    # position, unlike fcntl.flock() which locks the whole file. The previous
    # 1-byte lock at an arbitrary position was decorative: concurrent sessions
    # could still interleave writes. Lock a fixed region anchored at offset 0
    # instead; both lock and unlock must use the same anchor and length.
    # 0x7FFFFFFF is the max positive signed 32-bit int, the largest range
    # msvcrt.locking accepts portably.
    _NT_LOCK_BYTES = 0x7FFFFFFF


    def _acquire_lock(handle) -> None:
        """Acquire an advisory exclusive lock on an open file handle."""
        if sys.platform == "win32":  # pragma: no cover - platform branch
            import msvcrt

            pos = handle.tell()
            handle.seek(0)
            try:
                msvcrt.locking(handle.fileno(), msvcrt.LK_LOCK, _NT_LOCK_BYTES)
            finally:
                handle.seek(pos)
            return
        import fcntl

        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)


    def _release_lock(handle) -> None:
        """Release the advisory lock held on an open file handle."""
        if sys.platform == "win32":  # pragma: no cover - platform branch
            import msvcrt

            pos = handle.tell()
            handle.seek(0)
            try:
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, _NT_LOCK_BYTES)
            except OSError:
                pass
            finally:
                handle.seek(pos)
            return
        import fcntl

        try:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        except OSError:
            pass


    def _write_checkpoint(project_dir: str, file_path: str, summary: str) -> None:
        """Write a lightweight checkpoint for plan/state recovery.

        Concurrent PostToolUse hooks can race on the per-day checkpoint file, so
        the read-modify-write sequence is wrapped in an advisory exclusive lock
        (fcntl.flock on POSIX, msvcrt.locking on Windows). Without the lock,
        interleaved writes drop entries or produce invalid JSON.
        """
        checkpoint_dir = Path(project_dir) / ".agents" / ".hook-state"
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
        timestamp = datetime.now(tz=UTC).isoformat()

        checkpoint_file = checkpoint_dir / f"plan-checkpoint-{today}.json"

        # Open r+ when present, w+ to create; serialize via OS advisory lock.
        mode = "r+" if checkpoint_file.exists() else "w+"
        with checkpoint_file.open(mode, encoding="utf-8") as handle:
            _acquire_lock(handle)
            try:
                checkpoints: list[dict[str, object]] = []
                handle.seek(0)
                raw = handle.read()
                if raw:
                    try:
                        existing = json.loads(raw)
                        if isinstance(existing, list):
                            checkpoints = existing
                    except json.JSONDecodeError:
                        # Preserve the corrupt file under .corrupt so prior
                        # checkpoints are not silently wiped when the daily
                        # JSON cannot be parsed. The new write proceeds with
                        # an empty list so the hook still records progress.
                        corrupt_path = checkpoint_file.with_suffix(
                            checkpoint_file.suffix + ".corrupt"
                        )
                        try:
                            corrupt_path.write_text(raw, encoding="utf-8")
                        except OSError:
                            pass

                checkpoints.append({
                    "file": file_path,
                    "timestamp": timestamp,
                    "summary": summary,
                })

                # Keep only last 20 checkpoints to avoid unbounded growth
                if len(checkpoints) > 20:
                    checkpoints = checkpoints[-20:]

                handle.seek(0)
                handle.truncate()
                handle.write(
                    json.dumps(checkpoints, indent=2, ensure_ascii=False)
                )
                handle.flush()
            finally:
                _release_lock(handle)


    def main() -> None:
        """Checkpoint plan/TODO state after relevant file writes."""
        # Drain stdin before any early exit (harness drain contract), but defer
        # parsing until after the consumer-repo skip: malformed input in a
        # consumer install must skip (exit 0), not fail closed (exit 2).
        raw_input = _read_stdin_raw()

        if skip_if_consumer_repo(HOOK_NAME):
            sys.exit(0)

        if raw_input is None:
            sys.exit(0)

        hook_input = _parse_hook_input(raw_input)

        file_path = _extract_file_path(hook_input)
        if not file_path:
            sys.exit(0)

        if not _is_checkpointable_file(file_path):
            sys.exit(0)

        project_dir = get_project_directory()
        project_root = Path(project_dir).resolve()

        # Anchor relative paths to the project root so a hook process whose
        # CWD is a subdirectory still resolves to the file Claude wrote, and
        # reject paths that escape the repo (CWE-22 path traversal).
        candidate = Path(file_path)
        resolved = (
            candidate.resolve()
            if candidate.is_absolute()
            else (project_root / candidate).resolve()
        )
        try:
            resolved.relative_to(project_root)
        except ValueError:
            print(
                f"[WARNING] {HOOK_NAME}: ignoring out-of-root path: {file_path}",
                file=sys.stderr,
            )
            sys.exit(0)

        summary = _read_file_summary(str(resolved))

        # Persist a project-relative path so checkpoints stay portable across
        # machines and CWDs, instead of leaking absolute paths from whoever
        # invoked Claude.
        try:
            recorded_path = str(resolved.relative_to(project_root))
        except ValueError:
            recorded_path = file_path

        _write_checkpoint(project_dir, recorded_path, summary)

        print(f"[INFO] {HOOK_NAME}: Checkpointed state for {recorded_path}", file=sys.stderr)
    try:
        return main()
    except Exception as _exc:
        sys.stderr.write('[ERROR] hook error (fail-closed): ' + str(_exc) + '\n')
        return 2

_shim_dispatch()
