from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Read
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Read'

# Bound the standalone shim read before JSON parsing so a malicious or buggy
# upstream cannot cause unbounded allocation (CWE-400).
_HOOK_STDIN_CEILING_BYTES = 64 * 1024 * 1024

# Apply the normal payload policy only after matcher selection. Multi-call
# events can contain a large unrelated call that must not deny a small matched
# call.
_MATCHED_SHIM_PAYLOAD_LIMIT_BYTES = 2 * 1024 * 1024
_MAX_MATCHER_TOOL_CALLS = 256


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match each top-level `|` branch as a separate glob alternative."""
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def _shim_load_json(raw_value):
    return _json.loads(raw_value, object_pairs_hook=_shim_unique_object)


def _shim_parse_json_string(raw_value, field_name):
    if isinstance(raw_value, str):
        stripped = raw_value.lstrip()
        if not stripped or stripped[0] not in "{[\"":
            return raw_value
        try:
            return _shim_load_json(raw_value)
        except _json.JSONDecodeError as exc:
            print(
                "matcher-shim [{}]: {} is not valid JSON: {}".format(
                    _MATCHER, field_name, exc
                ),
                file=_sys.stderr,
            )
            return raw_value
    return raw_value


def _shim_tool_input_from_call_args(raw_args):
    return _shim_parse_json_string(raw_args, "toolCalls.args")


def _shim_validate_tool_name(name, field):
    if not isinstance(name, str) or not name.strip():
        raise ValueError("{} must be a non-empty string".format(field))
    if name != name.strip():
        raise ValueError(
            "{} must not have leading or trailing whitespace".format(field)
        )
    return name


def _shim_json_equal(left, right):
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        return left.keys() == right.keys() and all(
            _shim_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list):
        return len(left) == len(right) and all(
            _shim_json_equal(a, b) for a, b in zip(left, right))
    return left == right


def _shim_alias_value(payload, snake, camel, parser=None):
    fields = [field for field in (snake, camel) if field in payload]
    if not fields:
        return False, None, snake, False
    values = [payload[field] for field in fields]
    if parser is not None:
        values = [parser(value, field) for value, field in zip(values, fields)]
    if len(values) == 2 and not _shim_json_equal(values[0], values[1]):
        raise ValueError(
            "conflicting top-level {}/{} values".format(snake, camel)
        )
    changed = fields != [snake] or values[0] != payload[snake]
    return True, values[0], "/".join(fields), changed


def _shim_top_level_candidate(payload):
    has_name, name, _, name_changed = _shim_alias_value(
        payload, "tool_name", "toolName", _shim_validate_tool_name
    )
    if not has_name:
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    input_payload = payload
    if payload.get("tool_input") is None and "toolArgs" in payload:
        input_payload = {key: value for key, value in payload.items() if key != "tool_input"}
    has_input, tool_input, input_field, input_changed = _shim_alias_value(
        input_payload, "tool_input", "toolArgs", _shim_parse_json_string
    )
    has_call_id, call_id, _, call_id_changed = _shim_alias_value(
        payload, "tool_call_id", "toolCallId"
    )
    if not (name_changed or input_changed or call_id_changed):
        return payload, input_field
    candidate = dict(payload)
    for field in ("toolName", "toolArgs", "toolCallId"):
        candidate.pop(field, None)
    candidate["tool_name"] = name
    if has_input:
        candidate["tool_input"] = tool_input
    if has_call_id:
        candidate["tool_call_id"] = call_id
    return candidate, input_field


def _shim_candidate_payloads(payload):
    if "toolCalls" in payload:
        tool_calls = payload["toolCalls"]
        if not isinstance(tool_calls, list):
            raise ValueError("toolCalls must be a list when present")
        if len(tool_calls) > _MAX_MATCHER_TOOL_CALLS:
            raise ValueError(
                "toolCalls contains {} entries; limit is {}".format(
                    len(tool_calls), _MAX_MATCHER_TOOL_CALLS
                )
            )
        if not tool_calls and (
            "tool_name" in payload or "toolName" in payload
        ):
            raise ValueError(
                "empty toolCalls conflicts with top-level tool_name/toolName"
            )
        for index, call in enumerate(tool_calls):
            if not isinstance(call, dict):
                raise ValueError(
                    "toolCalls[{}] must be an object".format(index)
                )
            _shim_validate_tool_name(
                call.get("name"), "toolCalls[{}].name".format(index)
            )
        for call in tool_calls:
            name = call["name"]
            candidate = dict(payload)
            for field in (
                "toolCalls",
                "tool_name",
                "toolName",
                "tool_input",
                "toolArgs",
                "tool_call_id",
                "toolCallId",
            ):
                candidate.pop(field, None)
            candidate["tool_name"] = name
            candidate["tool_input"] = _shim_tool_input_from_call_args(call.get("args"))
            if "id" in call:
                candidate["tool_call_id"] = call.get("id")
            yield candidate, "toolCalls.args"
        return
    yield _shim_top_level_candidate(payload)


def _shim_match_candidate(payload, kind, params):
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    return tool_name == params["toolName"]


def _shim_select_payloads(payload):
    kind, params = _shim_classify(_MATCHER)
    for candidate, input_field in _shim_candidate_payloads(payload):
        if _shim_match_candidate(candidate, kind, params):
            yield candidate, input_field


def _shim_replay_bytes(payload, selected, raw):
    if selected is payload:
        return raw
    return _json.dumps(selected, separators=(",", ":")).encode("utf-8")


def _shim_exit_code(exc):
    code = exc.code
    if code is None:
        return 0
    if isinstance(code, int):
        return code
    return 1


def _shim_invoke_selection(payload, selection, raw):
    selected, input_field = selection
    replay = _shim_replay_bytes(payload, selected, raw)
    if len(replay) > _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES:
        print(
            (
                "matcher-shim [{}]: matched replay from {} exceeds "
                "{} bytes; refusing"
            ).format(_MATCHER, input_field, _MATCHED_SHIM_PAYLOAD_LIMIT_BYTES),
            file=_sys.stderr,
        )
        return 2
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(replay), encoding="utf-8")
    try:
        rc = _original_main(replay)
    except SystemExit as exc:
        return _shim_exit_code(exc)
    if rc is None:
        return 0
    return int(rc)


def _shim_dispatch_selections(payload):
    try:
        yield from _shim_select_payloads(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)


def _shim_debug_trace(fire):
    if not _os.environ.get("COPILOT_HOOK_DEBUG"):
        return
    kind, _ = _shim_classify(_MATCHER)
    _sys.stderr.write(
        "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
    )


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_HOOK_STDIN_CEILING_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _HOOK_STDIN_CEILING_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _HOOK_STDIN_CEILING_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _shim_load_json(_raw or b"{}")
    except ValueError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    fire = False
    for selection in _shim_dispatch_selections(payload):
        if not fire:
            fire = True
            _shim_debug_trace(fire)
        rc = _shim_invoke_selection(payload, selection, _raw)
        if rc != 0:
            _sys.exit(rc)
    if not fire:
        _shim_debug_trace(fire)
    _sys.exit(0)
# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Track allowed Read operations for the graduated LSP-first gate (ADR-062 Section 4).

    Claude Code PostToolUse hook (matcher ``Read``). When the Read guard allows a Read
    operation (exit 0), this tracker records the file path via ``record_read`` so the
    graduated tiers (soft-allow, soft-warn, hard-block) work correctly. Without this
    tracking, ``read_files`` stays empty and every gated Read is treated as read
    number 1, so the graduated enforcement never kicks in.

    This hook complements the usage tracker (``invoke_lsp_usage_tracker.py``), which
    tracks LSP navigation calls. Together they implement ADR-062 Section 4's
    single-system-of-record for gate state: navigation via ``record_nav``, reads via
    ``record_read``, both in PostToolUse.

    Hook Type: PostToolUse
    Matcher (register in hooks.json): Read
    Exit Codes:
        0 = Always. PostToolUse never blocks.

    Fail-open (mandatory, ADR-062 Section 5): missing lib, malformed JSON, any error
    returns 0 without mutating state. A tracking failure must never block the agent.
    """


    import json
    import os
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    _lib_dir: str | None = None
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(
            f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import get_project_directory  # noqa: E402
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402
    from hook_utilities.lsp_gate_state import is_gated_target, record_read  # noqa: E402
    from hook_utilities.lsp_health import lsp_runtime_down  # noqa: E402
    from hook_utilities.lsp_provider import SYMBOLS_OVERVIEW, detect_providers  # noqa: E402


    def main() -> int:
        """Main hook entry point. Returns exit code (always 0; PostToolUse)."""
        if skip_if_consumer_repo("lsp-read-tracker"):
            return 0

        try:
            if os.environ.get("SKIP_LSP_GATE", "").strip().lower() == "true":
                return 0

            # Symmetric with the PreToolUse guard: when LSP_DOWN is set, reads are
            # allowed without gating, so we must not track them either. Otherwise
            # tier state advances during degraded mode and hard-blocks resume when
            # the LSP recovers (issue #2622).
            if lsp_runtime_down(get_project_directory()):
                return 0

            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)
            if not isinstance(hook_input, dict):
                return 0

            if hook_input.get("tool_name") != "Read":
                return 0

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0

            # file_path (Claude) or path (Copilot CLI view); see #2610.
            file_path = str(tool_input.get("file_path") or tool_input.get("path") or "").strip()
            if not file_path:
                return 0

            project_dir = get_project_directory()

            # Only track reads that the guard would gate (Bug fix: ADR-062 Section 3/4).
            # Non-gated reads (dotfiles, out-of-repo, no provider) must not inflate
            # the read_files count, otherwise tier thresholds trigger early.
            if not is_gated_target(file_path, project_dir):
                print(
                    f"LSP read tracker: non-gated target, not tracked: {file_path}",
                    file=sys.stderr,
                )
                return 0

            providers = detect_providers(file_path, SYMBOLS_OVERVIEW, project_dir)
            if not providers:
                print(
                    f"LSP read tracker: no overview provider, not tracked: {file_path}",
                    file=sys.stderr,
                )
                return 0

            state = record_read(project_dir, file_path)

            print(
                f"LSP read tracked: file={file_path} "
                f"read_count={state.get('read_count')} "
                f"read_files_len={len(state.get('read_files', []))}",
                file=sys.stderr,
            )
            return 0

        except Exception as exc:  # noqa: BLE001 - fail-open is mandatory
            print(
                f"LSP read tracker error: {type(exc).__name__} - {exc}",
                file=sys.stderr,
            )
            return 0
    return main()

_shim_dispatch()
