# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(Write|Edit)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Write|Edit)$'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """
    PostToolUse hook: Persists plan/TODO state after Write/Edit operations.

    Saves lightweight checkpoints when session logs or plan files are modified,
    enabling resume context after compaction.

    Hook Type: PostToolUse (matcher: ^(Write|Edit)$)
    Exit Codes: Always 0 (fail-open)

    Related:
    - Issue #1703 (lifecycle hook infrastructure)
    - Issue #1691 (anti-drift protocol)
    - ADR-008 (protocol automation lifecycle hooks)
    """

    import json
    import os
    import re
    import sys
    from datetime import UTC, datetime
    from pathlib import Path

    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _lib_dir = str(Path(__file__).resolve().parents[2] / "lib")
    if os.path.isdir(_lib_dir) and _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    try:
        from hook_utilities import get_project_directory as _get_project_directory
        from hook_utilities import lock_file as _lock_file
        from hook_utilities import unlock_file as _unlock_file

        def get_project_directory() -> Path | None:
            """Wrap shared utility returning Path for backward compat."""
            result = _get_project_directory()
            return Path(result) if result else None

    except ImportError:
        # Fallback if hook_utilities not available
        def get_project_directory() -> Path | None:
            """Resolve project root from env or git."""
            env_dir = os.environ.get("CLAUDE_PROJECT_DIR")
            if env_dir:
                return Path(env_dir)
            current = Path.cwd()
            while current != current.parent:
                if (current / ".git").exists():
                    return current
                current = current.parent
            return None

        _lock_file = None  # type: ignore[assignment]
        _unlock_file = None  # type: ignore[assignment]

    # Files that trigger checkpointing.
    #
    # Patterns anchor the basename to '/' or start-of-string so files like
    # `MyTODO.md`, `OLD-PLAN.md`, or `vendor/foo/SOMETODO.md` do not match.
    # The `.agents/plan*` pattern is also anchored to a `.agents/` segment so
    # unrelated files containing the substring elsewhere do not trigger
    # checkpoint writes that would evict real plan/session edits from the
    # 20-entry ring.
    PLAN_PATTERNS = [
        re.compile(r"(?:^|/)\.agents/sessions/[^/]+\.json$"),
        re.compile(r"(?:^|/)TODO\.md$", re.IGNORECASE),
        re.compile(r"(?:^|/)PLAN\.md$", re.IGNORECASE),
        re.compile(r"(?:^|/)\.agents/plan[^/]*\.md$", re.IGNORECASE),
        re.compile(r"(?:^|/)PROJECT-PLAN\.md$", re.IGNORECASE),
    ]


    def is_plan_file(file_path: str) -> bool:
        """Check if the modified file is a plan/session/TODO file."""
        # Normalize to forward slashes for pattern matching
        normalized = file_path.replace("\\", "/")
        return any(p.search(normalized) for p in PLAN_PATTERNS)


    def write_checkpoint(project_dir: Path, file_path: str, content: str) -> None:
        """Write a lightweight checkpoint for the modified plan file."""
        agents_dir = project_dir / ".agents"
        if not agents_dir.is_dir():
            return  # Consumer repo: skip silently to avoid creating .agents/
        hook_state_dir = agents_dir / ".hook-state"
        hook_state_dir.mkdir(parents=True, exist_ok=True)

        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
        checkpoint_file = hook_state_dir / f"plan-checkpoint-{today}.json"

        # Locked read-modify-write to prevent race conditions
        # Use os.open with O_CREAT to atomically create if missing, then lock before any I/O
        fd = os.open(checkpoint_file, os.O_RDWR | os.O_CREAT, 0o600)
        with os.fdopen(fd, "r+", encoding="utf-8") as f:
            if _lock_file is not None:
                _lock_file(f)
            try:
                # Read existing checkpoint data
                f.seek(0)
                file_content = f.read()
                existing = []
                if file_content.strip():
                    try:
                        existing = json.loads(file_content)
                        if not isinstance(existing, list):
                            existing = [existing]
                    except json.JSONDecodeError:
                        existing = []

                # Append new checkpoint entry
                entry = {
                    "file": file_path,
                    "timestamp": datetime.now(tz=UTC).isoformat(),
                    "summary": content[:500],
                }
                existing.append(entry)

                # Keep only last 20 entries to avoid unbounded growth
                if len(existing) > 20:
                    existing = existing[-20:]

                # Write back
                f.seek(0)
                f.truncate()
                json.dump(existing, f, indent=2, ensure_ascii=False)
                f.flush()  # Ensure data is on disk before releasing lock
            finally:
                if _unlock_file is not None:
                    _unlock_file(f)


    def main() -> int:
        """Check if modified file is a plan file and checkpoint if so."""
        # Skip if stdin is TTY
        if sys.stdin.isatty():
            return 0

        # Read stdin JSON
        try:
            stdin_data = sys.stdin.read()
            if not stdin_data.strip():
                return 0
            hook_input = json.loads(stdin_data)
        except Exception as e:
            print(f"[hook-error] invoke_plan_state_sync stdin: {type(e).__name__}: {e}", file=sys.stderr)
            return 0  # Fail-open

        # Valid JSON whose root is not an object would crash the .get() calls
        # below and break the fail-open contract.
        if not isinstance(hook_input, dict):
            print(
                f"[hook-error] invoke_plan_state_sync non-dict hook_input: {type(hook_input).__name__}",
                file=sys.stderr,
            )
            return 0  # Fail-open

        # Extract file path from tool input (tolerate non-dict tool_input)
        tool_input = hook_input.get("tool_input", {})
        if not isinstance(tool_input, dict):
            return 0  # Fail-open
        file_path = tool_input.get("file_path", "") or tool_input.get("path", "")

        if not file_path:
            return 0

        if not is_plan_file(file_path):
            return 0

        project_dir = get_project_directory()
        if not project_dir:
            return 0

        # Resolve and validate the file path stays within project_dir.
        # The file_path comes from hook_input which is harness-controlled but may
        # be tainted; reject paths that escape the project root to prevent
        # unintended reads (CWE-22 path traversal).
        try:
            project_dir_resolved = project_dir.resolve()
            full_path = Path(file_path)
            if not full_path.is_absolute():
                full_path = project_dir_resolved / file_path
            full_path = full_path.resolve()
            full_path.relative_to(project_dir_resolved)  # raises ValueError if outside
            normalized_file_path = str(full_path.relative_to(project_dir_resolved))
        except (OSError, ValueError) as e:
            print(
                f"[hook-error] invoke_plan_state_sync path-validate: {type(e).__name__}: {e}",
                file=sys.stderr,
            )
            return 0

        # Read the file content for summary
        try:
            content = full_path.read_text(encoding="utf-8") if full_path.is_file() else ""
        except OSError as e:
            print(
                f"[hook-error] invoke_plan_state_sync read: {type(e).__name__}: {e}",
                file=sys.stderr,
            )
            content = ""

        try:
            write_checkpoint(project_dir, normalized_file_path, content)
        except OSError as e:
            print(
                f"[hook-error] invoke_plan_state_sync checkpoint: {type(e).__name__}: {e}",
                file=sys.stderr,
            )

        return 0


    if __name__ == "__main__":
        sys.exit(main())
    return main()

_shim_dispatch()
