"""Corpus inventory and baseline ratchet for the memory placement gate (#5391).

Split out of ``check_memory_placement.py`` so both files stay under the
project's 500-line ceiling (`.claude/rules/code-quality.md`) and so the
ratchet is separately testable. Mirrors the split at
``agent_skill_discriminator_baseline.py`` (issue #4087), including its
direction of dependency: this module knows nothing about scoring, and the
scoring module imports from it. The two functions that need the flag
threshold take it as an argument rather than importing it back.

Baseline semantics, mirroring the discriminator: the gate is change-triggered
by default, ``--all`` scores every tracked memory, ``--update-baseline``
records the corpus, and a gate run with ``--baseline`` fails a recorded file
only when its score rises above the recorded value. A file absent from the
baseline uses the ordinary threshold.

Different than canonical: the discriminator records every agent, so a
recorded 0 there fails on a rise to 1. This baseline records only files
already at or above the flag threshold, i.e. the pre-existing debt. Recording
the other 1000+ memories at 0 would make any single new normative heading a
CI failure, a rule nobody chose, and would put a 65 KB artifact in the diff of
every memory rename.
"""

from __future__ import annotations

import sys
from pathlib import Path

from scripts.validation.agent_skill_discriminator_baseline import (
    refuse_dirty_scoring_inputs,
    tracked_paths_at_head,
)
from scripts.validation.memory_placement_signals import MAX_SCORE
from scripts.validation.portability_common import load_baseline, write_baseline

MEMORY_ROOT = ".serena/memories/"
DEFAULT_BASELINE_NAME = "memory_placement_baseline.json"

# Files under .serena/memories/ that are not memories. Kept in parity with the
# canonical memory loader's skip list, quoted verbatim from
# scripts/validation/memory_index.py:
#     _CANONICAL_SKIP_NAMES = frozenset({"README.md", "CLAUDE.md"})
_NON_MEMORY_NAMES: frozenset[str] = frozenset({"README.md", "CLAUDE.md"})

# ``_comment`` written into the baseline artifact. A constant so the committed
# file and the writer cannot drift apart.
BASELINE_COMMENT = (
    "Memory placement debt register (issue #5391). One entry per memory that "
    "already scored at or above the flag threshold when the gate landed; a "
    "file below the threshold is not recorded, so it is gated by the plain "
    "threshold and the ratchet never turns an ordinary signal into a failure. "
    "Generated by check_memory_placement.py --update-baseline. A gate run "
    "with --baseline fails a recorded file only when its score rises above "
    "the value here. The register may only shrink: migration issues #5392, "
    "#5393, and #5394 clear it."
)


# ---------------------------------------------------------------------------
# Corpus inventory
# ---------------------------------------------------------------------------


def is_memory_path(path: str) -> bool:
    """True when the path is a Serena memory file, not directory metadata."""
    norm = path.replace("\\", "/").strip()
    if not norm.startswith(MEMORY_ROOT) or not norm.endswith(".md"):
        return False
    return Path(norm).name not in _NON_MEMORY_NAMES


def filter_memory_paths(changed_files: list[str]) -> list[str]:
    """Keep only memory paths, de-duplicated, order-stable."""
    seen: set[str] = set()
    out: list[str] = []
    for raw in changed_files:
        path = raw.strip().replace("\\", "/")
        if not is_memory_path(path) or path in seen:
            continue
        seen.add(path)
        out.append(path)
    return out


def resolve_repo_path(repo_root: Path, relative_path: str) -> Path:
    """Return a resolved path only when it stays under the repo root."""
    resolved_root = repo_root.resolve()
    full_path = (resolved_root / relative_path).resolve()
    if not full_path.is_relative_to(resolved_root):
        raise ValueError(f"Path escapes repo root: {relative_path}")
    return full_path


def full_corpus_memory_paths(repo_root: Path) -> list[str] | None:
    """Every memory tracked at HEAD, or ``None`` when git could not answer.

    Read from a named ref rather than walked on disk, per
    `.claude/rules/ci-scripts.md` MUST-9: "A ratchet baseline is a claim about
    a ref, so the measurement behind it MUST NOT read untracked state". The
    ref reader is shared with the agent-skill discriminator's baseline module,
    where it is written generically: ``tracked_paths_at_head`` takes only a
    repo root and returns every tracked path.
    """
    tracked = tracked_paths_at_head(repo_root)
    if tracked is None:
        return None
    return sorted(path for path in tracked if is_memory_path(path))


def refuse_incomplete_corpus(corpus: list[str] | None, repo_root: Path) -> int | None:
    """Config-error code when a full-corpus scan produced no corpus.

    ``None`` from the reader means git could not answer, so what the commit
    contains is unknown; falling back to a directory walk would restore the
    defect the ref read exists to remove. An empty list means git answered and
    no memory is tracked, which would pass the gate and record a baseline that
    gates nothing (`.claude/rules/ci-scripts.md` MUST-12).
    """
    if corpus is None:
        print(
            f"Cannot list the files tracked at HEAD in {repo_root}. "
            "Full-corpus mode scores what the commit contains and will not "
            "fall back to a filesystem walk "
            "(.claude/rules/ci-scripts.md MUST-9).",
            file=sys.stderr,
        )
        return 2
    if not corpus:
        print(
            f"No memory files are tracked at HEAD in {repo_root} (examined 0 "
            f"of the paths under {MEMORY_ROOT}). Refusing a full-corpus run "
            "over an empty corpus: it would pass the gate and record a "
            "baseline that gates nothing.",
            file=sys.stderr,
        )
        return 2
    return None


# ---------------------------------------------------------------------------
# Baseline ratchet
# ---------------------------------------------------------------------------


def validate_baseline_scores(baseline: dict[str, int]) -> None:
    """Raise ``ValueError`` when a recorded score is outside 0..MAX_SCORE.

    ``portability_common.load_baseline`` is the canonical reader and vets the
    JSON shape and the integer type. Stricter than canonical: the placement
    score is a weighted sum of four booleans capped at ``MAX_SCORE``, so a
    value outside that range is a config defect. Above the ceiling the ratchet
    silently disables itself for that path; below zero it fails the path on
    every run.
    """
    for path, value in sorted(baseline.items()):
        if not 0 <= value <= MAX_SCORE:
            raise ValueError(
                f"Baseline score for {path!r} is {value}, outside the valid "
                f"range 0..{MAX_SCORE}. A placement score is a weighted sum "
                "of four booleans."
            )


def baseline_note(path: str, score: int, baseline: dict[str, int] | None) -> str:
    """Trailing report annotation showing the baseline comparison, if any."""
    if baseline is None:
        return ""
    recorded = baseline.get(path)
    if recorded is None:
        return " baseline=new"
    if score > recorded:
        return f" baseline={recorded} (regression)"
    return f" baseline={recorded}"


def refuses_write_from_outside(repo_root: Path) -> bool:
    """True when the process is not standing inside ``repo_root``.

    `.claude/rules/ci-scripts.md` MUST-7, quoted verbatim: "A script that
    resolves the repository root and then writes to it MUST confirm the
    current directory is inside the resolved root before the first write
    (``Path.cwd().resolve().is_relative_to(top_level)``)."
    """
    cwd = Path.cwd().resolve()
    if cwd.is_relative_to(repo_root):
        return False
    print(
        f"Refusing to write a baseline into {repo_root} while running from "
        f"{cwd}: --update-baseline records the checkout it is run from "
        "(.claude/rules/ci-scripts.md MUST-7).",
        file=sys.stderr,
    )
    return True


def refuse_ceiling_raise(
    proposed: dict[str, int], existing: dict[str, int], flag_threshold: int
) -> int | None:
    """Config-error code when an update would raise or grandfather a ceiling."""
    increased = {
        path: (existing[path], score)
        for path, score in proposed.items()
        if path in existing and score > existing[path]
    }
    for path, (old, new) in sorted(increased.items()):
        print(
            f"Refusing baseline update for {path}: score rose from {old} to "
            f"{new}. The placement baseline is a ceiling; a rising score is a "
            "regression, not a new floor.",
            file=sys.stderr,
        )
    if increased:
        return 2

    grandfathered = {
        path: score
        for path, score in proposed.items()
        if path not in existing and score >= flag_threshold
    }
    for path, score in sorted(grandfathered.items()):
        print(
            f"Refusing baseline update for {path}: new entry at score {score} "
            f"(>= {flag_threshold}) would grandfather a violation. Fix the "
            "placement first, then re-run --update-baseline.",
            file=sys.stderr,
        )
    return 2 if grandfathered else None


def update_baseline(
    baseline_path: Path,
    proposed: dict[str, int],
    *,
    repo_root: Path,
    allow_shrink: bool,
    flag_threshold: int,
) -> int:
    """Write the debt register for ``--update-baseline``.

    Rejects a rise on a recorded path and a new entry already at the flag
    threshold: the register is a ceiling, so recording either would forgive
    the exact condition the ratchet exists to catch. The first write has no
    existing file to compare against, so it records the corpus as it stands,
    pre-existing violations included; that is the grandfathering the ratchet
    is for, and every later write may only lower it.

    Refuses dirty or untracked memories: the path inventory comes from HEAD
    but scoring reads content from disk, so uncommitted changes produce a
    register that differs from what HEAD describes.
    """
    if refuses_write_from_outside(repo_root):
        return 2

    if refuse_dirty_scoring_inputs(repo_root, (MEMORY_ROOT,)):
        return 2

    if baseline_path.is_file():
        try:
            existing = load_baseline(baseline_path)
        except (OSError, ValueError, KeyError):
            existing = {}
        if rc := refuse_ceiling_raise(proposed, existing, flag_threshold):
            return rc

    return write_baseline(
        baseline_path,
        proposed,
        BASELINE_COMMENT,
        "signal points",
        repo_root=repo_root,
        allow_shrink=allow_shrink,
    )
